### ISSUE TITLE
*_in_alarm  and *generated_alerm  topics are not updated

### ISSUE THREAD

**Issue by y1ann1s** [ParadoxAlarmInterface/pai#107]
## Alarm system
EVO192 access mode (IP150, etc..).

## Environment
linux docker :dev
## Git branch
dev

## Describe the bug
during alarm triggered situation the  *_in_alarm  and *generated_alerm  topics are not updated

## To Reproduce
1. Start script '...'
2. Do something '....'
3. See error

## Logs
PLEASE DO NOT SEND LOGS IN CLEAR TEXT AS THEY MAY CONTAIN SENSITIVE INFORMATION
If you wish to add a log (which will greatly help us), please follow the following instructions:

1. Go to https://keybase.io/encrypt
2. Write 'jpbarraca' as the recipient
3. Write your log or add a link to the log file (if using services such as dropbox).
4. Click Encrypt
5. Save the result to a text file and add it as an attachment.

**Comment by yozik04** [comment]
Did it work in master?

**Comment by y1ann1s** [comment]
updated to latest dev cause used dev from docker will restest

**Comment by y1ann1s** [comment]
updated to latest dev ,still not working

**Comment by yozik04** [comment]
How long it was in alarm when you checked? Status update is every 10 seconds.

**Comment by y1ann1s** [comment]
will check this one again after 10 sec, but the generated alarm field is not also set

**Comment by yozik04** [comment]
@jpbarraca EVO zones currently has next properties:
- `presently_in_alarm` flag is set when zone triggers an alarm and goes off when partition is disarmed
- `generated_alarm` flag is set when alarm fires off and goes off when you next time arm the partition

Does SP/MG has something similar. I see only `alarm` property. Maybe we can rename to have a common name?
