### ISSUE TITLE
GSM interface is broken on master

### ISSUE THREAD

**Issue by gytisgreitai** [ParadoxAlarmInterface/pai#108]
This invokes `self.run_loop`, but this function is non existent. https://github.com/ParadoxAlarmInterface/pai/blob/master/paradox/interfaces/gsm_interface.py#L94

Are fixes still done for master, or everybody should switch to dev?

**Comment by jpbarraca** [comment]
We usually only apply critical changes to master. Try dev. This code was extensively refactored.

**Comment by gytisgreitai** [comment]
ok, thanks
