### ISSUE TITLE
dev: MQTT raw events published into wrong topic

### ISSUE THREAD

**Issue by gytisgreitai** [ParadoxAlarmInterface/pai#112]
MQTT raw events go into` paradox/events` instead of `paradox/events/raw`. Afaik the problem is with `.format()` function on this line https://github.com/ParadoxAlarmInterface/pai/blob/6ed2fc1702be87313931ecb391e2eb38db94a4c1/paradox/interfaces/mqtt/basic.py#L173

**Comment by yozik04** [comment]
Thanks
