### ISSUE TITLE
Push bullet notifications

### ISSUE THREAD

**Issue by dtheodoropoulos** [ParadoxAlarmInterface/pai#116]
Hi, you have done excellent work. 
I want to enable pushbullet notification on my cellphone , but i can't figure out what goes to those fields KEY , SECRET , CONTACTS.
# Pushbullet
PUSHBULLET_ENABLE = False
PUSHBULLET_KEY = ''                     # Authentication key used for Pushbullet
PUSHBULLET_SECRET = ''                  # Authentication secret used for Pushbullet
PUSHBULLET_CONTACTS = []                # Pushbullet user identifiers for notifications and interaction

**Comment by jpbarraca** [comment]
Hi,

The PUSHBULLET_SECRET was now deprecated in the dev branch. Ignore it.
The PUSHBULLET_KEY : go here: https://www.pushbullet.com/#settings/account and create an access token.
PUSHBULLET_CONTACTS = A list of contacts that will receive the messages and can interact with the alarm.
