### ISSUE TITLE
What is my panel ID?

### ISSUE THREAD

**Issue by roinou** [ParadoxAlarmInterface/pai#118]
Thank you for this nice project. I managed to connect to my **IP150 version 20, firmware: 4.42** and my **EVO192 version 3.20 build 10**. I changed the config according to the wiki and I get _HomeAssistant_ to display states of my sensors, it's working OK so far.

Now, I think my EVO firmware is a bit old, so I asked my provider to upgrade it, but I forgot to disconnect PAI, so they know I've been fideling with the system and they are a bit reluctant to do so.

Therefore, I try to connect using **Babyware**, but fail doing so. It's ok all the way to the panel connection which fails because of wrong panel ID. I tried 0000, 0, 0001 and all sorts of combination, without success. It is worth noting that the panel password wasn't default _0000_ but something else that I luckily guessed, meaning my provider changed the default value.

**Question**: as PAI manages to connected to the panel, can it give me the panel ID that is being used?

**Comment by yozik04** [comment]
Hi @roinou, connect with Babyware via PAI. Enable IP Interface in settings. Then in settings you can find panel id.

**Comment by roinou** [comment]
I tried many things, but it won't work. I get some unknown messages in PAI debug, and in the end Babyware fails because of too many retries. I guess my firmware is too old, so there are some things that you guys missed. Can't blame you, I can only blame my installer for not upgrading the firmwares.

**Comment by yozik04** [comment]
Can you edit code?
Add
```python
logger.debug('panel_id: %d', reply.fields.value.panel_id)
```
Before this line:
https://github.com/ParadoxAlarmInterface/pai/blob/7ede0bc94d74ee1d62037e53390c5bd9ff101300/paradox/paradox.py#L148

It will be in decimal. Convert it to hex and you will get the right panel_id

**Comment by roinou** [comment]
I works!! Converting to HEX gave we the correct Panel ID, I can now fully connect in Babyware.

Thanks a lot for the support, I believe this can be a useful debug for the rest of us.

**Comment by idtazio** [comment]
Hi,
I have an issue and maybe someone is able to help:
I messed up something with Babyware and I now have the Panel ID different from the default ... but I don't know it.
I know the password but not the Panel ID.
Do you know how I can reset it / change it  / or find which one is?

**Comment by yozik04** [comment]
Check you'r panel's manual and find it via installation mode using your keypad. Or run PAI in debug mode with dumping messages. It logs it in one of the initial packets.

**Comment by idtazio** [comment]
Thanks ... I am not familiar with PAI. What do I need to run it in debug mode?

**Comment by yozik04** [comment]
Use the keypad then :) To get familiar with PAI read the wiki.

**Comment by idtazio** [comment]
Thanks, I will check the Keypad manual to see if it is possible to change the Panel ID. Not sure because the Keypad is only numeric

**Comment by idtazio** [comment]
Done :):) 
I was able to change it through the Keypad. Thank you for the suggestion :)

**Comment by Thodpaz** [comment]
hello everyone..can anybody help me about my panel id?? i cant find it...what is PAI? and how can i find my code to log it at babyware?? thanks

**Comment by yozik04** [comment]
@Thodpaz your installer should know.

**Comment by Thodpaz** [comment]
> @Thodpaz your installer should know.

my installer has die before a year and nobody knows

**Comment by yozik04** [comment]
I remember somebody has created a brute force tool for it. Try to find... Maybe he/she will share. Password is just 4 digits. Try 0000 or None at first.

**Comment by Thodpaz** [comment]
i try both and nothing... do you remember any element to help about brute force tool??

**Comment by yozik04** [comment]
Probably somebody mentioned in gitter.

**Comment by Pream04** [comment]
I have an issue with my ip150, when it's connected to my company network there is no internet light blinking, the IP was set as static to the alarm module and I am able to ping the IP and from my network switch I can see the ip150 Mac add  tagged to IP assigned its up and active. Where as when connected to a public sim card router there is internet light. Can someone pls help with this
