### ISSUE TITLE
ESP32 - TCPtoSerial

### ISSUE THREAD

**Issue by cybertza** [ParadoxAlarmInterface/pai#119]
So i have the following issue at the moment.

If i set config file to Serial and do the following
/home/ha/dev/ttyV0

`socat pty,link=/home/ha/dev/ttyV0,waitslave tcp:172.16.103.60:23`
to create a virtual port
Then i am able to connect to the panel and i can read data just fine.

But i don't know socat, and it doesn't seem reliable (i haven't tried to make it either).

So naturally i would like to use the built in ability to connect direct to TCP socket. 

Then i never manage to connect.

Any ideas?

```

# Connection Type
CONNECTION_TYPE = 'IP'                  # Serial or IP

# Serial Connection Details
SERIAL_PORT = '/home/ha/dev/ttyV0'              # Pathname of the Serial Port
SERIAL_BAUD = 9600              # 9600 for SP/MG. For EVO: Use 38400(default setting) or 57600

# IP Connection Details
IP_CONNECTION_HOST = '172.16.103.60'    # IP Module address when using direct IP Connection
IP_CONNECTION_PORT = 23             # IP Module port when using direct IP Connection
IP_CONNECTION_PASSWORD = b'paradox' # IP Module password. "paradox" is default.
IP_CONNECTION_SITEID = None             # SITE ID. IF defined, connection will be made through this method.
IP_CONNECTION_EMAIL = None              # Email registered in the site
IP_CONNECTION_PANEL_SERIAL = None  # Use a specific panel. Set it to None to use the first
IP_CONNECTION_BARE = True      # No not expect an IP150 module. Used this for base Serial over TCP tunnels


```

```
2019-12-15 10:06:45,395 - INFO     - PAI.paradox.connections.ip_connection - Connecting to IP module. Try 1/3
2019-12-15 10:06:45,397 - WARNING  - PAI.paradox.connections.ip_connection - Dangling data in the receive buffer: b'e014130c0f0c06000f00000000000041424e42204245414d2020202020202000000000006be014130c0f0c06010f00000000000041424e42204245414d2020202020202000000000006ce014130c0f0c06000f00000000000041424e42204245414d2020202020202000000000006b'
2019-12-15 10:06:45,398 - WARNING  - PAI.paradox.connections.ip_connection - Dangling data in the receive buffer: b'e014130c0f0c06000f00000000000041424e42204245414d2020202020202000000000006be014130c0f0c06010f00000000000041424e42204245414d2020202020202000000000006ce014130c0f0c06000f00000000000041424e42204245414d2020202020202000000000006b'
2019-12-15 10:06:45,398 - WARNING  - PAI.paradox.connections.ip_connection - Dangling data in the receive buffer: b'e014130c0f0c06000f00000000000041424e42204245414d2020202020202000000000006be014130c0f0c06010f00000000000041424e42204245414d2020202020202000000000006ce014130c0f0c06000f00000000000041424e42204245414d2020202020202000000000006b'
2019-12-15 10:06:45,399 - WARNING  - PAI.paradox.connections.ip_connection - Dangling data in the receive buffer: b'e014130c0f0c06000f00000000000041424e42204245414d2020202020202000000000006be014130c0f0c06010f00000000000041424e42204245414d2020202020202000000000006ce014130c0f0c06000f00000000000041424e42204245414d2020202020202000000000006b'

```

'
## Alarm system

sp5050
## Environment

linux arm

### Git branch

dev
## Logs (if required)
<!-- PLEASE DO NOT SEND LOGS IN CLEAR TEXT AS THEY MAY CONTAIN SENSITIVE INFORMATION
If you wish to add a log (which will greatly help us), please follow the following instructions:

**Comment by yozik04** [comment]
Looked at the code and I think we lost this functionality with rewrites. It tries to send ip150 payloads to serial which is wrong.

**Comment by yozik04** [comment]
Should be working now. Please try.

**Comment by yozik04** [comment]
@cybertza Did you tried?

**Comment by cybertza** [comment]
To be honest I have not, but I need to, 
I started trying to load the dev build, then I had a error for something called paradox module  not found, but then didn’t have time to look for my mistake.

Then I started to tinker with something else.

I can just do a pull from the dev build to test?

**Comment by yozik04** [comment]
You can pull from master it is on 1.4.0.

**Comment by cybertza** [comment]
Ok works in DEV.
Busy trying the hass.io
but getting stuck with the connection type
Exception: Error parsing configuration: Invalid value type <class 'NoneType'> for config argument CONNECTION_TYPE. Allowed are: [<class 'str'>
will let you know when i win.

**Comment by cybertza** [comment]
I see the pull request is there #https://github.com/ParadoxAlarmInterface/hassio-repository/pull/2  for the fix.

**Comment by cybertza** [comment]
Hi

This seems to work now, please add version tracking to the startup message <3.

Thanks for the fix.
See the Hass.io integration is getting there.
Do you want me to create a guide for you for the ESP32 build i did?

Basically an   ESP32 + LM2596 directly connected to the panel, no other wires or anything.
I did this since my IP150 got fried by lightning. It seems to work rather stable with the socat, so i'm sure it will work just as good if not better with this version.

**Comment by cybertza** [comment]
> Hi
> 
> This seems to work now, please add version tracking to the startup message <3.
> 
> Thanks for the fix.
> See the Hass.io integration is getting there.
> Do you want me to create a guide for you for the ESP32 build i did?
> 
> Basically an ESP32 + LM2596 directly connected to the panel, no other wires or anything.
> I did this since my IP150 got fried by lightning. It seems to work rather stable with the socat, so i'm sure it will work just as good if not better with this version.

Also total cost is like 10% of the cost of the IP150, its just wireless thou, but im sure if you wanted wired you could use and arduino+ether to achieve the same thing. Personally i have had no issues with the wireless.

**Comment by yozik04** [comment]
> Do you want me to create a guide for you for the ESP32 build i did?

That would be great! Feel free to fill the wiki!

**Comment by yozik04** [comment]
That pull request is outdated and can not be merged. Can you show your json?

**Comment by cybertza** [comment]
Will do when i get a second.
Did the ESP guide for you 🥇

**Comment by yozik04** [comment]
@cybertza Great guide. 💪 Thank you!
I think `IP_CONNECTION_BARE = True` is mandatory

I reorganised sections a bit as well.

**Comment by cybertza** [comment]
sweet thanks.

**Comment by cyrenaud** [comment]
> Hi
> 
> This seems to work now, please add version tracking to the startup message <3.
> 
> Thanks for the fix.
> See the Hass.io integration is getting there.
> Do you want me to create a guide for you for the ESP32 build i did?
> 
> Basically an ESP32 + LM2596 directly connected to the panel, no other wires or anything.
> I did this since my IP150 got fried by lightning. It seems to work rather stable with the socat, so i'm sure it will work just as good if not better with this version.

Howzit! I am in the same boat re lightning frying my IP150. Did you create the guide for your ESP32 build? Can you send me a link if you did? 

Much appreciated.

**Comment by yozik04** [comment]
@cyrenaud Guide is in the wiki: https://github.com/ParadoxAlarmInterface/pai/wiki/Connection-methods#serial-over-ip-esp32
