### ISSUE TITLE
Invalid PC Password when it contains 0

### ISSUE THREAD

**Issue by kovacsbalu** [ParadoxAlarmInterface/pai#120]
## Alarm system
Panel SP7000 version 6.10 build 2
IP 150 v.139

## Environment
RPI
PY3

## Git branch
master

## Describe the bug
Wrong encoding when pc password contains 0
00 00 00 00 17 06 10 02 80 80 9a 9a 19
Save connection raw with ParadoxIP150v2
00 00 00 00 17 06 10 02 80 80 90 90 19

It works with passwd 4444
00 00 00 00 17 06 10 02 80 80 44 44 19

## To Reproduce
Set PC password to 9090

## Logs
2019-12-16 13:07:09,391 - INFO - MainThread - PAI.paradox.paradox - Starting communication
2019-12-16 13:07:09,663 - INFO - MainThread - PAI.paradox.hardware.spectra_magellan.panel - Initializing communication
2019-12-16 13:07:09,787 - ERROR - MainThread - PAI.paradox.paradox - Got ERROR Message: Invalid PC Password
2019-12-16 13:07:10,680 - DEBUG - MainThread - PAI.paradox.paradox - Request retry (1/5)

**Comment by iondarie** [comment]
I also use SP7000 and my password contains 0 and i have no issues.

**Comment by yozik04** [comment]
😱

**Comment by kovacsbalu** [comment]
> SP7000 version 6.90 build -1
> IP150 version: 4.42
> 
> I also use SP7000 and my password contains 0 and i have no issues.

Good for you :) 
As i can see you have different panel and ip version.

**Comment by ipetrovits** [comment]
Hi, can confirm the same on:
ParadoxAlarmInterface/pai/Docker/Hassbian/RPI4B
SP6000@5.18
IP150@1.34
The strangest part - it worked without probem with 0000, and after a poweroff-restart of RPI host, it just stopped with wrong PC password. The new password has no 0, connection established without problems.

**Comment by yozik04** [comment]
Password 0000 is exception and treated differently.

**Comment by kunago** [comment]
I can confirm the report as I am also using the same IP150 firmware and have the same issue. Once I changed the PIN to one not containing "0", I could login.

**Comment by yozik04** [comment]
> I can confirm the report as I am also using the same IP150 firmware and have the same issue. Once I changed the PIN to one not containing "0", I could login.

@kunago what panel?

**Comment by kunago** [comment]
The panel is EVO192, v. 3.20.016

**Comment by yozik04** [comment]
@kunago and IP150 module version?

**Comment by yozik04** [comment]
Just tested what sends Babyware to my EVO192 with IP150 1.32
```
(pass)->(hex)
0000->0000
9090->9090
1234->1234
0909->0909
```
Babyware does not encode "0"

**Comment by yozik04** [comment]
Can somebody for whom "0" in password works try to connect with Babyware to PAI and see what is sent there for `0000`, `9090`, `1234`, `0909`. Just type in connection password in Babyware, save and attempt to connect. On Installer login step required payload will appear.

Config:
```
# Enable logs
LOGGING_LEVEL_CONSOLE = logging.DEBUG
LOGGING_DUMP_PACKETS = True

IP_INTERFACE_ENABLE = True
```

Grep:
```
Line to grep:
APP -> IPI (payload) b'00000000

Decoding:
APP -> IPI (payload) b'0000 0000 zzzz zzzz xxxx yyyy ............
zzzz zzzz - product_id + firmware versions
xxxx - panel id
yyyy - password
```

**Comment by yozik04** [comment]
I have removed `0` encoding from `dev` and created FAQ page. https://github.com/ParadoxAlarmInterface/pai/wiki/FAQ#authentication-failed-wrong-password

**Comment by TomasJancauskas** [comment]
When trying to encode password myself exception is thrown:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paradox/paradox.py", line 151, in connect_async
    result = await self.panel.initialize_communication(reply, cfg.PASSWORD)
  File "/usr/local/lib/python3.7/site-packages/paradox/hardware/spectra_magellan/panel.py", line 154, in initialize_communication
    encoded_password = self.encode_password(password)
  File "/usr/local/lib/python3.7/site-packages/paradox/hardware/panel.py", line 111, in encode_password
    raise (Exception("Not supported password {}".format(password)))`

**Comment by yozik04** [comment]
You are not on `dev`.

**Comment by NapalmCandy** [comment]
It is a common problem because the system understand the Hexadecimal numbers, so instead using a 0 you will need to put an A

Example: 0909 -> A9A9

Then will work without problems
