### ISSUE TITLE
Startup script does it work?

### ISSUE THREAD

**Issue by stratosnik** [ParadoxAlarmInterface/pai#121]
## Alarm system
Spectra SP6000 (serial connection). It is the same for all

## Environment
- RPI rasbian
- Python 3.7

## Git branch
Master, also dev.

## Describe the bug
Script "run.sh" from console_scripts does not find "paradox", should it be in pai directory?

## To Reproduce
Try to run it.

**Comment by yozik04** [comment]
run.sh fixed in dev. Please try.

**Comment by stratosnik** [comment]
OK its fixed in dev
