### ISSUE TITLE
PRT3 support

### ISSUE THREAD

**Issue by judge** [ParadoxAlarmInterface/pai#123]
Hello,

Paradox has a [PRT3 module](http://www.paradox.com/Products/default.asp?CATID=7&SUBCATID=75&PRD=234) which can be used as a home automation module (its called printer module by default). As far as I understand it is a serial interface for the panel. 
Do you guys have plans to support this module with serial connection?

By the way I have one of this module connected to a Raspberry PI (it has an USB port too), and I'm using [this](https://github.com/DaveOke/ParadoxHassMQTT) app to publish events to mqtt. It works fine for my zones but it does not pick arm/disarm states and this project seems more mature.

**Comment by yozik04** [comment]
Hello,
Neither me, neither @jpbarraca has this module. Most probably it is same serial interface. But no idea exactly.
We support serial connection. You can try to hook it up and see. Maybe it will work out of the box =)

**Comment by judge** [comment]
Actually I tried :), but it does not work:

```2019-12-28 07:44:04,198 - INFO     - PAI.paradox.connections.serial_connection - Connecting to serial port /dev/ttyUSB0
2019-12-28 07:44:04,204 - INFO     - PAI.paradox.connections.serial_connection - Serial port open
2019-12-28 07:44:04,205 - INFO     - PAI.paradox.paradox - Connecting to panel
2019-12-28 07:44:04,206 - INFO     - PAI.paradox.paradox - Initiating communication
2019-12-28 07:44:10,225 - ERROR    - PAI.paradox.paradox - Failed to connect: Panel did not replied to InitiateCommunication
2019-12-28 07:44:10,227 - ERROR    - PAI - Unable to connect to alarm
```

I'll try to figure out what is happening but I know nothing about serial interfaces (nor python). :(

**Comment by yozik04** [comment]
Then just return/sell PRT3 and connect RPi instead of it. Win-win!

**Comment by jpbarraca** [comment]
The PRT3 is not a simple USB interface as it converts the messages to another format. I do not see the point of adding this interface as it would require a large effort ( we do not have it) and a simple usb-serial interface or RPI can be used.

**Comment by judge** [comment]
So if I get one of these USB-TTL modules (like [this?](https://www.rpibolt.hu/termek/usb_20_-_uart_ttl_33v__5v_serial_konverter_cp2102.html)) and I connect my RPi through USB with cables Rx, Tx and GND on the panel then I should have serial connection setup right?

**Comment by yozik04** [comment]
Exactly!

**Comment by judge** [comment]
Sound great! I'll close this and try it with the direct serial connection.
Thanks a lot guys! 👍
