### ISSUE TITLE
No handler for message 5

### ISSUE THREAD

**Issue by Trefex** [ParadoxAlarmInterface/pai#126]
```
2020-01-03 13:25:54,314 - ERROR    - PAI.paradox.lib.async_message_manager - No handler for message 5
Detail: Container: 
    fields = Container: 
        data = b'RG\x80\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 70)
        value = Container: 
            po = Container: 
                command = 5
                status = Container: 
                    reserved = False
                    alarm_reporting_pending = False
                    Winload_connected = True
                    NeWare_connected = False
            packet_length = 71
            control = Container: 
                ram_access = True
                eeprom_address_bits = 0
            bus_address = 0
            address = 2
            data = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 64)
        offset1 = 0
        offset2 = 70
        length = 70
    checksum = b'\x1b' (total 1)
```

I receive this sometimes when doing some arming / disarming via Home Assistant.

I have not seen that many errors when running the docker on my Windows PC, but i see this now more frequent when running on the Docker NAS.

Is the async handler robust or is something wrong in my setup?

**Comment by Trefex** [comment]
Using tag latest from DockerHub.

**Comment by Trefex** [comment]
Might be coincidence with arm/disarm as i receive also this message 4-5 mins after arm/disarm.

**Comment by yozik04** [comment]
dupe #89 
Happens sometimes and it is fine. Reason unknown.

**Comment by Trefex** [comment]
Hi @yozik04 i still experience this with version 2.2.0

**Comment by yozik04** [comment]
@drzoidberg33 it is fine, relax 😎

**Comment by drzoidberg33** [comment]
> @drzoidberg33 it is fine, relax 😎

Thanks, it's working great btw, but I've only had it up for 30 minutes so far 👍

**Comment by rtATvw** [comment]
Possibly interesting variations of mostly non-truncated message 5 PDUs from:
IP(114) Module version 20, firmware: 6.0
Panel Identified EVO192 version 7.70 build 1
[message 5.txt](https://github.com/ParadoxAlarmInterface/pai/files/14602855/message.5.txt)

**Comment by yozik04** [comment]
I have added IO_TIMEOUT setting. Please try to play with it. Default is 0.5 seconds.
