### ISSUE TITLE
Got ERROR Message: Invalid record type

### ISSUE THREAD

**Issue by pherbel** [ParadoxAlarmInterface/pai#127]
## Alarm system
EVOHD version 4.5
access mod: IP150 - IP Module version 20, firmware: 4.42, serial: 710626d0
## Environment
- running latest docker image on windows service with docker for windows

## Git branch
master with docker latest.

## Describe the bug
pai can connect to module and is getting data like labels, zones, users, etc
I have warnings, but it seems working.

>INFO     - PAI.paradox.hardware.panel - Updating Definitions from Panel
>WARNING  - PAI.paradox.paradox - Missing element ID in system/?, m/m: 45/4, message: Special events: WinLoad in (connected)
> WARNING  - PAI.paradox.hardware.panel - Unable to properly decode label b'Bejarat nyit\x9ds' using the utf-8 encoding.

The main problem is I've got error logs
> INFO     - PAI.paradox.paradox - Connection OK
> ERROR    - PAI.paradox.paradox - Got ERROR Message: Invalid record type
> ...
> ERROR    - PAI.paradox.paradox - Lost communication with panel

The system reconnect again and again

And it seems there is no data on MQTT topics.

## To Reproduce
1. I just started docker image

Any help appreciated

Thanks

**Comment by yozik04** [comment]
What actually is there: `b'Bejarat nyit\x9ds'` ?

Please enable all debug and send me.

EVOHD version 4.5 is very old...

**Comment by pherbel** [comment]
Thanks for the quick response.

Actually the language is Hungarian, but it should work with utf-8. b'Bejarat nyit\x9ds' have been fix now with 'Bejarat nyitas' string.

Also in find this config
> STATUS_REQUESTS = list(range(1, 6))

And it seems it solved the error log

>ERROR - PAI.paradox.paradox - Got ERROR Message: Invalid record type

I have enbled MQTT with this config, but it seems still can't see mqtt info

> MQTT_ENABLE = True			# Enable MQTT Interface
> MQTT_HOST = 'localhost' 		# Hostname or address
> MQTT_PORT = 1883        		# TCP Port
> MQTT_KEEPALIVE = 60

**Comment by jpbarraca** [comment]
The panel is fully initialized and PAI starts issuing status requests? In debug mode you will see if something is sent to the MQTT interface

**Comment by yozik04** [comment]
> localhost

Docker container does not know what is `localhost` type IP address there.

**Comment by pherbel** [comment]
Good catch.
I didn't realize the localhost issue.

Now I see the messages on MQTT topics.

Thank you for your awesome support!

Now we can close this.

**Comment by pjuhel2** [comment]
Hello, How did you succeed to update the EVOHD?
