### ISSUE TITLE
Panel connection status

### ISSUE THREAD

**Issue by clau-bucur** [ParadoxAlarmInterface/pai#129]
It would be nice to add a topic to indicate whether PAI is currently connected to the panel.

## Feature description
In my case, connecting with IP150, if IP150 becomes unreachable and PAI cannot connect to it, there's no indication of a failure.
All the sensors show online, paradox/interface/MQTTInterface is also online.
A new sensor similar to paradox/interface/MQTTInterface would be helpful to indicate that the panel is currently online.

**Comment by Trefex** [comment]
Does this mean the sensors keep showing "Clear" ?

Should there be a "alive" timeout on each update of each sensor?

**Comment by jpbarraca** [comment]
We know if we are connected or not.
We can retain the topic with "online" and then change it to offline if it disconnects (or the mqtt interface dies)

**Comment by yozik04** [comment]
We can have `online`, `offline`, `error`?

**Comment by jpbarraca** [comment]
initializing, online, offline, error
We may send pubsub messages and the mqtt interface (or the other interfaces) issue notifications. Some are already in place.

**Comment by clau-bucur** [comment]
> Does this mean the sensors keep showing "Clear" ?
Yes, all of them are in "clear" state (topic open=False).
And the partitions show "disarmed" even though my system is currently armed.

> Should there be a "alive" timeout on each update of each sensor?
I think a global "status" topic should suffice.

**Comment by Trefex** [comment]
@clau-bucur @jpbarraca @yozik04 

For me all sensor status should switch to "Unknown" or something else when no status has been received for a long time. I do assume the status of each sensor is polled every 10 seconds?

**Comment by clau-bucur** [comment]
The sensors use paradox/interface/MQTTInterface for Availability status, which in this case is Online.

**Comment by Trefex** [comment]
Ah gotcha. Then I think they should also be linked to the new status, so that if either the MQTT interface or the Panel link goes down, the sensors become aware and would allow for notification triggers.

**Comment by clau-bucur** [comment]
Do you have any idea when this could be implemented?

**Comment by yozik04** [comment]
created `paradox/interfaces/run_status`. It can have states: `error, initializing, paused, online, stopped, offline`
**BREAKING CHANGE:** `paradox/interfaces//MQTTInterface` is not published anymore

**Comment by Trefex** [comment]
What do we have to change in HomeAssistant?

**Comment by yozik04** [comment]
Nothing. Autodiscovery covers the change.

**Comment by clau-bucur** [comment]
Great. I'll test it.

**Comment by Trefex** [comment]
Is the status even used in HA directly?

**Comment by yozik04** [comment]
Yes it is used for all autodiscovered elements

**Comment by clau-bucur** [comment]
![image](https://user-images.githubusercontent.com/47672949/72620650-6699b780-3948-11ea-9c53-86c171aa94aa.png)
The payload on/off for the generated entities is "True" or "False", however the run_status has different values (error, initializing, paused, online, stopped, offline).
When I stopped PAI all entities went offline. I'll check what happens when the panel becomes unavailable.

**Comment by yozik04** [comment]
payload_on is for value. Not availability.

**Comment by cybertza** [comment]
Hi Guys

Great work once again 🥇 
Wanted to open the same thing :p
The correct way to handle this is with the available topic, Yes
obviously the panel and the sensors could have separate topics, but this would defeat the purpose as if it can't comm, everything should say not available.

HASS.io only supports 2 states as far as i know:
Online/Offline
I am not sure what the availability topic as 
error, initializing, paused, online, stopped, offline 
can have ref:
https://www.home-assistant.io/integrations/binary_sensor.mqtt/#availability_topic
`availability_topic
(string)(Optional)

The MQTT topic subscribed to receive birth and LWT messages from the MQTT device. If availability_topic is not defined, the binary sensor availability state will always be available. If availability_topic is defined, the binary sensor availability state will be unavailable by default.

payload_available
(string)(Optional)

The payload that represents the online state.

Default value:

online

payload_not_available
(string)(Optional)

The payload that represents the offline state.

Default value:

offline`

Having other states in that same topic may cause problems.

Nothing wrong with having a state topic that is unrelated to this and attaching it to the panel's data itself as a sensor.
![image](https://user-images.githubusercontent.com/20600538/72687634-87107000-3b08-11ea-9f4b-be7d1274ee5c.png)


Thanks again for the great work
Cyber T za

**Comment by yozik04** [comment]
The reason why we can not have multiple topics is that MQTT connection can only publish one topic on last will.

@cybertza What that red arrow means in the image you posted? Do you know how to add sensor value there?

**Comment by yozik04** [comment]
Looks like we need a separate topics anyway because hass changes sensor availability only on "online", "offline" payload, ignores all other...
https://github.com/home-assistant/home-assistant/blob/05ecc5a1355c7af11b5d310470a6171528dc7a2b/homeassistant/components/mqtt/__init__.py#L1102

**Comment by yozik04** [comment]
I have added `run_status` sensor and `availability` topic as well.

All typical sensors (alarm_panels, binary_sensors) use `availability` topic. And availability is `online` only when pai is fully functional or status requests are paused (used for IP Interface, Babyware connection). This is fine and how it actually should be.

**Stupid thing:** run_status sensor also uses `availability` topic. But it will have state unavailable in case of an `error` or `stop` state in PAI because of `availability` is `offline` at that moment.

I can remove `availability_topic` from run_status sensor but then if pai was killed -9 or there was a network problem between pai and MQTT run_status will keep previous `online` state.
