### ISSUE TITLE
Time Sync uses UTC not local time

### ISSUE THREAD

**Issue by camadio** [ParadoxAlarmInterface/pai#130]
## Alarm system
MG5050, access mode IP150

## Environment
- RPI 3
- Hass.io version 0.104.3

## Git branch
standard

## Describe the bug
From what I can tell, if the "SYNC_TIME" option is set to true, it uses UTC time, not local time to set the Paradox panel time.

## To Reproduce
1. Set a different timezone than UTC
2. Set "SYNC_TIME" to true
3. Start addon module in hassio
4. Panel time will be updated
5. See error

**Comment by yozik04** [comment]
How PAI is installed?

**Comment by yozik04** [comment]
Ahh, hassio. Looks like hass io does not pass timezone to the addon.

**Comment by yozik04** [comment]
Probably this will help: https://github.com/home-assistant/hassio-supervisor/issues/732

**Comment by yozik04** [comment]
@camadio Save addon config. Remove the addon and install Development version from the same repository. Does it solve the problem?

**Comment by camadio** [comment]
@yozik04 thanks that has the correct time now.
