### ISSUE TITLE
wrong panel ID.

### ISSUE THREAD

**Issue by zed74** [ParadoxAlarmInterface/pai#134]
Hello, i posted on here before. Here is a screenshot of what error i get when connecting to the panels, have access to no Id or password, can the paradox board be reset to factory?
![045D4FBE-C080-4003-A01F-BA4D0FE4DC3F](https://user-images.githubusercontent.com/60713857/73898123-c8fd2c80-48e4-11ea-8afa-2332ad6f7cdc.jpeg)

![231B9B2A-90EB-4C52-96BF-8F0FFDA07DD1](https://user-images.githubusercontent.com/60713857/73898042-89364500-48e4-11ea-993f-7f352e6575a7.jpeg)

**Comment by yozik04** [comment]
It is not nice to create multiple issues about the same problem, you got reply already. Developers of this project are neither professional installers neither hackers. We just provide an interface for home automation.
