### ISSUE TITLE
small typo on mqtt for keypads

### ISSUE THREAD

**Issue by cybertza** [ParadoxAlarmInterface/pai#136]
HASS.io ver: 2.1.0 

BUG
MQTT topic for keypad gets a //

:p

/keypads//signal_

## Alarm system
Describe your panel model (ex: EVO192, Spectra SP4000, Magellan MG5050), access mode (Serial, IP150, etc..).

## Environment
- Windows, Linux, RPI...
- Python version

## Git branch
Which Git branch you use. Did you tried "dev" branch? Please try before posting.

## To Reproduce
1. Start script '...'
2. Do something '....'
3. See error

## Logs
PLEASE DO NOT SEND LOGS IN CLEAR TEXT AS THEY MAY CONTAIN SENSITIVE INFORMATION
If you wish to add a log (which will greatly help us), please follow the following instructions:

1. Go to https://keybase.io/encrypt
2. Write to us
   1. Write 'jpbarraca' as the recipient if you have SP/MG panel
   2. Write 'yozik04' as the recipient if you have EVO panel
3. Write your log or add a link to the log file (if using services such as dropbox).
4. Click Encrypt
5. Save the result to a text file and add it as an attachment.

> 2020-02-10 18:41:59,554 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//ac_loss_trouble=False
> 2020-02-10 18:41:59,554 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//battery_failure_trouble=False
> 2020-02-10 18:41:59,554 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//supervision_failure_trouble=False
> 2020-02-10 18:41:59,554 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//signal_strength=10
> 2020-02-10 18:41:59,555 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//ac_loss_trouble=False
> 2020-02-10 18:41:59,555 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//battery_failure_trouble=False
> 2020-02-10 18:41:59,555 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//supervision_failure_trouble=False
> 2020-02-10 18:41:59,555 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//signal_strength=10
> 2020-02-10 18:41:59,556 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//ac_loss_trouble=False
> 2020-02-10 18:41:59,556 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//battery_failure_trouble=False
> 2020-02-10 18:41:59,556 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//supervision_failure_trouble=False
> 2020-02-10 18:41:59,556 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//signal_strength=10
> 2020-02-10 18:41:59,556 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//ac_loss_trouble=False
> 2020-02-10 18:41:59,557 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//battery_failure_trouble=False
> 2020-02-10 18:41:59,557 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//supervision_failure_trouble=False
> 2020-02-10 18:41:59,557 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//signal_strength=10
> 2020-02-10 18:41:59,557 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//ac_loss_trouble=False
> 2020-02-10 18:41:59,557 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//battery_failure_trouble=False
> 2020-02-10 18:41:59,557 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//supervision_failure_trouble=False
> 2020-02-10 18:41:59,558 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//signal_strength=10
> 2020-02-10 18:41:59,558 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//ac_loss_trouble=False
> 2020-02-10 18:41:59,558 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//battery_failure_trouble=False
> 2020-02-10 18:41:59,558 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//supervision_failure_trouble=False
> 2020-02-10 18:41:59,558 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//signal_strength=10
> 2020-02-10 18:41:59,558 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//ac_loss_trouble=False
> 2020-02-10 18:41:59,559 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//battery_failure_trouble=False
> 2020-02-10 18:41:59,559 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//supervision_failure_trouble=False
> 2020-02-10 18:41:59,559 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//signal_strength=10
> 2020-02-10 18:41:59,559 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//ac_loss_trouble=False
> 2020-02-10 18:41:59,559 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//battery_failure_trouble=False
> 2020-02-10 18:41:59,559 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//supervision_failure_trouble=False
> 2020-02-10 18:41:59,560 - DEBUG    - BasicMQTTInterface - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/states/keypads//signal_strength=10

**Comment by yozik04** [comment]
Can it be that your keypad name could not be read?

**Comment by yozik04** [comment]
Try latest `dev`

**Comment by cybertza** [comment]
Thanks, it’s not impossible let me check that for you.

**Comment by yozik04** [comment]
I guess it is fixed. Reopen if not.
