### ISSUE TITLE
Not work on MG5050

### ISSUE THREAD

**Issue by danygi79** [ParadoxAlarmInterface/pai#138]
After upgrading from version 1.3.1 to version 2.1.0 it no longer works.
The connection to the panel takes place correctly and also to the mqtt broker, in fact the values ​​of power supply and battery are displayed correctly, but no other data is synchronized correctly, the alarm cannot be activated and no sensor status is displayed

I use IP100.

how do I dowgrade to version 1.3.1 on hassio?

**Comment by yozik04** [comment]
We have a form to fill for a reason. I can not do anything with your report without asking million questions.

> how do I dowgrade to version 1.3.1 on hassio?
Simply stop using Hass.io and use plain docker. Hassio does not support versions.

**Comment by danygi79** [comment]
form? which?

**Comment by jpbarraca** [comment]
When submitting an issue you are presented with a template. Please follow it.
PAI is being continuously tested on those panels, but we need more information.

**Comment by danygi79** [comment]
Sorry but I don't understand what I have to do, I wrote you the model of the control unit used and the problem, if you need more then just ask, but in this way I don't know how to help and what data to provide

**Comment by yozik04** [comment]
Please send full logs at least.
