### ISSUE TITLE
Is is possible to set sensors to be bypassed on arm?

### ISSUE THREAD

**Issue by psyciknz** [ParadoxAlarmInterface/pai#145]
## Alarm system

Spectra SP6000 via ip150

## Environment

Linux X86 Docker

### Git branch

Old master

## Question

Is it possible to bypass sensors.   I'd assume for a workflow it would be set before the panel is armed.

**Comment by yozik04** [comment]
If you arm from paradox keyboard then it is impossible.

**Comment by psyciknz** [comment]
Ahh, keyboard or remote.   So if there was a bypass you cxan only arm via PAI (so in my case via homekit).

How do you tell pai to bypass a sensor?  Is it part of the arm command, or do you set the sensor as bypassed, then arm it?

**Comment by yozik04** [comment]
See mqtt section in wiki. bypassing is there. It is a separate command.

**Comment by psyciknz** [comment]
Ok I see this:
```
paradox/control/zones/name allow setting some zone properties where name identifies the zone. If the name is all, all zones will be updated. The payload can have the values bypass and clear_bypass.
```
But is that something I set before the partition is armed.....or can I set it after arming.  It just says what I can do, not how I can use it.

**Comment by yozik04** [comment]
I do not know about SP/MG. But in EVO you cannot bypass a zone in an armed partition.
