### ISSUE TITLE
Label decoding

### ISSUE THREAD

**Issue by yozik04** [ParadoxAlarmInterface/pai#146]
Paradox uses some custom encoding for all texts. I managed to find a table for that.

![image](https://user-images.githubusercontent.com/2420038/77531259-4da70880-6e9b-11ea-9c45-a80cafb1ccda.png)

In order to properly decode the symbols we need to create a character maps.

In the image above there are two char maps: one for English keyboard, second for Russian keyboard.

**Comment by yozik04** [comment]
Looks like first 122 symbols **almost** match ASCII encoding. The rest are different. I need volunteers who would create a char map to decode these.

**Comment by yozik04** [comment]
Skeleton created in a separate branch.

**Comment by radokristof** [comment]
@yozik04 If you can remember I had problems with characters (mainly special chars). I think this is why I had them, they were decoded incorrectly...

**Comment by yozik04** [comment]
To use encodings:
```python
LABEL_ENCODING="paradox-en"
# or 
LABEL_ENCODING="paradox-ru"
```

**Comment by yozik04** [comment]
Merged into dev. @ShadowofReason Thank you for contribution.

**Comment by radokristof** [comment]
@yozik04 Had time to test this. Solved my label problems as well! Thank you.
