### ISSUE TITLE
Why Insite gold app stop working?

### ISSUE THREAD

**Issue by lordboro** [ParadoxAlarmInterface/pai#147]
Hello,
I've tried to install and configure on home assistant PAI and mosquitto broker, like is shown in the wiki, and its work Great (thank you!), with my mg5050 fw 7.14 and ip150 fw 4.42 in local ip connection mode.
The problem is when i try to connect by swan with insite gold app. The app shown me an error in italian, means like "an error occurred because your sistem is Busy or not respond". If i stop PAI sevice after few minutes, insitegold app return to work. Any suggestion to fix this problem?
Eventually, if i use 306usb serial metod connection can resolve this problem?
Apart that, I'd like to thank the developers for this fantastic works, and escuse for my bad english!

**Comment by yozik04** [comment]
Hi. Current limitation that you can make only one connection to the panel. It can be babyware, PAI or Insite Gold. They can not be used simultaneously unfortunatelly.

**Comment by lordboro** [comment]
thank you. i hope in future something change. is possible create an automation that when sistem is armed pai stop running and cyclically control sistem is already armed for or otherwise return normal run?

**Comment by yozik04** [comment]
Just forget about insite gold and use something different.

**Comment by smithcr68** [comment]
I have deleted my insite gold app after experiencing problems, then reloaded it. When I try to reload my panel number, it says panel number is already registered. How do I get around this to get my app running again.
