### ISSUE TITLE
Sp panel event 40 - special alarm.

### ISSUE THREAD

**Issue by liakoumedos** [ParadoxAlarmInterface/pai#149]
Is it possible to be sent as mqtt messages the panic, panic medical, panic fire and duress alarm??
thanks in advance.

**Comment by jpbarraca** [comment]
You wish PAI to forward messages generated by the panel in the case of panic, panic medical.. etc?
If the panel generates an event or changes a property, they should be sent. They aren't?

**Comment by liakoumedos** [comment]
Yes the alarm generated but not puplished. As i saw your code propably you haven't programm these alarm to be published. These alarms don,t have restoration.

**Comment by yozik04** [comment]
Properties are published on every change.

**Comment by liakoumedos** [comment]
i am searching with mqtt explorer and i can't find something. furthermore to the property.py file there aren't configured these. only to events.py i found these.

**Comment by jpbarraca** [comment]
Maybe it's only an event that is fired.
Log the messages sent to MQTT when the panic is triggered.

**Comment by liakoumedos** [comment]
The event 40 special alarm with the subevents is not publishing.
also the events 58 that represent forced zones is not publishing.
The event 40 will be very usefull.

**Comment by jpbarraca** [comment]
Can you enable full debug with message dump, trigger the event and send the log? Send it to my email or post it here after being encrypted in keybase

**Comment by liakoumedos** [comment]
i am new hassio user. i looking how to give you the logs. any advice will be helpfull

**Comment by yozik04** [comment]
@liakoumedos What panel firmware version you have?
