### ISSUE TITLE
Add users in control panel 

### ISSUE THREAD

**Issue by miromartinov** [ParadoxAlarmInterface/pai#150]
## Alarm system
SP65 , IP100 ; EvoHD and IP150

## Question
Hello, 
I want to know is it possible a user codes to be addes from Home Assistant in the control panel ?

I tested with 2 panels : SP65 and IP100; EVOHD and IP150 - works fine .

**Comment by yozik04** [comment]
Hello, currently it is not possible. But it is doable. Pull requests are welcome.
