### ISSUE TITLE
2 IP modules

### ISSUE THREAD

**Issue by istvanszab** [ParadoxAlarmInterface/pai#151]
Thank your work.
It works perfect for a 5 minutes, then the connection lost and Insite Gold send alarm.
Maybe it  thinks that this is a sabotage.
I use HassIO 0.108.9, SP6000 with IP150 v4.1

Because my SP6000 has only one serial port,  what do you think if I make a parallel cable to the serial port for two IP150 modules? One for IP150 with SWAN connection and one for IP150 with your script connection?

Kind regards
Istvan

**Comment by yozik04** [comment]
Bad idea. They will interfere with each other. Just configure HASS to use local connection and do not use Insite Gold.

**Comment by istvanszab** [comment]
Thank you. I was afraid of that answer :)
It can't connect with local connection:
INFO     - PAI.paradox.connections.ip_connection - Connecting to IP module. Try 1/3
INFO     - PAI.paradox.connections.ip_connection - Authenticating with IP Module
ERROR    - PAI.paradox.connections.ip_connection - Unable to establish session with IP Module. Timeout. Only one connection at a time is allowed.

**Comment by yozik04** [comment]
IP150 v4.1
Update it to at least 4.40.004. See wiki.

**Comment by istvanszab** [comment]
OK. I just would like to use them with each other.
Thank you
