### ISSUE TITLE
Autodiscovery not discovering all attributes

### ISSUE THREAD

**Issue by santibur06** [ParadoxAlarmInterface/pai#153]
## Alarm system
Paradox SP6000

## Environment
hassio (latest) running on VMWare

### Git branch
master

## Question
Hi!

I have setup pai through the hassio add-on, everything works great and connection with IP150 (latest firmware, swan disabled) seems pretty stable.

The only issue I have is with the attributes that are being auto-discovered by home assistant.
For instance, in zones, I can only see the open state, but there are a bunch of other attributes (i see them in mqtt explorer, paradox topic) that I can't access (or don't know how) through home assistant and that I need to trigger some automations. For example, some of my zones are wireless and I'd like to monitor the battery level so I can fire a notification when they are running low.

<img width="280" alt="Screen Shot 2020-05-07 at 2 31 08 PM" src="https://user-images.githubusercontent.com/931452/81415061-491e7280-911e-11ea-907f-6ca263586083.png">

I have searched the web for hours and can't seem to find anyone else who has the same issue, and from what I can recall (it was 4am and had been searching/trying settings non-stop since the day before...) some guys were able to see these attributes so I believe I have something wrong in my settings...

Here's my Addon config:
```
LOGGING_FILE: null
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
LOGGING_DUMP_PACKETS: false
LOGGING_DUMP_MESSAGES: false
LOGGING_DUMP_STATUS: false
LOGGING_DUMP_EVENTS: false
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: XXXXXXX
IP_CONNECTION_PORT: 10010
IP_CONNECTION_PASSWORD: paradox
IP_CONNECTION_SITEID: null
IP_CONNECTION_EMAIL: null
IP_CONNECTION_PANEL_SERIAL: null
IP_CONNECTION_BARE: false
LIMITS:
  partition:
    - 1
  pgm: []
  door: []
  bus-module: []
  repeater: []
  keypad: []
SYNC_TIME: false
PASSWORD: XXXXXXX
MQTT_ENABLE: true
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_USERNAME: XXXXXXX
MQTT_PASSWORD: XXXXXXX
MQTT_RETAIN: true
MQTT_BIND_ADDRESS: 127.0.0.1
MQTT_BIND_PORT: 0
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
POWER_UPDATE_INTERVAL: 60
PUSH_POWER_UPDATE_WITHOUT_CHANGE: true
PUSH_UPDATE_WITHOUT_CHANGE: true
IP_INTERFACE_ENABLE: true
```

Any thoughts?

oh and by the way, KUDOS to the ones who built this integration, you guys are god.

**Comment by yozik04** [comment]
We do not want to let home assistant to autodetect all attributes. There are too many. Use https://www.home-assistant.io/integrations/sensor.mqtt/ to create additional ones you need.
