### ISSUE TITLE
Not getting all motion detection

### ISSUE THREAD

**Issue by terencevs** [ParadoxAlarmInterface/pai#154]
## Alarm system
EVO192 with IP150

## Environment
RPI

### Git branch
Main

## Question
MQTT does not recieve all motion detection on my PIRs. Has PAI been designed like this? I wanted to use my PIRs to trigger lights but it does not always send a open = true message.

I am watching MQTT with MQTT Explorer to confirm this. 

The panel shows the zone as open though, so I know its not my PIR.

**Comment by yozik04** [comment]
For me it sends for all movements. Why you think pir has triggered? What pirs you have?

**Comment by terencevs** [comment]
> For me it sends for all movements. Why you think pir has triggered? What pirs you have?

It shows on the Zone on the control panel as movement detected but no message in MQTT.

I have NV5 PIRs.

**Comment by terencevs** [comment]
So I did some more reading of the documentation and found this:

Panel side
It is recommended to check System Options -> Communication -> “Transmit zone status on serial port”. This way events will be received instantly.

I did this and it is now 100% better. Will test for a day and close. Sometimes it does help to read all the documentation ;)

**Comment by yozik04** [comment]
> Sometimes it does help to read all the documentation ;)

True thing 😄
