### ISSUE TITLE
crypto optimization

### ISSUE THREAD

**Issue by a-lurker** [ParadoxAlarmInterface/pai#155]
Great to see the crypto.py in action!  If I may, can I suggest a modification:

In crypto.py the key is padded and the keygen function is called every time encrypt() or decrypt() is called. The keygen function is cpu time intensive, so I would like to suggest that the padding process and keygen function be moved out of encrypt() or decrypt()  keygen would then only be called twice at start up: once with the user password and once with the panel supplied password. The precalculated saved padded/expanded key would then be passed to encrypt() or decrypt() from then on.

Very minor issue: the array 'shifts' is nested one too many times deep, so in the function shift_row() we see shifts[0][i][d]) % 4] with the fixed [0] index, which is not required.

**Comment by yozik04** [comment]
Welcome @a-lurker. Can you make a pull request to dev branch with changes?
I did perf test with py-spy yesterday and found that most CPU intensive is in `deep_merge ->  merge_into` function in lib/utils.py. It calls `__contains__` method of `ElementTypeContainer`. So it becomes loop in the loop. This is what I am planning to optimise the most.

**Comment by yozik04** [comment]
@a-lurker Actually no need for a pull request. I'll just memoize `keygen` function with a decorator and that will do.

**Comment by yozik04** [comment]
I'd better use `pycrypto`. It is a lot faster. but I can not get it encrypt the same way.
```
from Crypto.Cipher import AES
```

**Comment by yozik04** [comment]
@jpbarraca Can you please let us know what kind of AES encryption crypto.py uses?

**Comment by jpbarraca** [comment]
It's mostly AES but doesn't produce results compatible with the standard.

Our version pads the payload and key with a constant value (0xee) and the key is expanded differently. The resulting cryptograms have some similarities (every 5th byte).
This is the key expanded with our code (key = b'\x00'*32):
```
[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x62, 0x62, 0x62, 0x62, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0xaa, 0xaa, 0xaa, 0xaa, ...]
```

This is the key expanded with a compliant implementation:
```
[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x62, 0x63, 0x63, 0x63, 0x62, 0x63, 0x63, 0x63, 0x62, 0x63, 0x63, 0x63, 0x62, 0x63, 0x63, 0x63, 0xaa, 0xfb, 0xfb, 0xfb, ...]```

**Comment by yozik04** [comment]
Key padding is not done inside AES so it is simple to change, but key expanding can't be changed as it is inside native C library. Just measured, using `from Crypto.Cipher import AES` it is 500x times faster...

**Comment by yozik04** [comment]
`keygen` actually takes only 4% of time.

**Comment by yozik04** [comment]
![image](https://user-images.githubusercontent.com/2420038/82740399-206abf80-9d51-11ea-9bb8-5b09fa94270a.png)

I encrypt and decrypt some different text. 200 times.

**Comment by yozik04** [comment]
I managed to speed it up like 10%. But it is still very slow.

**Comment by yozik04** [comment]
We can fork it and update as we need 🤣 
https://github.com/dlitz/pycrypto/blob/master/src/AES.c

**Comment by jpbarraca** [comment]
The code we have can be somewhat optimized:
Current:
```
 $ python3 -m timeit -s "import crypto" "crypto.encrypt(b'1'*32, b'0'*32)"
500 loops, best of 5: 452 usec per loop
```
New:
```
 $ python3 -m timeit -s "import crypto2" "crypto2.encrypt(b'1'*32, b'0'*32)"
2000 loops, best of 5: 128 usec per loop
```

**Comment by yozik04** [comment]
@jpbarraca crypto2?

**Comment by jpbarraca** [comment]
Alternative implementation taking in consideration how python behaves. Only for encryption now.

**Comment by yozik04** [comment]
Nice.

**Comment by jpbarraca** [comment]
Added an updated version with ~3x performance baseline over the baseline

**Comment by yozik04** [comment]
@jpbarraca it is awesome improvement. No idea how you came up with these formulas. Looking at it right now. It is brilliant.

The only note:
```python
i = 0
while i < 4:
  # ...
  i += 1
```
is 2x times slower in python than
```python
for i in range(4):
  # ...
```

Explanation: https://stackoverflow.com/questions/869229/why-is-looping-over-range-in-python-faster-than-using-a-while-loop

**Comment by yozik04** [comment]
I have fixed some performance bugs in deep_merge and added additional key index so now I can not even capture it with py-spy...
Now we really need to think what we will do with spare cycles...

**Comment by jpbarraca** [comment]
Added more changes. Now we need something faster than a tuple for batch XORs

**Comment by yozik04** [comment]
`decrypt` fails. Produces nonsense. I have updated tests.

**Comment by jpbarraca** [comment]
Weird as I was testing both. Any specific payload or any payload?

**Comment by yozik04** [comment]
`tests/lib/test_crypto.py`
https://github.com/ParadoxAlarmInterface/pai/blob/crypto-optimization/tests/lib/test_crypto.py

```
dec_text = b"Very hard text to be encrypted"
enc_text = b'\xe2\x14S\x8eW`v\xaaa\xc5=\xfe\x90\x94\xf2\x97\xf0\x1f\x19I\xf1\xa7"h\xe5*\xe8\x01\xd4\xdczk'
password = b"test123456"
```

**Comment by yozik04** [comment]
Interesting alternative: http://numba.pydata.org/

**Comment by jpbarraca** [comment]
Fixed. I missed a small detail in the multiplication.

Current status:
```
$ python3 -m timeit -s "from paradox.lib.crypto import encrypt" "x = encrypt(b'\xaa'*16, b'\xbb'*32)"
5000 loops, best of 5: 64.8 usec per loop
$ python3 -m timeit -s "from paradox.lib.crypto import decrypt" "x = decrypt(b'\xaa'*16, b'\xbb'*32)"
2000 loops, best of 5: 130 usec per loop
$ python3 -m timeit -s "from paradox.lib.crypto_old import encrypt" "x = encrypt(b'\xaa'*16, b'\xbb'*32)"
1000 loops, best of 5: 315 usec per loop
$ python3 -m timeit -s "from paradox.lib.crypto_old import decrypt" "x = decrypt(b'\xaa'*16, b'\xbb'*32)"
500 loops, best of 5: 448 usec per loop
```

**Comment by yozik04** [comment]
Too fast to be true 😄 . Merged to dev! Great work. Viva @jpbarraca !
