### ISSUE TITLE
Allow current Time to be pushed to panel as when the PAI starts

### ISSUE THREAD

**Issue by 1nutty1** [ParadoxAlarmInterface/pai#157]
Being able to manually push the system time to the panel

My panel loses around 2 minutes every hour, I would like to be able to push the time to it every couple of hours to keep it relatively in sync with my Pi time.
If it could be implemented like the startup process that would be great, even as an option in the config to send the time to the panel every X hours (0 - 168) where zero is never and 168 is 1 week...

Thanks.
PS PAI works brilliantly on an SP65 panel with an IP150 on the latest firmware.

**Comment by yozik04** [comment]
What if I will make an mqtt topic which would trigger resync. Then you can resync time any time from your home automation software (Openhab, HomeAssistant).

Or timer based approach is preferred?

**Comment by 1nutty1** [comment]
That would be awesome

**Comment by radokristof** [comment]
I would be also happy if there will be a function like this! My also lose a few mins after running for many weeks. Also I would be able to sync when DST happens.

**Comment by yozik04** [comment]
or if drift is > some amount then resync.

**Comment by yozik04** [comment]
Resolved in `dev`. Please verify.

**Comment by yozik04** [comment]
I guess it works as two weeks have passed and no reply.
