### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by thermseekr** [ParadoxAlarmInterface/pai#158]
Hello everyone

Forgive me for not filling the form as requested. I don't yet have a panel connected, my plan is to connect two MG6250 panels in the near future.

I'm an electronic engineer with considerable experience on industrial energy and automation systems and industrial IT infrastructure, and as free time allows I've been slowly walking my way into the IoT world. I lack knowledge/experience to fully understand a design like PAI at the first glance, so here I am asking (probably silly) questions.

First things first, how should I run it? I downloaded the latest build and I see a Dockerfile, is it supposed to run in a docker container? And, is it supposed to be run executing run.sh? Seems obvious but I gotta ask :)

I see mentions to a Raspberry Pi, so I suppose it would run on Raspbian. Does it run well also on Ubuntu? Given it would be inside a container I suppose yes but again gotta ask.

About connecting, can I use the 307USB adapter from Paradox and from there to a serial port on a Pi or other computer, or should I go straight to the serial port on the panel? I'm aware of the need to convert the signal levels, no problems with that.

Going a bit further, has anyone tested with a serial to ethernet converter? I read about using an ESP32, but I'm thinking more of Tibbo DS100 or DS203 industrial converters and then accessing the serial ports through a virtual serial port driver on the host system. Tibbo works very well on that topology, I have sucessfully connected remote legacy systems that way in the past. So the whole path would be:

MG6250 <==> 307USB <==> Tibbo <==> eth network <==> virtual serial port on linux host

This way I suppose I could have two docker containers running two instances of PAI to control both my panels from the same host where I'll have Hassio running.

About Hassio integration, I have not yet gone through the whole Wiki, but since PAI uses MQTT and my main goal is to be able to arm/disarm and receive push notifications about events I think I'll be ok.

Thank you very much for developing and making this project available to others, and also for taking the time to read my post.

Tales Maschio

**Comment by yozik04** [comment]
Hi Tales,

Welcome and thank you for kind words.

> First things first, how should I run it?

You can run it as a service on any linux machine (ARM, x64, x86). For this you will need to install dependencies and configure systemd service to start it on boot. Alternatively you can run it inside a docker container which already has all the dependencies in it and you do not need to configure systemd, docker will rerun containers after a reboot (subject to configuration).

> About connecting

I use cheap USB2TTL from china connected to a RPI. Works tolerable but periodically loses connection (2-3 times a day). Nobody else reported that. Reconnects automatically within seconds so I do not bother. I do not think problem is in USB 2 TTL module.

> MG6250 <==> 307USB <==> Tibbo <==> eth network <==> virtual serial port on linux host

Why not. If you want it this way. For PAI it will be like a local serial port. Tibbo DS100 price is 100$. I'd recommend buying IP150 module instead as PAI works perfectly with it. USB2TTL is ~3$ and does its job =).

> This way I suppose I could have two docker containers running two instances of PAI to control both my panels from the same host where I'll have Hassio running.

You can have as many docker containers as you want. Make sure you have access to Hassio root system. You will need to set permissions for the serial devices. If you install PAI as Hassio Addon you will only be able to install one addon. Home assistant communicates with PAI via MQTT. The is no direct link between them. Addon is just an easiest way to install for most users.

**Comment by thermseekr** [comment]
Hi Jevgeni,

Thank you for your reply. Things are more clear now. About the IP150 module, my panels are not compatible. I thought about 307USB + Tibbo to avoid having software running outside my server. But it's indeed more intelligent to start the approach from the lower end of the cost scale. Will order a couple RPis and a bunch of USB2TTLs and see how it goes.

Regards from Brazil.

**Comment by yozik04** [comment]
One concern. Does Babyware support MG6250? PAI communicates with the panel using babyware protocol. It is weird that IP150 is not supported. Now I am not sure if MG6250 will work with PAI.

**Comment by thermseekr** [comment]
Yes Babyware supports this panel. I unfortunately won’t be able to test in the next few days or even weeks, but as soon as I can stop in front of the panel I’ll try and post results here.
