### ISSUE TITLE
PGM Control

### ISSUE THREAD

**Issue by thcasssio** [ParadoxAlarmInterface/pai#159]
## Alarm system
SP6000, IP150 V2.X firmware

## Environment
HASS.io

## Question
Hi, newbie here, I'm trying to setup hass.io with PAI, but I have a few questions.

When I setup it first, it didn't show my PGMs, only the sensors. Is that by design? If so, how do I add a button on hass.io to control my PGMs? Should I use service? If so, what is the code I must put in service?

Another question is how may I get a notification in case of an alarm, for example?

Thanks

Cassio

**Comment by warrendt** [comment]
Hi everyone, 

On this topic as well, the IP150 module itself has a PGM as well. 
I have wired my gate trigger to this and use it to open and close my street gate. 
Would there we a potential of integrating this or would i have to re-wire back to the PGM output on the panel

**Comment by yozik04** [comment]
Hi. It will be easier and faster to rewire it to the panel. IP150 PGM controlling is not implemented.

**Comment by yozik04** [comment]
> When I setup it first, it didn't show my PGMs, only the sensors. Is that by design? If so, how do I add a button on hass.io to control my PGMs? Should I use service? If so, what is the code I must put in service?

Probably PAI does not autodetect PGMs for MG/SP and does not publish these switches to home assistant automatically. How to add a button that sends MQTT messages you need to look into home assistant documentation. In PAI wiki you can find info to what topics and with what payload you need to publish.

> Another question is how may I get a notification in case of an alarm, for example?


I use pushover. You can try it as well. There is info in the wiki.

**Comment by warrendt** [comment]
I have re-wired the PGM, but I am still not seeing the control topic being published. 
Here is my config yaml for the PAI container 

LOGGING_FILE: null
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
LOGGING_DUMP_PACKETS: false
LOGGING_DUMP_MESSAGES: false
LOGGING_DUMP_STATUS: false
LOGGING_DUMP_EVENTS: false
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: 127.0.0.1
IP_CONNECTION_PORT: 10000
IP_CONNECTION_PASSWORD: paradox
IP_CONNECTION_SITEID: Maree
IP_CONNECTION_EMAIL: warrendt@gmail.com
IP_CONNECTION_PANEL_SERIAL: null
IP_CONNECTION_BARE: false
LIMITS: {}
SYNC_TIME: true
PASSWORD: '0000'
MQTT_ENABLE: true
MQTT_HOST: 192.168.1.148
MQTT_PORT: 1883
MQTT_USERNAME: None
MQTT_PASSWORD: None
MQTT_RETAIN: true
MQTT_BIND_ADDRESS: 192.168.1.148
MQTT_BIND_PORT: 0
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
MQTT_BASE_TOPIC: paradox
MQTT_ZONE_TOPIC: zones
MQTT_PARTITION_TOPIC: partitions
MQTT_BUS_TOPIC: buses
MQTT_SYSTEM_TOPIC: system
MQTT_REPEATER_TOPIC: repeaters
MQTT_USER_TOPIC: users
MQTT_EVENTS_TOPIC: events
MQTT_CONTROL_TOPIC: control
MQTT_DEFINITIONS_TOPIC: control
MQTT_HOMEASSISTANT_DISCOVERY_PREFIX: homeassistant
MQTT_OUTPUT_TOPIC: outputs
MQTT_KEYPAD_TOPIC: keypads
MQTT_STATES_TOPIC: states
MQTT_RAW_TOPIC: raw
MQTT_NOTIFICATIONS_TOPIC: notifications
MQTT_PUBLISH_RAW_EVENTS: true
MQTT_INTERFACE_TOPIC: interface
MQTT_TOGGLE_CODES: {}
MQTT_DASH_PUBLISH: true
MQTT_DASH_TOPIC: metrics/exchange/pai
POWER_UPDATE_INTERVAL: 60
PUSH_POWER_UPDATE_WITHOUT_CHANGE: true
PUSH_UPDATE_WITHOUT_CHANGE: false

![image](https://user-images.githubusercontent.com/193215/87936387-07e9fd80-ca93-11ea-8197-ff3377cbf21d.png)

**Comment by warrendt** [comment]
I have re-wired the PGM, but I am still not seeing the control topic being published.
Here is my config yaml for the PAI container

LOGGING_FILE: null
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
LOGGING_DUMP_PACKETS: false
LOGGING_DUMP_MESSAGES: false
LOGGING_DUMP_STATUS: false
LOGGING_DUMP_EVENTS: false
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: 127.0.0.1
IP_CONNECTION_PORT: 10000
LIMITS: {}
SYNC_TIME: true
PASSWORD: '0000'
MQTT_ENABLE: true
MQTT_HOST: 192.168.1.148
MQTT_PORT: 1883
MQTT_USERNAME: None
MQTT_PASSWORD: None
MQTT_RETAIN: true
MQTT_BIND_ADDRESS: 192.168.1.148
MQTT_BIND_PORT: 0
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
MQTT_BASE_TOPIC: paradox
MQTT_ZONE_TOPIC: zones
MQTT_PARTITION_TOPIC: partitions
MQTT_BUS_TOPIC: buses
MQTT_SYSTEM_TOPIC: system
MQTT_REPEATER_TOPIC: repeaters
MQTT_USER_TOPIC: users
MQTT_EVENTS_TOPIC: events
MQTT_CONTROL_TOPIC: control
MQTT_DEFINITIONS_TOPIC: control
MQTT_HOMEASSISTANT_DISCOVERY_PREFIX: homeassistant
MQTT_OUTPUT_TOPIC: outputs
MQTT_KEYPAD_TOPIC: keypads
MQTT_STATES_TOPIC: states
MQTT_RAW_TOPIC: raw
MQTT_NOTIFICATIONS_TOPIC: notifications
MQTT_PUBLISH_RAW_EVENTS: true
MQTT_INTERFACE_TOPIC: interface
MQTT_TOGGLE_CODES: {}
MQTT_DASH_PUBLISH: true
MQTT_DASH_TOPIC: metrics/exchange/pai
POWER_UPDATE_INTERVAL: 60
PUSH_POWER_UPDATE_WITHOUT_CHANGE: true
PUSH_UPDATE_WITHOUT_CHANGE: false

![image](https://user-images.githubusercontent.com/193215/87936498-32d45180-ca93-11ea-89b4-19eeaf9e84be.png)

**Comment by yozik04** [comment]
For SP/MG PGM autodetection is not implemented.

Control topic should be published by home assistant, not PAI.

You can configure PGMs manually in your home assistant. See wiki https://github.com/ParadoxAlarmInterface/pai/wiki/MQTT-Interface#control for topics.

**Comment by yozik04** [comment]
@jpbarraca Do you want to implement a PGM autodetection for homeassistant?

**Comment by Rusti-gotrage** [comment]
I would LOVE a PGM autodetection for Home-Assistant!
I've only just gotten my HASS  config running and am just learning everything from YAML, to Node-Red to MQTT...

I love the PAI HASS add-on - it worked great pretty much out of the box for the alarm areas, and zone detectors...
Now I want to be able to use HASS to trigger the relay (PGM5) that triggers the Garage Roller Door...

Being a total n00b with HA, etc... etc...  I've got little to no clue how to do this, so any and all assistance greatly appreciated!

For Reference: I'm running a Paradox EVO192 version 4.63 build 2, with an IP150 IP Module version 20, firmware: 5.2
Talking to HASS 0.114.2 on a R-Pi3B using the built in HASS MQTT Broker 5.1 addon.

**Comment by warrendt** [comment]
I eventually hacked together a MQTT button which works, but it sucks for state and feeding back an open/close state because I don't know enough to get that far

**Comment by Rusti-gotrage** [comment]
Would love to see your code...
I tried using Node-Red to publish MQTT data to the panel....

got this:

2020-08-19 00:50:20,798 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT Broker Connected
2020-08-19 00:59:22,865 - INFO     - PAI.paradox.interfaces.mqtt.basic - message topic=paradox/control/outputs/5, payload=on
2020-08-19 00:59:22,903 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29
2020-08-19 00:59:31,101 - INFO     - PAI.paradox.hardware.evo.panel - PGM command: "on" failed
2020-08-19 00:59:31,102 - WARNING  - PAI.paradox.interfaces.mqtt.basic - Output command refused: 5=on

Back to the drawing board I guess...

**Comment by yozik04** [comment]
@Rusti-gotrage PGM Auto discovery is implemented in 2.2.0 which is now released. You probably need to upgrade your EVO fw as well.
@warrendt Try 2.2.0 if you have EVO.

**Comment by warrendt** [comment]
I have an MG5050, I'll install as soon as its available as an update on Hassio.

**Comment by Rusti-gotrage** [comment]
@yozik04  - Sooo excited with the new version!! It DOES pick-up the PGM's automatically now which is great....  🥇  😀 

BUT....  😭 

2020-08-19 16:59:39,427 - INFO     - PAI.paradox.interfaces.mqtt.basic - message topic=paradox/control/outputs/pgm_5, payload=on
2020-08-19 16:59:39,459 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29
2020-08-19 16:59:40,471 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29
2020-08-19 16:59:41,456 - INFO     - PAI.paradox.interfaces.mqtt.basic - message topic=paradox/control/outputs/pgm_5, payload=off
2020-08-19 16:59:41,471 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29
2020-08-19 16:59:42,483 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29

I suspect this may have something to do with the Alarm Panel Firmware.

Unfortunately - I'm unable to source NEW Firmware and Paradox are EXCEPTIONALLY UN-HELPFUL!! 😠 
They said - talk to your distributor.

The distributor the parts came from, because I'm not an installer and (more importantly I suspect) I don't have an account with them, won't deal with me.  😡   So despite the fact that I installed the damn thing and programmed it myself, and I USED to BE an alarm technician, because I didn't by the parts DIRECTLY from them, they won't deal with me!  😢 

If someone has the latest firmware for an EVO192 that they can sling me in a dropbox or similar - I'd greatly appreciate it! 

On a separate note - I'm somewhat comforted that it's the same error I was getting myself and the MQTT publish command is the same as the one I was using... it gives me hope that I'm not a complete n00b!!  😃

**Comment by yozik04** [comment]
@Rusti-gotrage Come to gitter to discuss your options.

**Comment by chinezbrun** [comment]
Hi guys, any solution on this? I need to control PGM's from Home Assistant and really i do not understand how. I have MG5050.

**Comment by warrendt** [comment]
> Hi guys, any solution on this? I need to control PGM's from Home Assistant and really i do not understand how. I have MG5050.

Version 2.2.1 picks it automatically and adds it to home assistant via MQTT.

**Comment by Rusti-gotrage** [comment]
> Hi guys, any solution on this? I need to control PGM's from Home Assistant and really i do not understand how. I have MG5050.

just make sure your running as close to the latest firmware on your panel that you can... and your IP150

**Comment by yozik04** [comment]
@chinezbrun For MG5050 I think there is no PGM autodetection yet. Even in 2.2.1. Ask @jpbarraca =)

**Comment by chinezbrun** [comment]
thanks. I did it manually based on MQTT wiki. Pity that PGM auto detection is not yet implemented.

**Comment by jpbarraca** [comment]
It will be very soon, just not today :D

**Comment by jpbarraca** [comment]
Is this fixed?

**Comment by chinezbrun** [comment]
PGM autodetection works on MG5050

**Comment by lucdiniz** [comment]
> 
> 
> Is this fixed?

I confirm it auto-detects on MG5050. Thanks @jpbarraca
