### ISSUE TITLE
SWAN Connection: PAI sometimes connects to other user's panel

### ISSUE THREAD

**Issue by yusufptl** [ParadoxAlarmInterface/pai#164]
MG5050 
Describe your panel model  Magellan MG5050), access mode ( IP150 using SWAN .).

## Environment
Home assistant

## Git branch
HACS

## Describe the bug
I am able to connect and arm disarm. It shows either a MG5050 or EVO192 under devices. If i click further it has created a large number of entities which are not part of my system. 

## Logs
In the logs you will see 5 zones. as per the screen shot you can see a number of entities, the list is much longer than this. maybe around 30 entities. 

![image](https://user-images.githubusercontent.com/65311719/87849942-bf90db00-c8ec-11ea-9002-162e615fdd6b.png)

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.1.13
Comment: https://keybase.io/crypto

wcFMA4hORRWTO2jFARAAgxIB7g9h8cuVvxFFSWbijPW4dDVhWfV4JCrWmuybSUsh
eZBDtn5/OIZf57Iy9OQOSYGEEChyw6Yxj8yLFSsZx4EymSSnu0DvLQkZSpo4Hu4z
rMxE49gMTM35bsnaSYGFV40aH01sSRqH8AYicopKKVXA2HESqyAZLZwiVEE4E3si
BLvbQQWC7N/j2Y16OXNyNqCtsbDQXEwTlQSossS6kDlgIBU+TE7pBsYDELDF4h5d
Mvl1Cu0R9Ljm2MYo2mJ8JHLBDBXJ2Bv6MoMoQAIRWHmlRiqrZwr/17gPgOsI1gCi
P9rJeeSOSHk22LOydEEj+zUcpkSksw/oyMdoMRNOz/Wos9VWoueCMacOZnw4f59b
vI7NnOZM+MuU+HzqifBNvPjB8cko9oVHDMkb/qz3A98HyW1C0BAYr3Ah8o0dtRFe
f3QgSUO8ieS0LAnieMEDX3E4KVNhY4bmzrDLn646NMm/oB/jBrD2nG4utXavOedb
r/mLbXtxzsq4WsNBAtz7vcbBlwyUWLQJ7NRc/fkABuIf9Muzi45P46bkVAQ12hzX
F3CW6guAI5JmR8wtdRb2AqzarjW7QCXyiQWpRkiDoMTinGekJ+/fs1aVikE3QZ1u
xOi49T1lfXouIGFCafu0lGoTeETZ6bInx25zfUI0UYkDKxwlmh8S+quldG7BTwXS
w7sB28lcJpdXaC5cf1avAz31AiFdK86hmMs8LBXF4crTsUxfFtM9qfkA5t+zQg+P
0crIC6JO2c6HuY2O0s/nND7qP57JpKcv/QlNkg46MpAfBRBxypgj1hE5PlgNITlK
8v6XOzsoCj4WRJtYbceD15xk8rsC1BORoUWxtjuRTNTwwutu4OxjsXgLROlHO6lL
j5XqaOhXaHRml419XZGgBl9oyYNnEfT/WT7MxjspCSrul+LjH7HJ+ZAj0fWlj0TU
MiFm2WSpBiuQNMbMgOLbJbAo3TUzzj5KOEaZOpVMIjNhw0wbA+XgNmccoT7R0QUG
7HcTKKjSV5GlYugOUnvzD1rC7ziFb0axfYEaHBVlMdwor8um7VUDsIxqoEsx1LHa
1S56z8TRToQNz/8K1qxCAjjRI7pHbcCtqxN5F7QFLR0SAeRSGimOl0SBu9Faf9Sp
N0RGZmL4gcytEYj7egKNYJ5gOjIriKuAyr7b+jifQ2iQmWmLdVrk1BG9flL1Uu2l
BzUxpwDa9jaGJMgPhUH7UuEAfrv7HcvVMOom/m4xNuFvUXLggGUDbWG1X0lDrZ8q
W6pVs2gAWHJ2cu9c6jC8XcMMb5SlrsxnDEta8YozIT6YuDPf2UYrmbL7JSPiMh3+
KzdABok9D+gwkR+Ob3PlatA1OavDEMNrCgri/ZA18vBeeUcHWTE/TQ+5B6+rqbaU
yDtkx8yo9N9yXnDMSoADN/GZbgY2Fv4EzUgDAFBfyu9YodgzgimvKmO+91FrBGUP
fLNMv//vKy5FQgu8LQnkn80kyu1e8zN9kFv2R3JZ0ZJk588NE+orr17o5MAQPH+h
e6vHndGH7bRZ6NGzfuxZTp7h6aDXhoMOTeRgzW0W1HYASnrnjRaIrXC78BMsnq2v
Wm9zt3i8zNUyTkl805haAy9Y92VTWmI2CkPv8IFKTqYYXewhNpFsAQzYKBffXOeD
CdqYUqpveyxZijQZtVZfbVy8qJfR5RbPQM95cbISZO/0ZpqsODBMFoKkIjPXQ379
bc4Ev4iAFrNP+hf1rWQSsJanbQ9gIYIDuWFzFV7+kpp5DWsQIYinsWNNIUNaaqRV
Okrc2XSBRNEufzEjVN5gHb/nVoMQ+4Dd5or4QliP+tyUIT5ppgaPHspyzvzodARu
NvBA0ZhMKQ9c/CLEwfpAIHNXPiyUbbougMhqUSNO0H0Gu50bN/6LDz584NHV7r65
igide9P8cGlDXIq06yB/OfIGHgS+7KhPNO+HeqsXjWPT8p85BMKYpL3z+bclS9v3
HKQSIaOPQ3H/FGT5YzJzJCdslj0Ipxf1trUfYXwGO3YpiahcXnD4cOh9gCetDFsG
lC4K8E+q0yWOXPdU8BMrJdG/dKp4odwrc6WueMCsBP2Z0Hzh8XT5qR4V8lO9xsd3
KEY0/0iGRdJmFD3YRhA7f4WXmjnJdKujJ/J9n1fnOqEu3WBJt73GGR18ge3Rh9w6
/PnvN5jGd4EuNHOXMJiycA58QpUJpQafWcoC+B2PwNym5l79n1OCxcIg8AS/
=ctoc
-----END PGP MESSAGE-----

**Comment by yozik04** [comment]
I've seen this before. Actually we can not do anything about that. Consider other connection methods.

**Comment by yusufptl** [comment]
Sure I will, which other method can I use with the ip150 it's on fw 5.0

**Comment by yozik04** [comment]
Check wiki. Local IP connection should work with fw 5.x
