### ISSUE TITLE
Door Control and status For PARADOX EVO and others PAI and Hassio

### ISSUE THREAD

**Issue by FigJam23** [ParadoxAlarmInterface/pai#165]

**Comment by yozik04** [comment]
Door action message was implemented back in d521a36e8e74bf6f59655d613de615c61535b1fa
TODO:
- MQTT endpoint

**Comment by yozik04** [comment]
MQTT topic `paradox/control/doors/Door 1` or `paradox/control/doors/1`
payload `lock` or `unlock`.
That will fail for sure. I need full debug output what was received after this command.

**Comment by ShadowofReason** [comment]
@yozik04 Still need output?

**Comment by yozik04** [comment]
😄 some years has passed. I am not sure I want to return to this.

**Comment by FigJam23** [comment]
I gave up trying to get this to work using below MQTT, such a shame as being able to control doors would be extremely useful and a A+++ feature for PAI. my next option is to upgrade my entire system to a inception controller and ditch Paradox, but I would prefer to stay with Paradox as I like the system and why replace it if not required. I wish I knew how to pull logs from babyware to get this working :{ 

'''MQTT topic paradox/control/doors/Door 1 or paradox/control/doors/1
payload lock or unlock.'''

**Comment by yozik04** [comment]
The feature was almost ready. It required testing and bug fixing. But then you have disappeared. I do not have door control modules myself. So I had to develop the feature blindly. 
Your comment does not help to resolve the problem.
Show debug logs, describe your environment. Provide as much info as you can. This will move things forward.

**Comment by yozik04** [comment]
Or wait when someone will come and invest his time into it.
So far we had just 2 persons that had any interest in this feature request.

**Comment by FigJam23** [comment]
Probably be waiting along time lol I'm just going to use a pgm to trigger rex on door for now not a perfect solution as only will work as a timed unlock

**Comment by FigJam23** [comment]
Hey mate sorry to bring up an old thread, I've had another go at this now I understand a bit more about how things work lol still
a work in progress anyhow I think I've made some progress so using the below MQTT command.
 `
 - name: "Door 1"
    state_topic: "paradox/control/doors/1"
    command_topic: "paradox/control/doors/1"
    payload_on: "lock"
    payload_off: "unlock"   `

I get this in my PAI error log, would you have any idea on what i could now try.

`2022-12-10 15:10:50,951 - INFO     - PAI.paradox.hardware.evo.panel - Door command: "unlock" succeeded
2022-12-10 15:10:52,535 - INFO     - PAI.paradox.interfaces.mqtt.basic - message topic=paradox/control/doors/1, payload=lock
2022-12-10 15:10:52,549 - INFO     - PAI.paradox.hardware.evo.panel - Door command: "lock" succeeded
2022-12-10 15:10:52,661 - WARNING  - PAI.paradox.paradox - Missing element with ID 129 in door/`

**Comment by FigJam23** [comment]
do I need to include a user ID?

raw = PerformDoorAction.build({"fields":{"value":{"doors":[1], "user_id": 3, "command": "unlock"}}})

**Comment by FigJam23** [comment]
Ok, good News Door Unlocks and locks using the above MQTT command omg Yay.  the only issue I have now is I can not control the door when it is unlocked on a scheduled event. Is there any command like unlock override or lock override, i could use that would force the door to lock. wow progress is exciting

**Comment by FigJam23** [comment]
Ok This Is my final change That is working best removed all time controls from babyware  and use hassio as primary control.
`lock:
    - name: Frontdoor
      state_topic: "paradox/control/doors/1/user_id/1"
      command_topic: "paradox/control/doors/1/user_id/1"
      payload_lock: "lock"
      payload_unlock: "unlock"
      state_locked: "lock"
      state_unlocked: "unlock"
      optimistic: false
      qos: 1
      retain: true
   #   value_template: "{{ value.x }}"`

Log out put still error but Door Control working further testing to come
`2022-12-10 16:25:04,668 - INFO     - PAI.paradox.hardware.evo.panel - Door command: "unlock" succeeded
2022-12-10 16:25:07,963 - INFO     - PAI.paradox.interfaces.mqtt.basic - message topic=paradox/control/doors/1/user_id/1, payload=lock
2022-12-10 16:25:07,976 - INFO     - PAI.paradox.hardware.evo.panel - Door command: "lock" succeeded
2022-12-10 16:25:08,074 - WARNING  - PAI.paradox.paradox - Missing element with ID 129 in door/`
