### ISSUE TITLE
Cannot connect to IP150 module

### ISSUE THREAD

**Issue by samuellazea** [ParadoxAlarmInterface/pai#166]
## Alarm system

Panel
Type | EVOHD
-- | --
Firmware version | 6.86
Serial number | 07 00 35 DA

Ip Module
Firmware version | 1.39.02
-- | --
Hardware | 020
ECO | N009
Serial boot | N/A
IP boot | 2.12

## Environment

Linux/Docker

## Question

I cannot connect to ip-150 module no matter what I do. Tried all passwords I could but still no luck. I can connect with babyware and iParadox to check that it works and it does work but not when I try to connect with PAI.

**Comment by yozik04** [comment]
Errors? Logs? PAI version? Did you read a note about '0's in the password? Two lines of text thrown into an issue is certainly not enough.
