### ISSUE TITLE
Using Limit's properly...

### ISSUE THREAD

**Issue by Rusti-gotrage** [ParadoxAlarmInterface/pai#168]
## Alarm system
EVO192
IP150
PCS260 GSM
RTX3 Wireless

## Environment
Running under HASS.IO Raspberry Pi 0.114

## Question
Trying to set limits to restrict only the users I want, as well as pull the PGM's I want to use...
Problem is, every time I put the limit's code in (copied from the wiki) the Config engine won't accept it in the syntax the Wiki provides it, and when I alter it so the Config engine WILL, it then CHANGES it further when I SAVE.

I try inserting the code: 

LIMITS = {
    'user': range(1, 7), 
    'door': [],               
    'pgm': range(1, 6),
    'key-switch': []
}

And it won't accept it as it stand.
I have to change it to:

LIMITS: {
 user: '(1, 2, 3, 4, 5, 6)',
 door: [],
 pgm: '(1, 2, 3, 4, 5, 6)',
 key-switch: []
}

End config after 'saving':

LOGGING_FILE: null
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
LOGGING_DUMP_PACKETS: false
LOGGING_DUMP_MESSAGES: false
LOGGING_DUMP_STATUS: false
LOGGING_DUMP_EVENTS: false
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: <REDACTED>
IP_CONNECTION_PORT: <REDACTED>
IP_CONNECTION_PASSWORD: <REDACTED>
IP_CONNECTION_SITEID: null
IP_CONNECTION_EMAIL: null
IP_CONNECTION_PANEL_SERIAL: null
IP_CONNECTION_BARE: false
LIMITS:
  user: '(1, 2, 3, 4, 5, 6)'
  door: []
  pgm: '(1, 2, 3, 4, 5, 6)'
  key-switch: []
SYNC_TIME: false
PASSWORD: '<REDACTED>'
MQTT_ENABLE: true
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_USERNAME: <REDACTED>
MQTT_PASSWORD: <REDACTED>
MQTT_RETAIN: true
MQTT_BIND_ADDRESS: 127.0.0.1
MQTT_BIND_PORT: 0
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
POWER_UPDATE_INTERVAL: 60
PUSH_POWER_UPDATE_WITHOUT_CHANGE: true
PUSH_UPDATE_WITHOUT_CHANGE: false

Then when I try and save and restart the module, the log throws up errors...

2020-08-15 14:19:24,205 - ERROR    - PAI - Restarting
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paradox/main.py", line 80, in run_loop
    if await alarm.connect():
  File "/usr/local/lib/python3.7/site-packages/paradox/paradox.py", line 168, in connect
    labels = await self.panel.load_labels()
  File "/usr/local/lib/python3.7/site-packages/paradox/hardware/panel.py", line 169, in load_labels
    await self._load_labels(data[elem_type], addresses, label_offset=elem_def['label_offset'])
  File "/usr/local/lib/python3.7/site-packages/paradox/hardware/panel.py", line 238, in _load_labels
    async for index, data in self._eeprom_batch_reader(addresses, field_length):
  File "/usr/local/lib/python3.7/site-packages/paradox/hardware/panel.py", line 196, in _eeprom_batch_reader
    ia = IndexAddress(*next(addresses))
  File "/usr/local/lib/python3.7/site-packages/paradox/hardware/panel.py", line 167, in <genexpr>
    addresses = iter((i, a) for i, a in addresses if i in limits)
TypeError: 'in <string>' requires string as left operand, not int

I'm obviously doing something wrong... any pointers?

**Comment by yozik04** [comment]
We initially made this project to be standalone and all configuration was done in a config file written in Python. This is when all the documentation was written. Then we wrapped it into hass.io addon. Addons want config files in JSON. In Hass.io Web UI you configure the addon in YAML. So you now need to use YAML syntax for arrays. Use your favourite search engine and search for "yaml array". You will find the answer.
Maybe one day we will rewrite configuration to use yaml.

**Comment by Rusti-gotrage** [comment]
Huh - ok.... so - YAML learning curve for me...!

For anyone else who comes across this and wants the answer on the correct format for Limits in HASSIO's YAML config...

To only pick up the users 1, 2, 4 and 5, and only pgm's 1 and 5, 
but NOT pickup any doors, bus-modules or key-switches:

----------8<------snip------8<----------

LIMITS:
  door: []
  key-switch: []
  bus-module: []
  user:
    - 1
    - 2
    - 4
    - 5
  pgm:
    - 1
    - 5

----------8<------snip------8<----------
