### ISSUE TITLE
Not all HomeAssistant MQTT sensor names follow the same pattern

### ISSUE THREAD

**Issue by clau-bucur** [ParadoxAlarmInterface/pai#172]
The MQTT sensors and trouble binary sensors do not follow the same naming pattern as the binary sensors for zones and partitions (which IMHO follow the more logical naming).

## Feature description
The **partition_\*\_\*** and **zone_\*\_\*** binary senor names are following the MQTT topics they are defined in, and are more easier to manage.
However, the **troubles_\*\_\*** binary sensors follow a nice topic pattern, but their names are not following the same logic.
For example: **homeassistant/binary_sensor/xxxxxxx/troubles_system_trouble** is named "**Panel system_trouble**". When it should have been named "**Troubles System Trouble**"

The same happens for most of the sensors. Here they have rather generic names, which does not make it clear that they belong to the paradox alarm system.
For example **homeassistant/sensor/0502f2e4/run_status** generates a rather confusing sensor named "**sensor.run_status**".
This would be better to be renamed **homeassistant/sensor/0502f2e4/panel_run_status** + **sensor.panel_run_status**.

**Comment by jpbarraca** [comment]
thanks for the comment.
I used "Panel XXX" because in my scenario the Troubles prefix was already in use for another scope (Higher level issues).
Zones and Partitions are more specific to an alarm and I kept them like that, but the word _troubles_ is more generic (is it?).

Does ```pai_run_status``` _PAI Run Status"_ (as this is a PAI variable and not from the panel) makes sense?
Also, what prefixes can we use for the panel it self? ```paradox_*```, ```alarm_*```, ```evo192_*```, other?

**Comment by clau-bucur** [comment]
> I used "Panel XXX" because in my scenario the Troubles prefix was already in use for another scope (Higher level issues).
> Zones and Partitions are more specific to an alarm and I kept them like that, but the word _troubles_ is more generic (is it?).

Indeed _troubles_ is pretty generic.
**Panel Troubles** or **PAI troubles** all work I think.

> Does `pai_run_status` _PAI Run Status"_ (as this is a PAI variable and not from the panel) makes sense?

Yes, it makes sense, and it's a good indicator of what is it for.


> Also, what prefixes can we use for the panel it self? `paradox_*`, `alarm_*`, `evo192_*`, other?

I'd say that both **paradox\_\*** or **pai\_\*** make sense.
It would be nice that all domains (sensor, binary sensor, switch) follow the same pattern though.

**Comment by jpbarraca** [comment]
Can we close this?

**Comment by clau-bucur** [comment]
Yes, fied by #175 !
