### ISSUE TITLE
MQTT Reporting Speed - Can it be faster?

### ISSUE THREAD

**Issue by Rusti-gotrage** [ParadoxAlarmInterface/pai#173]
## Alarm system
EVO192 
IP150

## Environment
HASS 0.114.4
Using MQTT Broker 5.1
PAI 2.2.1

## Hardware
Raspberry Pi-3B

### Git branch
Latest Stable

## Question
I'm trying to use the door reed switch to trigger the light being turned on in the garage and I'm counting sometimes as high as 9 seconds before MQTT is seeing the report from the panel about the door being opened.
When I open the door, I hear the chime from my T50 saying the door is open, but it's taking MUCH longer for the status to reflect in MQTT (and thus in Node-RED and HA).

Is there any way we can increase the reporting speed from the Panel to MQTT??

**Comment by yozik04** [comment]
Tried this?
https://github.com/ParadoxAlarmInterface/pai/wiki/Configuration#panel-side

**Comment by Rusti-gotrage** [comment]
YEESSSS!!!!
That's the ticket!! 
Thanks muchly :)
