### ISSUE TITLE
Wrong PASSWORD error after connection to IP150 was briefly interrupted

### ISSUE THREAD

**Issue by NeilDuToit92** [ParadoxAlarmInterface/pai#174]
## Alarm system
EVO192 - IP150

## Environment
Home assistant add-on (Development and production)

## Git branch
Development and production HA add-ons

## Describe the bug
There seems to be a timeout in my connection which is possible due to a wireless network bridge between my Home Assistant server and my Paradox.
When that connection drops, PAI attempts to reconnect to the alarm panel, but fails with error 'Wrong PASSWORD'.
I can then just restart the add-on and it will connect successfully again. The biggest issue is that the container dies when I get this error.

## To Reproduce
1. Start PAI container
2. Let is connect to the panel
3. Interrupt the physical connection to the IP150
4. PAI disconnects and attempts to reconnect
5. Wrong password error

## Logs
Log attached

**Comment by yozik04** [comment]
Hey. Can not find attached logs.

**Comment by NeilDuToit92** [comment]
[PAI log encrypted.txt](https://github.com/ParadoxAlarmInterface/pai/files/5169442/PAI.log.encrypted.txt)
I did upload it on the issue, not sure what happened there, but here you go

**Comment by NeilDuToit92** [comment]
I have found a workaround. I tell Home Assistant to restart the PAI add-on if the alarm has been unavailable for more than 60 seconds. It only treats the symptoms of the error I am having and not the error itself, it's not ideal, but for now it works.

**Comment by yozik04** [comment]
Did you do this way? I can not decrypt.
1. Go to https://keybase.io/encrypt
2. Write to us
   1. Write 'jpbarraca' as the recipient if you have SP/MG panel
   2. Write 'yozik04' as the recipient if you have EVO panel
3. Write your log or add a link to the log file (if using services such as dropbox).
4. Click Encrypt
5. Save the result to a text file and add it as an attachment.

**Comment by NeilDuToit92** [comment]
Yes I did, here is the same log that I encrypted again
[PAI log encrypted 2.txt](https://github.com/ParadoxAlarmInterface/pai/files/5169576/PAI.log.encrypted.2.txt)

**Comment by yozik04** [comment]
Ahh sorry it was PGP crypted... I used keybase one...

**Comment by yozik04** [comment]
Can you please provide longer log with disconnection part from successful connection.
Successful connection block would also be useful.
I need to see the differences between packets.

**Comment by NeilDuToit92** [comment]
Will do, I'll set up file logging and send one when it occurs again

**Comment by NeilDuToit92** [comment]
I am setting the following configuration values to try to write to a persistent storage that won't disappear when the container shuts down, but the log is not writing to the data directory. Any ideas?

LOGGING_FILE: /data/paradox.log
LOGGING_LEVEL_CONSOLE: 10
LOGGING_LEVEL_FILE: 10
LOGGING_DUMP_PACKETS: true
LOGGING_DUMP_MESSAGES: true
LOGGING_DUMP_STATUS: true
LOGGING_DUMP_EVENTS: true

**Comment by yozik04** [comment]
Ahh. You actually can not.

**Comment by NeilDuToit92** [comment]
Alright, I'll run it manually then  in the next few days to get the logs.
