### ISSUE TITLE
Improve keyswitch reaction

### ISSUE THREAD

**Issue by clau-bucur** [ParadoxAlarmInterface/pai#176]
The keyswitch triggering is detected by PAI with a delay of a few seconds.
Testing the keyswitch in Babyware is detected instantly.

I'd be great if PAI would have the same reaction time.
I attached a log file where I enabled and then disabled keyswitch 1.
[logs.txt](https://github.com/ParadoxAlarmInterface/pai/files/5256176/logs.txt)

**Comment by yozik04** [comment]
@clau-bucur Can you please redo the log with:
`LOGGING_DUMP_MESSAGES = True` setting.

**Comment by clau-bucur** [comment]
Here it is.
[log_with_dump.txt](https://github.com/ParadoxAlarmInterface/pai/files/5259535/log_with_dump.txt)

**Comment by yozik04** [comment]
Unfortunately I do not see any live event broadcasted =(
Data comes only with periodic status requests...

**Comment by clau-bucur** [comment]
That's sad. There must be some way though, because Babyware detects the keyswitch trigger instanly.

**Comment by jpbarraca** [comment]
Babyware constantly polls the panel, we don't. You can implement a similar behavior by reducing the KEEP_ALIVE_INTERVAL. Take in consideration that we (at least I don't) have a clear idea about the safe values. Lower values may result in events being blocked (or not...), especially in panels with slower baud rate (SP, MG).

If you have the time, reduce the value and report your findings.

**Comment by clau-bucur** [comment]
I've set it to 1. Now, of course, the reaction is realtime-like.
One positive side-effect is that now the motion sensors are detected very accurately when someone passes by (with the default value I could not use them because they would not report 90% of the movement).

Shall I watch out for something in particular while testing with this low value?

**Comment by jpbarraca** [comment]
We have two sources of information, direct memory status and events. For those sensors, the asynchronous events should be enough and you should not get any delay. With a low polling interval you are actually forcing pai to constantly update the status.

What intrigues me is why you are missing live events...

**Comment by clau-bucur** [comment]
> What intrigues me is why you are missing live events...
The motion detection trigger when the system is unarmed is considered a live event? I was missing only events while panel is disarmed. While it was armed I was receiving proper events.

I have not tested yet events while armed with the low polling interval.

**Comment by yozik04** [comment]
@clau-bucur Setting that to 1 is a bad idea it can pile up if it will not manage to get all status within one second.
Did you set live event broadcasting on serial port in babyware?

**Comment by yozik04** [comment]
See link: https://github.com/ParadoxAlarmInterface/pai/wiki/Configuration#panel-side

**Comment by clau-bucur** [comment]
> 
> 
> @clau-bucur Setting that to 1 is a bad idea it can pile up if it will not manage to get all status within one second.
> Did you set live event broadcasting on serial port in babyware?

I have not set that, did not know about it! I've set it now. GREAT! Instant detection of motion while disarmed! This now makes PAI more perfect, if you allow my expression :))

@yozik04 What would be a safer value then? I'd still like a better reaction to this keyswitch.

**Comment by yozik04** [comment]
@clau-bucur Did you enabled event broadcasting now? If yes, then please send me new debug log for the keyswitch.

**Comment by clau-bucur** [comment]
Here it is.
[paradox.log](https://github.com/ParadoxAlarmInterface/pai/files/5281793/paradox.log)

**Comment by yozik04** [comment]
Nope, no luck. No event was sent.

**Comment by clau-bucur** [comment]
OK, then what would be an acceptable minimum value for the pooling interval?

**Comment by yozik04** [comment]
On EVO192 it is pretty fast. It fetches all within 600-700ms. Put 2 seconds. It should be safe.

**Comment by clau-bucur** [comment]
Great. Thank you @yozik04 !!
