### ISSUE TITLE
Unable to connect PAI to SP5500 via telnet

### ISSUE THREAD

**Issue by fishermanG** [ParadoxAlarmInterface/pai#177]
## Alarm system
 SP5500

## Environment
-->HASS.IO on RP3B+ with Serial Connection over telnet via ESP32 (Connected RX to TX2; TX to RX2. GND and VCC not connected. Tried swapping Rx with Tx, no avail. 

My config:
LOGGING_FILE: null
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
LOGGING_DUMP_PACKETS: false
LOGGING_DUMP_MESSAGES: false
LOGGING_DUMP_STATUS: false
LOGGING_DUMP_EVENTS: false
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: 192.168.1.126
IP_CONNECTION_PORT: 23
IP_CONNECTION_PASSWORD: paradox
IP_CONNECTION_SITEID: null
IP_CONNECTION_EMAIL: null
IP_CONNECTION_PANEL_SERIAL: null
IP_CONNECTION_BARE: true
LIMITS: {}
SYNC_TIME: true
PASSWORD: '0000'

## Question
Unable to connect to alarm panel. Keep getting "ERROR    - PAI - Unable to connect to alarm"

**Comment by yozik04** [comment]
GND needs to be connected. I recommend to use a level shifter with ESP32 as it is not meant to be used with 5V input signals.

**Comment by fishermanG** [comment]
Silly me. Should have tried connecting the GND. It is working now.

Thanks man.

**Comment by yozik04** [comment]
Enjoy
