### ISSUE TITLE
Log Permission Denied?

### ISSUE THREAD

**Issue by ashtonaut** [ParadoxAlarmInterface/pai#178]
Hi, I'm very interested in this project and I'm looking forward to trying to get connected to my Paradox SP4000.

Thanks in advance for the other questions I am sure will be coming in the near future :)

In advance of receiving my USB-Serial adapter in the mail I am simply testing an install of PAI on my Raspberry Pi to make sure that it runs.

## Alarm System
N/A, just trying to get PAI running for now.

## Environment
RPi 4 running Raspbian Buster, the only user on the system is the default "pi" user
Python 2.7.16
Not using Docker
PAI installed using manual install method from the Github repo noted in Wiki (but I get the same error when installing using the pip3 method). No errors or issues during installation.
My conf file is located at `/home/pi/pai/pai.conf`

## Git branch
Master

## Describe the bug
I get a log permission error when trying to run PAI:

```
# ./run.sh
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/pai/paradox/console_scripts/pai_run.py", line 43, in <module>
    main()
  File "/home/pi/pai/paradox/console_scripts/pai_run.py", line 36, in main
    main(args)
  File "/home/pi/pai/paradox/main.py", line 120, in main
    config_logger(logger)
  File "/home/pi/pai/paradox/main.py", line 39, in config_logger
    delay=0,
  File "/usr/lib/python3.7/logging/handlers.py", line 147, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.7/logging/handlers.py", line 54, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/paradox.log'
```
It seems to me like there is a permission error trying to get logging up and running.

## To Reproduce
1. Install PAI
2. Run PAI
3. Get error

## Logs
Can't send a log as it's the log that's having the issue :)

If I edit `pai.conf` and set `LOGGING_FILE = None` or change the log location to somewhere within the home directory then this error doesn't occur and PAI starts up, but I want to ensure I don't run into other permission errors so want to bottom this one out before I do a workaround. 

There appears to be some kind of permission error with opening the log file to start logging.

My install is fresh and I'm not yet ready to try connecting to a panel, I just want to get PAI running.

Any thoughts? Am I safe to simply change the location of the log file, or should the default install config work without permission errors?

Thanks in advance.

**Comment by yozik04** [comment]
Hey. Create the file manually and give permissions to it.
```
touch /var/log/paradox.log
chmod 666 /var/log/paradox.log
```

**Comment by ashtonaut** [comment]
OK, done and seems to work fine. Now I just have to wait for the USB adapter to arrive for the next phase of testing. Thanks.
