### ISSUE TITLE
HomeAssistant PGM switch missing state payloads

### ISSUE THREAD

**Issue by clau-bucur** [ParadoxAlarmInterface/pai#182]
## Alarm system
EVO192

## Environment
HassOS 4.13 + HA 0.116.2

## Git branch
dev

## Describe the bug
The autodiscovered MQTT switches for PGMs are missing an important part:
**`"state_on": "True",
"state_off": "False"`**

Ommiting them means the switch will fall to defaults using "ON" / "OFF" values to determine the state.
But the actual values under the PGM state are "True" and "False".

**Comment by yozik04** [comment]
Agree. Fix was pushed to dev.
