### ISSUE TITLE
Serial over Telnet - Timeout while connecting to panel

### ISSUE THREAD

**Issue by M-Gregoire** [ParadoxAlarmInterface/pai#183]
Hi,

First of all, thank you for taking the time to share ParadoxAlarmInterface!

I'm trying to connect my alarm (Using the Home Assistant addon) but I didn't managed to solve the following issue.

## Alarm system

I have a MG6250 connected in serial with an ESP32 using a LM2596 for voltage regulation as described in the wiki.

```
[Alarm]      [Voltage regulation]        [ESP32]
RX ----------------------------------------> TX
TX ----------------------------------------> RX
- ---------> - IN          - OUT ----------> GND (Using micro USB input)
+ ---------> + IN          + OUT ----------> +   (Using micro USB input)
```

## Question

ESP32 is connected to Wifi correctly and I'm able to ping / telnet into it. 

If instead of connecting the USB input of the ESP 32 to the voltage regulator, I connect it to my PC, I'm able to see the Home Assistant instance connecting to it.

## Error

```
INFO     - PAI - Starting...
INFO     - PAI.paradox.paradox - Connecting to interface
INFO     - PAI.paradox.paradox - Using IP Connection
INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
INFO     - PAI.paradox.connections.connection - Connection established
INFO     - PAI.paradox.paradox - Connecting to Panel
INFO     - PAI.paradox.interfaces.mqtt.core - MQTT Broker Connected
ERROR    - PAI.paradox.paradox - Timeout while connecting to panel. Is an other connection active?
```

I've tried modifying `MAX_SRV_CLIENTS` to `3` from the `.ino` sketch without success.

## Configuration
```
LOGGING_FILE: null
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
LOGGING_DUMP_PACKETS: true
LOGGING_DUMP_MESSAGES: true
LOGGING_DUMP_STATUS: true
LOGGING_DUMP_EVENTS: true
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: <ip>
IP_CONNECTION_PORT: 23
IP_CONNECTION_PASSWORD: paradox # tried paradox and null
IP_CONNECTION_SITEID: null
IP_CONNECTION_EMAIL: null
IP_CONNECTION_PANEL_SERIAL: null
IP_CONNECTION_BARE: true
LIMITS: {}
SYNC_TIME: true
PASSWORD: '0000' # Tried 0000 and my main user password
MQTT_ENABLE: true
MQTT_HOST: <host>
MQTT_PORT: 1883
MQTT_USERNAME: <user>
MQTT_PASSWORD: <password>
MQTT_RETAIN: true
MQTT_BIND_ADDRESS: 127.0.0.1
MQTT_BIND_PORT: 0
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
```

## Logs

Encrypted as asked in the issue template:

```
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.1.13
Comment: https://keybase.io/crypto

wcFMA4hORRWTO2jFAQ/9H4m4vSKvMce90kL4PyyufKTwStOrkjPD8iQfGhIe6D66
1qC51mI8FQRviTONRXqcjO/lHt5wEafV7i/wCgV3gdlta/8PxLQGt93oMiEE4UM1
kp4yYYxwYRyAs/wixOivFSFBmyKyOb8XXb/cWw08511w9NR2x0adX8zMOK7UcpQw
TWmsu6hAit6oYQfZTygDh+9/8G7lTDH4KqEdfkjG4uBxGpESLHfQeEkLOjJOJULx
fcKKY4k+CrFD/8t1RCW3MGEKRaf10ejKWUO+hGd6i6OzJnGQ/oIS/WFle+VuEWVR
LJt7X2y5EljSNoviY3yD2iqtf3TFZwTYR9han4DB9NmV5axza/bQEB3qimYWKTLJ
ZWwQNpSBnddJlrpMILeI7nJSSl0GZLeMaP7d5mXXfEhy4sr+P0fzqbnuDeAuzHO7
lrXIVJ9QOoLkV1/6NTk3EdfHyrixWvpCVBTH00AU8/h44v++ZPfdP8LfnvMMz98B
9JW90QK9pAIOsW/tPgywSoVweA58YYcNCHvDPQi8kbV2hoZiYpvP9o60GtNU3X46
G7HQ4+/IiFtOvLwltON7v9zg239Z7oVo6xhxAMSTHNmZ34fXBkJoBFGcmkxqgSW9
LhT+2cvGr+JHA6x6lC6I8Y++/p+4uz4p1f2tiwNOGkctAUhFHsASMxCwjDCNKL/S
wckBW6so3dAJSJ+QWYfSsh0IABjqQjrz4TS6f7BKcePtSe0o0bYuTeI6hZBlVsuB
b1riGoWYdgxmfiiD+kcNUSrX8ytKXZY0g400kLXm25RKvDPnWVMHcFg7zbJXMPVT
C6xxhBO376c4/M+TTFQy65orfz8pMts2/KgD1hqv/dz9p+zteaAFLrfV0ebG4wbh
QEI+grF0kRXSWRMpp0EbgXmBvsMfpDadKUcqpNJvEH5re2Bq5n+845uF4X5RdUKu
Eo03bTngFcGjdhHLmUQ42KQ4WjcdP4GEQGmjIYf1hosfoW3oDB2+e2T7LKoDdEkp
UHTTttZ5KET87KV9YlvNxE36k50vNrxtiQBQO6xDEt5Pt6S+ljsQ2rfyBUSNrjJM
4YAeJ6zSYXHX+Mi++2Sk7nHbnVMKESaKNUJCmEz5DBQULVQXNhthJ5ULKQL6KGE1
WFhTo4NeVr0S/kSX6nykzGgr3B4YuQbfIRicp0o2TfOkvfMsoOUzgfxEai5JIMRg
7cyIhAVZVDG4a8GMxQu8ycwznMCt66H6uEVJfA5b0/onb4JgWtyiOdeuIXBcMIZz
IfHNDhP4p6mVALsgqZJdfOecSMCROEjVCJ32OWLK0lcJ/WYcFiMy0KmIkJHnXUWn
Gho2mPto0MestGRRZXW3vuSnEFuWaCixojZzcIY22/8+xWug6EfHTYhSVHWptopZ
1iaqNX0lQqQtkpzgbRxYw62eHwfUFDuy62w53zl1Yw7Axa38C27VtCGiSHeM5kB8
PuagZawJyk+4FpYmc6hbdmJgj7BdIt0zWhpm0uBiRoxEiLpBtXOPCHc+bgTjXUod
0Ff5/1VQuWsSONuO2bsjyJz3jt9nX3koo+ik
=NYsG
-----END PGP MESSAGE-----
```

Do you have any idea or suggestion on how I can solve this issue?

Thank you for any help you might provide.

EDIT: I don't own an IP150 so AFAIK I'm not able to use Babyware to get any kind of password

**Comment by jpbarraca** [comment]
Are you able to receive any message when you use ESP32 connected to the PC through USB?
What code is running on the ESP32?

Can you connect using babyware or winload?

**Comment by M-Gregoire** [comment]
Hi,
Thank you for your answer.
I'm running https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino as advised in the wiki.

When I'm connected to the ESP32 through USB, I'm getting the following:
```
WiFi connected IP address: 192.168.x.x
Ready! Use 'telnet 192.168.x.x 23' to connect
```

I can connect using Telnet on my PC, I get `New client: 0 192.168.x.x` but I don't anything in return

I don't have a GSM nor IP module so I can't use Babyware or Winload AFAIK.

**Comment by M-Gregoire** [comment]
Update: Instead of directly trying with Telnet over Wifi, I wanted to try with a serial communication on my PC through a FTDI232 and using a Docker container for pai locally running on my laptop.

Here is a picture of the wiring (Sorry for the wires color code being absolutely random...):
*I've inverted TX/RX just to be sure but no changes
![Uploading signal-2020-10-24-103658.jpeg…]()


I've configured `pai.conf` to use a `SERIAL` connection on `/dev/ttyUSB0` but got the exact same kind of failure I have with my ESP32.

(Code of the alarm changed to `0000` for the tests):
```
 - INFO     - MainThread - PAI.paradox.connections.serial_connection - Serial port open
 - INFO     - MainThread - PAI.paradox.paradox - Connecting to Panel
 - DEBUG    - MainThread - PAI.paradox.connections.protocols - PAI -> SER b'72000000000000000000000000000000000000000000000000000000000000000000000072'
 - DEBUG    - MainThread - PAI.paradox.paradox - send/receive timeout in 1.0021 s
 - DEBUG    - MainThread - PAI.paradox.paradox - Request retry (attempt 2/5)
 - DEBUG    - MainThread - PAI.paradox.connections.protocols - PAI -> SER b'72000000000000000000000000000000000000000000000000000000000000000000000072'
 - DEBUG    - MainThread - PAI.paradox.paradox - send/receive timeout in 1.0017 s
 - DEBUG    - MainThread - PAI.paradox.paradox - Request retry (attempt 3/5)
 - DEBUG    - MainThread - PAI.paradox.connections.protocols - PAI -> SER b'72000000000000000000000000000000000000000000000000000000000000000000000072'
 - DEBUG    - MainThread - PAI.paradox.paradox - send/receive timeout in 1.0023 s
 - DEBUG    - MainThread - PAI.paradox.paradox - Request retry (attempt 4/5)
 - DEBUG    - MainThread - PAI.paradox.connections.protocols - PAI -> SER b'72000000000000000000000000000000000000000000000000000000000000000000000072'
 - INFO     - MainThread - PAI - Captured signal SIGTERM. Exiting
 - INFO     - MainThread - PAI.paradox.paradox - Disconnecting from the Alarm Panel
 - INFO     - MainThread - PAI.paradox.paradox - Clean Session
 - INFO     - MainThread - PAI.paradox.paradox - Cleaning previous session. Closing connection
 - DEBUG    - MainThread - PAI.paradox.connections.protocols - PAI -> SER b'70250000000000000000000000000000000000000000000000000000000000000000000095'
```

Am I missing something obvious ?

Thank you

**Comment by yozik04** [comment]
As you have ftdi232 now. Connect usb cable to a windows pc and try serial connection with babyware.

**Comment by yozik04** [comment]
Ftdi Jumper should be at 5V. Use voltage meter to find ground and power on the panel.

**Comment by M-Gregoire** [comment]
I didn't know I could use Babyware using my FTDI232!

I was able to connect to the alarm and retrieve all the data so serial connection seems to be working properly

**Comment by yozik04** [comment]
I looked into the link https://bmpc.github.io/2020/05/30/reverse-engineering-mg6250.html you have provided and the guy references our PAI project and as i understood protocol is different.

**Comment by M-Gregoire** [comment]
Indeed, using the Python script in the link above I'm able to receive the events when I interact with the alarm.
Unfortunately, the project is far less complete than PAI: integration in homeassistant will be possible but probably a bit harder with less functionality. I might buy a MG5050...

In any case, thank you for your help! I assumed MG6250 would share the same protocol but unfortunately not.

I would love to see PAI extended to support MG6250 but I'm not skilled enough to do so. If this is something you would be ready to consider, I would happily send one to someone willing to give it a try.

**Comment by yozik04** [comment]
I doubt so. Is IP150 even supported by MG6250 if TX and RX are swapped?

**Comment by M-Gregoire** [comment]
Oh indeed:
`Spectra SP (V2.10 or above), MG5000 / MG5050 (V2.10 or above) / MG5075 et EVO / EVOHD.`

Looks like I'm out of luck

**Comment by yozik04** [comment]
If somebody with MG6250 will want to reverse engineer this new protocol then we are happy to help. But it is too complicated and is cheaper to buy a supported panel. Unfortunately.

**Comment by yozik04** [comment]
Updated [Compatibility](https://github.com/ParadoxAlarmInterface/pai/wiki/Compatibility) page.

**Comment by M-Gregoire** [comment]
Guess I'll go with the easy option of buying another one!

Thanks a lot for taking the time to help me and work on this project.

**Comment by thermseekr** [comment]
Hello all,

I am too struggling to connect to MG6250, and I finally found this topic. I'm trying with a Raspberry Pi, and I reached a point where the panel is identified, but nothing happens after that, as it can be seen below:

```
Attempting to load configuration from /home/pi/pai.conf
2020-12-26 08:22:37,566 - INFO     - PAI - Starting Paradox Alarm Interface 2.2.4
2020-12-26 08:22:37,566 - INFO     - PAI - Config loaded from /home/pi/pai.conf
2020-12-26 08:22:37,566 - INFO     - PAI - Console Log level set to 20
2020-12-26 08:22:37,570 - INFO     - PAI - Starting...
2020-12-26 08:22:37,571 - INFO     - PAI.paradox.paradox - Connecting to interface
2020-12-26 08:22:37,571 - INFO     - PAI.paradox.paradox - Using Serial Connection
2020-12-26 08:22:37,593 - INFO     - PAI.paradox.connections.serial_connection - Connecting to serial port /dev/ttyUSB0
2020-12-26 08:22:37,598 - INFO     - PAI.paradox.connections.serial_connection - Serial port open
2020-12-26 08:22:37,599 - INFO     - PAI.paradox.paradox - Connecting to Panel
2020-12-26 08:22:37,632 - INFO     - PAI.paradox.paradox - Panel Identified MG6250 version 1.80 build 2
2020-12-26 08:22:37,632 - INFO     - PAI.paradox.paradox - Initiating panel connection
2020-12-26 08:22:42,648 - ERROR    - PAI.paradox.paradox - Timeout while connecting to panel. Is an other connection active?
2020-12-26 08:22:42,654 - ERROR    - PAI - Unable to connect to alarm

```
 
Unfortunatelly I currently can't spend the time to try to reverse engineer the protocol. Will consider migrating to other panel.

Happy new year everone!
Tales

**Comment by thermseekr** [comment]
> I looked into the link https://bmpc.github.io/2020/05/30/reverse-engineering-mg6250.html you have provided and the guy references our PAI project and as i understood protocol is different.

Indeed the protocol looks different, but he has already progressed to correctly receive event messages and send them out via MQTT. Isn't this a good start for integrating this panel into PAI?
