### ISSUE TITLE
Can not read config file

### ISSUE THREAD

**Issue by tilentravnik** [ParadoxAlarmInterface/pai#184]
Hi, I'm running PAI as an add-in in HA. Running 2.2.2. When I start the add-in I get the following message in the log:
`Attempting to load configuration from /data/options.json
Traceback (most recent call last):
  File "/usr/local/bin/pai-service", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/paradox/console_scripts/pai_run.py", line 36, in main
    main(args)
  File "/usr/local/lib/python3.7/site-packages/paradox/main.py", line 118, in main
    cfg.load()
  File "/usr/local/lib/python3.7/site-packages/paradox/config.py", line 314, in load
    with open(self.CONFIG_FILE_LOCATION) as f:
PermissionError: [Errno 13] Permission denied: '/data/options.json'`

All was working a few days ago.

**Comment by skkostas** [comment]
I have the same issue after I reboot my RPI. 

HA version 0.116.2
OS version 4.13

**Comment by yozik04** [comment]
Created an issue in supervisor's repo.

**Comment by yozik04** [comment]
I also got that after reboot. Strange that other plugins work fine.

**Comment by dragonflyuk** [comment]
I've woken up to this aswell.

**Comment by vargatomy** [comment]
I have the same issue for a couple of days
OS: Ubuntu 18.04.5 LTS \n \l
Docker: Docker version 19.03.13, build 4484c46d9d
HA: 0.116.4
PAI: 2.2.2

Thanks for checking!

**Comment by kylev12** [comment]
I have the same issue today after a reboot also,

HA version: 0.116.4
OS version: 4.14
PAI version: 2.2.2
----

Attempting to load configuration from /data/options.json
Traceback (most recent call last):
  File "/usr/local/bin/pai-service", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/paradox/console_scripts/pai_run.py", line 36, in main
    main(args)
  File "/usr/local/lib/python3.7/site-packages/paradox/main.py", line 118, in main
    cfg.load()
  File "/usr/local/lib/python3.7/site-packages/paradox/config.py", line 314, in load
    with open(self.CONFIG_FILE_LOCATION) as f:
PermissionError: [Errno 13] Permission denied: '/data/options.json'
---

**Comment by yozik04** [comment]
Fixed in dev.
Master is in progress.

**Comment by yozik04** [comment]
Should be fixed now.

**Comment by tilentravnik** [comment]
Is there a way to upgrade this or should I just wait for an updated Add-on?

**Comment by yozik04** [comment]
If you are using dev version then you need to reinstall the plugin.
I do not know how supervisor updates addons. For main version maybe a reboot is sufficient to trigger update.

**Comment by tilentravnik** [comment]
I tried rebooting the host - no change. I tried uninstalling the add-on - no change (installed version 2.2.2 right back). Now running the dev version of the add-on with no problems. Would be nice to fully understand how new add-on versions are distributed. Thanks for the help @yozik04 !

**Comment by Gunth** [comment]
Remove the repository and add it worked for me ...

**Comment by tilentravnik** [comment]
Yes, uninstalling and reinstalling the repository works.
