### ISSUE TITLE
MQTT Dash and Hassio

### ISSUE THREAD

**Issue by M-Gregoire** [ParadoxAlarmInterface/pai#187]
Hi,

I've been trying out PAI addon for HASSIO: it worked right out the box!

However, I'm trying to get the MQTT Dashboard working on Android without success.
I've added `MQTT_DASH_PUBLISH: true` to my config but got the following error in the logs:
```
WARNING  - PAI.paradox.interfaces.mqtt.basic - MQTT DASH Template not found: /etc/pai/mqtt_dash.txt
```

Am I supposed to add this template or should it already be in the container ?

I'm sorry If I missed any info in the wiki, I couldn't find anything relevant.

**Comment by bogd** [comment]
For some reason, the mqtt-dash template is missing from the official image (and the instructions do not mention it at all). However, it is quite easy to get it back - if you followed the [instructions](https://github.com/ParadoxAlarmInterface/pai/wiki/Docker), just copy the file (you can find it [here](https://github.com/ParadoxAlarmInterface/pai/blob/dev/config/mqtt_dash.txt)) to ~/docker/pai/config .
