### ISSUE TITLE
PIR with SDD

### ISSUE THREAD

**Issue by Bl00d-B0b** [ParadoxAlarmInterface/pai#190]
Hello,

I use Paradox, and I have PIR with SDD. How I can merge PIR & SDD
For example, my PIR is on zone 10, and SDD is on zone 20. actually it's the same sensor. 

I want to use it as a one single Presence detection on my Homeassistent system. not like 2 separate. 

How i can implement it?

Ed

**Comment by yozik04** [comment]
No idea what is SDD. But this does not matter.
Group them and check status of the group. All is HomeAssistant configuration.

**Comment by Bl00d-B0b** [comment]
Hello,

PIR is motion sensor, connected to Zone 10
SDD is a break glass sensor, connected to Zone 20

but both sensors are in a single device.

And I seems found another issue, which possible need to be fixed.
I Label in paradox Zone 10 & Zone 20 with the same name.

As result in mqtt I see only one sensor, instead of 2 sensors!

Ed
