### ISSUE TITLE
Zone name change

### ISSUE THREAD

**Issue by rocrockyroc** [ParadoxAlarmInterface/pai#192]
Hello, Changing Zone name, at the Alarm Panel seams to generate two names for one zone within home assistant.
I have tried everything accept restarting your plug in from scratch as Im happy with it.  
there does not seam to be away to delete the old Zone name or refresh the zones.   I have two zones names for one actual zone.
EVO 192 using IP150 over IP working perfectly for months, just want to remove this duplication.

Thanks
Roc

**Comment by yozik04** [comment]
Hello. Please use MQTT Explorer and delete manually.
