### ISSUE TITLE
Add Code to HomeAssistant MQTT Discovery

### ISSUE THREAD

**Issue by somejavadev** [ParadoxAlarmInterface/pai#194]
## Alarm system
EVO192 version 6.86
IP(IP150) Module version 20, firmware: 1.34

## Environment

Home Assistant Integration:

Version | 2020.12.2
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 5.4.84
CPU Architecture | x86_64

## Git branch
Current version: 2.2.4

## Describe the bug
Adding a code to the home assistant interface is not honored and the alarm may be set without a valid code. See documentation

https://github.com/ParadoxAlarmInterface/pai/wiki/Home-Assistant-integration#homeassistant-keypad

## To Reproduce
1. Configure the home assistant integration via IP and MQTT access.
2. Add an alarm_panel entity to the UI using one of the partitions on the Paradox system:

![image](https://user-images.githubusercontent.com/6507120/103787332-1f6b7180-5046-11eb-85c4-ec2632c522cc.png)   
   
Lovelace yaml:   
```yaml
type: alarm-panel
states:
  - arm_home
  - arm_away
entity: alarm_control_panel.inside
```

3. You will notice there is no keypad, now follow the [documentation](https://github.com/ParadoxAlarmInterface/pai/wiki/Home-Assistant-integration#homeassistant-keypad) to enable the keypad.
   
![image](https://user-images.githubusercontent.com/6507120/103787842-cfd97580-5046-11eb-9295-78cce14e73d0.png)

Observe that the customize.yaml was updated by home assistant:

![image](https://user-images.githubusercontent.com/6507120/103788039-10d18a00-5047-11eb-908c-3acc8867c623.png)
   
4. Restart the home assistant instance  or reload the customisations under server controls.
5. You will notice the lovelace entity still doesn't require a code.
 
![image](https://user-images.githubusercontent.com/6507120/103788787-eaf8b500-5047-11eb-9675-72d8c8ce21c6.png)

I would expect the UI to now show the Keypad.
I have confirmed that my customize.yaml is included in my main configuration file of home assistant.
```yaml
homeassistant:
  customize: !include customize.yaml
```

**Comment by yozik04** [comment]
Great bug report, but unfortunately in a wrong place. This is Home Assistant bug for MQTT Alarm Panel. You need to create a bug report there.

**Comment by somejavadev** [comment]
@yozik04 thanks, I noticed it is even happening on the alarm panels created by templates so definitely not related to pai. I will log the bug on home assistant.

**Comment by yozik04** [comment]
Please link this task to one in Home Assistant to keep track of it.
I will reopen this. Let it stay until it will be fixed in Home Assistant.

**Comment by somejavadev** [comment]
Home Assistant Issue https://github.com/home-assistant/core/issues/44894 for reference.

**Comment by somejavadev** [comment]
@yozik04, from the home assistant issue it seems like these properties will need to be passed in from the discovery message. See this comment https://github.com/home-assistant/core/issues/44894#issuecomment-757050244. I am not sure if this has worked previously, do you think these properties could be configured in configuration of the Pai integration? Perhaps adding it to this section:

![image](https://user-images.githubusercontent.com/6507120/104088466-e7e00d80-526f-11eb-8101-951fca82db3f.png)

**Comment by somejavadev** [comment]
@yozik04, with regards to the outcome from the home assistant issue https://github.com/home-assistant/core/issues/44894#issuecomment-759567719, do you think we can add this to the plugin?

**Comment by yozik04** [comment]
Sure we can. Should be simple. The most complicated is to find time.

**Comment by yozik04** [comment]
I have pushed this feature to Development version. It seems to be working fine.

Config parameter:
```
MQTT_HOMEASSISTANT_CODE = '123456'
```

**Comment by somejavadev** [comment]
@yozik04, excellent. Thanks for the effort. I will give it a try.

**Comment by yozik04** [comment]
Did dev version solved it?

**Comment by somejavadev** [comment]
@yozik04 thanks, it look like it has. I am a bit swamped with work at the moment and haven't tested it thoroughly. The one thing I still would like to test is if it will be possible to create a single home assistant alarm panel which activates multiple zones now that the we can set the code via PAI.

**Comment by remirr** [comment]
Does anyone have simple instructions on what needs to be done to activate the code? Where do I need to add what code to get this working? 

At the moment I just have the state buttons in my Lovelace Dash

**Comment by adumnov** [comment]
> 
> 
> Does anyone have simple instructions on what needs to be done to activate the code? Where do I need to add what code to get this working?
> 
> At the moment I just have the state buttons in my Lovelace Dash

+1

**Comment by somejavadev** [comment]
Hi @remirr and @adumnov, I have unfortunately moved away from using this implementation and switched over to the Paradox Printer Module. The reason being even with this code implementation you can only use a single user code which is hard coded in Home Assistant. With the printer module you can arm/disarm the panel with the different user codes configured on the panel itself.

**Comment by somejavadev** [comment]
Hi @yozik04, I saw the changes above haven't been promoted to stable. I am switching back from the printer module to the IP150 method of integrating and thought I let you know I have tested them and they are working as expected should you want to propagate them.

Version Tested on:
Home Assistant 2022.8.7
Supervisor 2022.08.3
Operating System 8.5

**Comment by yozik04** [comment]
`MQTT_HOMEASSISTANT_CODE` was added in 3.0.0 I think. When I merged everything in `dev` to `master`. Currently `dev` and `master` branches are equal
