### ISSUE TITLE
PGM/output activation

### ISSUE THREAD

**Issue by brettmeyerowitz** [ParadoxAlarmInterface/pai#201]
Hi,

I have implemented PAI via MQTT and integrated successfully into homebridge using mosquitto and mqttthing and wanted to know if there is a way to activate a PGM via MQTT and if so what the topic/message would be? 

I see a list of outputs such as panic_radio, status_led and wanted to add my garage and gate via this functionality.

Many thanks for an awesome platform!

Brett

**Comment by yozik04** [comment]
Please check wiki first.

**Comment by brettmeyerowitz** [comment]
Thanks for the super quick reply - couldn't find anything in the wiki for this.

**Comment by yozik04** [comment]
https://github.com/ParadoxAlarmInterface/pai/wiki/MQTT-Interface#control

**Comment by brettmeyerowitz** [comment]
Thanks!
