### ISSUE TITLE
MQTT discovery config topics should not contain UTF-8 characters

### ISSUE THREAD

**Issue by danygi79** [ParadoxAlarmInterface/pai#202]
hello, I have this Warning in log:

WARNING  - PAI.paradox.hardware.panel - Unable to properly decode label b'Sens.Scale 1\xd2 P' using the utf-8 encoding.
                     Specify a different encoding using the LABEL_ENCODING configuration option.
2021-02-10 22:29:52,139 - WARNING  - PAI.paradox.hardware.panel - Unable to properly decode label b'Fin. Bagno 1\xd2 P' using the utf-8 encoding.

I used the character °, the complete string is "Sens.Scale 1 ° P". I think it is enough to indicate a different character set in LABEL_ENCODING, I have also tried but without success.
Is it possible to fix this warning somehow?

**Comment by J-Prince** [comment]
I have a similar issue with French accents:

2021-02-11 10:06:43,567 - WARNING  - PAI.paradox.hardware.panel - Unable to properly decode label b'Salle \x9c diner' using the utf-8 encoding.
                     Specify a different encoding using the LABEL_ENCODING configuration option.

No matter which encoding I tried, I could never get it to properly decode the label, "Salle à diner" in this case. So I just left the default value and managed the names in HomeAssistant.

**Comment by yozik04** [comment]
Try `paradox-en` as `LABEL_ENCODING`, it might work. Paradox has a weird custom encoding we did not covered all the symbols.

**Comment by J-Prince** [comment]
Yes, by using `paradox-en` the labels are now loaded properly. However, it seems HomeAssistant Auto Discovery doesn't like them, because they never show up in HA entities even though I see them properly in MQTT.

**Comment by yozik04** [comment]
can be that some symbols are not allowed in ids. Please send some `config` payloads.

**Comment by yozik04** [comment]
From this paths:
- `homeassistant/alarm_control_panel/<panel_serial>/<name>/config`
- `homeassistant/binary_sensor/<panel_serial>/<name>/config`

**Comment by J-Prince** [comment]
> can be that some symbols are not allowed in ids. Please send some `config` payloads.

Here's one that doesn't show up in HA:

Control Panel:
`{"name": "CHALET", "unique_id": "XXXXXXXX_partition_CHALET", "command_topic": "alarme-chalet/control/partitions/CHALET", "state_topic": "alarme-chalet/states/partitions/CHALET/current_state", "availability_topic": "alarme-chalet/interface/availability", "device": {"manufacturer": "Paradox", "model": "SP7000", "identifiers": ["Paradox", "SP7000", "XXXXXXXX"], "name": "SP7000", "sw_version": "4.94 build 0"}, "payload_disarm": "disarm", "payload_arm_home": "arm_stay", "payload_arm_away": "arm", "payload_arm_night": "arm_sleep"}`

Binary Sensor:
`{"name": "Fum\u00e9e sous-sol", "unique_id": "XXXXXXXX_zone_Fum\u00e9e_sous_sol_open", "state_topic": "alarme-chalet/states/zones/Fum\u00e9e_sous_sol/open", "device_class": "motion", "availability_topic": "alarme-chalet/interface/availability", "payload_on": "True", "payload_off": "False", "device": {"manufacturer": "Paradox", "model": "SP7000", "identifiers": ["Paradox", "SP7000", "XXXXXXXX"], "name": "SP7000", "sw_version": "4.94 build 0"}}`

**Comment by yozik04** [comment]
ok. First is because of #204. Fix is coming.

**Comment by yozik04** [comment]
No idea about second one. Check home assistant logs

**Comment by tekand** [comment]
I am experiencing the same issue with Hungarian special chars (if using `paradox-en`). The special characters are not appearing at all if using `utf8` or `latin2`.

```
Host1:
	HA: core-2021.2.3 in docker (with Python: 3.8.7)
	MQTT broker: Eclipse Mosquitto in docker (v2.0.7)

Host2:
	PAI: v2.3.1
		paho: v1.5.1
		pyserial: v3.5
```
Panel:

```
2021-02-20 09:54:33,042 - INFO     - PAI.paradox.paradox - Panel Identified MG5000 version 4.86 build 6
```
HA log:

Message is received on HA side

```
2021-02-20 09:54:43 DEBUG (Thread-5) [paho.mqtt.client] Received PUBLISH (d0, q0, r0, m0), 'homeassistant/binary_sensor/XXXXXXXX/Bejárati_Ajtó/config', ...  (446 bytes)

2021-02-20 09:54:43 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/binary_sensor/XXXXXXXX/Bejárati_Ajtó/config: b'{"name": "Bej\\u00e1rati Ajt\\u00f3", "unique_id": "XXXXXXXX_zone_Bej\\u00e1rati_Ajt\\u00f3_open", "state_topic": "paradox/states/zones/Bej\\u00e1rati_Ajt\\u00f3/open", "device_class": "motion", "availability_topic": "paradox/interface/availability", "payload_on": "True", "payload_off": "False", "device": {"manufacturer": "Paradox", "model": "MG5000", "identifiers": ["Paradox", "MG5000", "XXXXXXXX"], "name": "MG5000", "sw_version": "4.86 build 6"}}'
```

But cannot find 'process discovery payload' entry for the sensor which has the special char. It exists for all others:

```
2021-02-20 09:54:43 DEBUG (MainThread) [homeassistant.components.mqtt.discovery] Process discovery payload 
```

**Comment by yozik04** [comment]
hmm, maybe home assistant does not like utf-8 chars in mqtt topic?

**Comment by yozik04** [comment]
@tekand Can you try to replace special chars in hte topic and resubmit the payload. Will it appear in home assistant?

**Comment by tekand** [comment]
Certainly. Can you please elaborate a bit more on how to do that? This is my first pai and mqtt install.

**Comment by yozik04** [comment]
Get MQTT Explorer, there should be simple to do

**Comment by tekand** [comment]
I have MQTT Explorer, but did not find hte topic. 

Not sure how relevant, but the following doc says that the id should be `[a-zA-Z0-9_-]`.
https://www.home-assistant.io/docs/mqtt/discovery/#discovery_prefix

I guess that means that utf-8 special chars are not supported in the id, but maybe in the name attribute.

**Comment by tekand** [comment]
@J-Prince @danygi79 
With the new release the encodings have been updated. Can you please check whether your problem also appears with the latest release? The MQTT topics only contain ascii chars now, so there might be some slight name-changes here and there.:)

@radokristof 
I have introduced a new `paradox-hu` encoding. :) Can you please test it with your labels?

Details about the new encodings: https://github.com/ParadoxAlarmInterface/pai/wiki/Configuration#label-encodings

**Comment by J-Prince** [comment]
> @J-Prince @danygi79
> With the new release the encodings have been updated. Can you please check whether your problem also appears with the latest release? The MQTT topics only contain ascii chars now, so there might be some slight name-changes here and there.:)

I updated to pai to 2.5.1, switched my encoding to "paradox-en", cleaned up MQTT, restarted Home Assistant. Everything is perfect! Well worth the time it took to rename some entities in Home Assistant to fix the changes :-) THANK YOU!

**Comment by tekand** [comment]
@yozik04 I believe we can mark this as solved. :)

**Comment by yozik04** [comment]
@tekand I agree with you.
