### ISSUE TITLE
Have the ability to connect multiple Panels

### ISSUE THREAD

**Issue by DjBac** [ParadoxAlarmInterface/pai#210]
Is there a way to be able to connect to two or even three different panels at the same time?

**Comment by yozik04** [comment]
Only if you use multiple PAI instances.

**Comment by DjBac** [comment]
They only way to have multiple PAI instances is if I also use the development version, right? When I do that, then I can see only one, I suppose the above commit I see fixes that?

**Comment by yozik04** [comment]
If you are talking about home assistant then yes. You need that latest dev version. Before that version all panels and sensors ended up under a single device.

**Comment by J-Prince** [comment]
Using the hassio-repository, would it be possible to run multiple instances of PAI under Home Assistant?

**Comment by yozik04** [comment]
How many you need?

**Comment by J-Prince** [comment]
I have to connect to 2 panels in my use case. This is not high priority as I'm running 2 containers of the same image in Docker, but it's not managed within HA for updates, etc.

**Comment by yozik04** [comment]
Having PAI running in Docker without HA increases stability and you can rollback any time. I think this is a great benefit over supervisor approach.

Anyway I have added `(Second instance)`


![image](https://user-images.githubusercontent.com/2420038/110990939-aad1ed80-837c-11eb-919d-3a2828466f61.png)

**Comment by DjBac** [comment]
Although I can connect to two panels at the same time (with second instance version), then all the sensors are combined into one device. Furthermore, when I try to arm one panel, then both panel get armed. How can I separate the two panels to act as two individual alarm systems?

**Comment by yozik04** [comment]
@DjBac Use dev version. There was a fix for that.

**Comment by DjBac** [comment]
> @DjBac Use dev version. There was a fix for that.

Thanks for your reply. I've just tried it and although it connects to the panel, it does not show up in my MQTT devices at all.

**Comment by yozik04** [comment]
Verify settings it should come up. Inspect logs carefully. Compare with other instance. It is also possible that your MQTT broker allows only one client per username.

**Comment by DjBac** [comment]
> Verify settings it should come up. Inspect logs carefully. Compare with other instance. It is also possible that your MQTT broker allows only one client per username.

I've just double-checked. Even with a different MQTT user, still the 2nd panel will not show up in home assistant.

**Comment by DjBac** [comment]
I am still struggling with this one! Is there a way to produce different ids for a second and/or third panel? Instead, when I connect the 2nd panel, its zones/areas integrate with the first panel. After that, when for instance I try to arm area1 on the first panel, it shows "arming" at area1 on both panels.
