### ISSUE TITLE
HA Zone configuration

### ISSUE THREAD

**Issue by jakezp** [ParadoxAlarmInterface/pai#211]
## Alarm system
Magellan MG5050, IP150, Home assistant

## Environment
paradoxalarminterface (Docker - paradoxalarminterface/pai:latest)
mqtt (Docker - eclipse-mosquitto:latest)
Home assistant (Docker - homeassistant/home-assistant)

MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE = True

### Git branch
master branch (switched over from dev branch yesterday while testing)

## Question
A while ago, while on the dev branch, after an update all zones, etc were picked up as sensors, etc. in the following format:
_binary_sensor.paradox_210f8f23_zone_zone_name_open_, including multiple sensors for each zone. As a result, I have 100s of zones.

Previously, zones were picked up as _binary_sensor.zone_name_. And I only had 1 sensor per zone and then the alarm and status, etc.

I went through the process of renaming the friendly name for all my zones, taking hours to work through all the zones. Yesterday I updated again and things went haywire, so as a result, I deleted the discovered device from home assistance (MG5050) and restarted home assistant. Once it was discovered again, all my friendly name customizations were gone. 

I then switched to the master branch, hoping that I I would get the short version of zone names back. 

I restarted everything a few times and eventually I had 2 MG5050 devices. I deleted the one and after another restart I was left with 1 device containing the short version sensors (_binary_sensor.zone_name_) AND the 'verbose version' with 100s of sensors (_binary_sensor.paradox_210f8f23_zone_zone_name_open_).

This was acceptable, since I could only pick out the shorter version sensors and update all my configurations. This morning when I logged in, I see that all the short version sensors were all 'unavailable' and the long version sensor are all still active.

I really do not want to update all my automations again and set the friendly name for all those zones again and I really have no use for 100s of sensors.

- Is there a way I can configure ParadoxAlarmInterface to only return the short version sensors?
- Did I mess something up by switching from dev to master branch? Should I kill my docker, wipe my config and start again? 

I really do not want to update all my automations again and set the friendly name for all those zones again and I really have no use for 100s of sensors.

Apologies for the lengthy post, but I'd like to provide context.

**Comment by jakezp** [comment]
Forgot to mention. When I restart the pai docker, enables the 'short version' sensor again, along with the 'long version' sensors. But after a while, the short version sensors flip to unavailable again.

**Comment by yozik04** [comment]
I see you've got all possible fun.

master uses "short versions"
dev uses "long versions"
yesterday's dev update changed device id so you end up with two devices in homeassistant but one will be without sensors.

if you automation uses short versions I recommend staying on master.

**Comment by yozik04** [comment]
in future I will need to deprecate "short versions".

**Comment by jakezp** [comment]
Thanks for the info. I think I need to restart my pai integration, stay on dev branch and get used to the 'long versions', spend hours adding friendly names, update all configurations and automations to use the long versions...

At least I know now there is no configuration to switch between "long - and short versions"
