### ISSUE TITLE
How does one bypass zones through Home Assistant?

### ISSUE THREAD

**Issue by Vandiliz3r** [ParadoxAlarmInterface/pai#215]
The title says it all, Any pointers will be highly appreciated.

**Comment by MidnightZA** [comment]
This is probably not the best way to do it, but this is what I learnt from another forum.

I created a MQTT Switch for the zone "LOUNGE DOOR" (NB This is case sensitive according to your panel zones, took me days to troubleshoot that)

`switch:
  - platform: mqtt   
    name: "Lounge Door"
    command_topic: "paradox/control/zones/LOUNGE_DOOR"
    state_topic: "paradox/states/zones/LOUNGE_DOOR/bypassed"
    qos: 0
    optimistic: true
    state_on: "True"
    state_off: "False"  
    payload_on: "bypass"
    payload_off: "clear_bypass"
    payload_available: "Online"
    payload_not_available: "Offline"`

In the customize.yaml file, add this to show as a toggle on the dashboard
`switch.lounge_door:
  assumed_state: false`

Mine looks like this now

![image](https://user-images.githubusercontent.com/75374729/109921708-f7eef900-7cc4-11eb-982b-2984d4cbd2db.png)

**Comment by Vandiliz3r** [comment]
This is awesome, This is exactly what i have looking for!!!! Thanks I am going to give it a try and get back to you!

**Comment by yozik04** [comment]
@MidnightZA It is right way to do it.

**Some comments:**
Not sure if you need these:
```
qos: 0
optimistic: true
```

and next does not make any sense without `payload_topic` defined
```
payload_available: "Online"
payload_not_available: "Offline"
```

**Comment by yozik04** [comment]
`availability_topic`... not `payload_topic`

**Comment by MidnightZA** [comment]
@yozik04 Thanks. I just copied it from another forum. It worked as is so I didnt fiddle with anything.

**Comment by Vandiliz3r** [comment]
Guys

This is not working, Can you please point out where my issues is?

  - platform: mqtt
    name: "Kitchen Door"
    command_topic: "paradox/control/zones/kitchendoor"
    state_topic: "paradox/states/zones/kitchendoor/bypassed"
    state_on: "True"
    state_off: "False"
    payload_on: "bypass"
    payload_off: "clear_bypass"
    payload_available: "Online"
    payload_not_available: "Offline"

**Comment by MidnightZA** [comment]
Is your entity ID correct as per the MQTT info?

To check go to Configuration > Devices > (Search Paradox) > (Select your panel) > (Select MQTT info)

![Screenshot_20210309-160448_Home Assistant](https://user-images.githubusercontent.com/75374729/110482644-8dd5ba00-80f1-11eb-85bb-435be6d52201.jpg)

For example, my kitchen door is "KITCHEN_DOOR", but my entity ID is all lower case.

**Comment by weitheng** [comment]
I am using the same configs as @MidnightZA, any idea why this is not working?

> 021-03-23 20:00:16,574 - INFO     - PAI.paradox.interfaces.mqtt.basic - message topic=paradox/control/zones/2_Kch___Laundry, payload=bypass
2021-03-23 20:00:16,577 - ERROR    - PAI.paradox.paradox - No zones selected
2021-03-23 20:00:16,578 - WARNING  - PAI.paradox.interfaces.mqtt.basic - Zone command refused: 2_Kch___Laundry=bypass user: None

@yozik04 I tried adding `availability_topic: paradox/interface/availability`, but it says undetected, which is why I took the code off. But seems like it's doing its job, because it looks like it's not detecting it, which is why it doesn't work. 

![Screenshot 2021-03-23 at 12 07 15](https://user-images.githubusercontent.com/34220268/112143852-5aeef400-8bd0-11eb-8b85-2619ccc9a812.png)

Any help would be greatly appreciated.

**Comment by Vandiliz3r** [comment]
This worked perfectly thanks!!!

**Comment by weitheng** [comment]
Can someone help?

**Comment by Ives25** [comment]
Hi
it doesn't work for me.

[url=https://zupimages.net/viewer.php?id=23/15/8d9s.jpg][img]https://zupimages.net/up/23/15/8d9s.jpg[/img][/url]

[url=https://zupimages.net/viewer.php?id=23/15/v2d7.jpg][img]https://zupimages.net/up/23/15/v2d7.jpg[/img][/url]

**Comment by yozik04** [comment]
https://github.com/ParadoxAlarmInterface/pai/wiki/Home-Assistant-integration#add-more-properties-to-zones-or-partitions

This does not work?
Bypass switch is not exposed by default. You can control that.

**Comment by Ives25** [comment]
With this code I am only allowed to restart HA. I would like to create a bypass for an area.

**Comment by yozik04** [comment]
This is your custom stuff. Line 2 is incorrect. Autodiscovery should add bypasses.

**Comment by Ives25** [comment]
The error is still present with the deletion of line 2.

![pb contournement](https://user-images.githubusercontent.com/50076025/232253042-75918ce7-57c0-42c0-8de1-7869202ee82f.jpg)
