### ISSUE TITLE
Question about compatibility with the new paradox MG5075

### ISSUE THREAD

**Issue by elclaudio** [ParadoxAlarmInterface/pai#224]
## Alarm system

Paradox MG5075
## Environment

Linux armbian on odroid-c2
### Git branch

none for now
## Question

Hi there
I'm about to buy an alarm system and because of this software, I'm decided on buying a paradox one.

Still I'm not sure of the model I should buy. First, I was tempted by the EVO192 because (if I understand correctly, correct me if I'm wrong) the ability to use bus detectors and have better specs than magellan's. However there is also the new MG5075 which have built-in radio and is newer.
My question is : does PAI works with the new MG5075, if yes, is it stable ? I have the intention of using serial connection via usb ttl board.
If I understand correctly, the MG (and the MG5075 in particular) series can't use detectors on the bus, only extensions like keypad or zone extensions right ?

Thanks in advance

**Comment by yozik04** [comment]
Hi,
I have no idea how stable MG5075 is with PAI. Nobody added it to Compatibility list in wiki so far. Maybe it works, maybe not.

> If I understand correctly, the MG (and the MG5075 in particular) series can't use detectors on the bus, only extensions like keypad or zone extensions right ?

I am not an installer can not comment on that.

I recommend EVO. https://github.com/ParadoxAlarmInterface/pai/wiki/FAQ#which-panel-is-best-for-using-with-pai

**Comment by elclaudio** [comment]
thanks for your response. 
I don't know if you can tell me but, For the evo, if I connect a gprs/gsm communicator module like the PCS250G for sending sms, it appear to use the serial port, so I can't use PAI at the same time ?

**Comment by yozik04** [comment]
I know that people use ip150 with pcs250g

**Comment by luuuis** [comment]
MG5075 seems to work ok, configuration was the same as for other MG panels. Added to https://github.com/ParadoxAlarmInterface/pai/wiki/Compatibility

**Comment by yozik04** [comment]
Thank you!
