### ISSUE TITLE
Bypass Zones Home Assistant

### ISSUE THREAD

**Issue by weitheng** [ParadoxAlarmInterface/pai#226]
I am using the same configs as @MidnightZA, any idea why this is not working?

> 021-03-23 20:00:16,574 - INFO     - PAI.paradox.interfaces.mqtt.basic - message topic=paradox/control/zones/2_Kch___Laundry, payload=bypass
2021-03-23 20:00:16,577 - ERROR    - PAI.paradox.paradox - No zones selected
2021-03-23 20:00:16,578 - WARNING  - PAI.paradox.interfaces.mqtt.basic - Zone command refused: 2_Kch___Laundry=bypass user: None

This is my code:

> - platform: mqtt
  name: "Bypass Kitchen Laundry Alarm"
  command_topic: "paradox/control/zones/2_Kch___Laundry"
  state_topic: "paradox/states/zones/2_Kch___Laundry/bypassed"
  qos: 0
  optimistic: true
  state_on: "True"
  state_off: "False"
  payload_on: "bypass"
  payload_off: "clear_bypass"
  payload_available: "Online"
  payload_not_available: "Offline"

@yozik04 I tried adding `availability_topic: paradox/interface/availability`, but it says undetected, which is why I took the code off. But seems like it's doing its job, because it looks like it's not detecting it, which is why it doesn't work. 

![Screenshot 2021-03-23 at 12 07 15](https://user-images.githubusercontent.com/34220268/112143852-5aeef400-8bd0-11eb-8b85-2619ccc9a812.png)

Any help would be greatly appreciated.

_Originally posted by @weitheng in https://github.com/ParadoxAlarmInterface/pai/issues/215#issuecomment-804849272_

**Comment by weitheng** [comment]
Anyone can help with this?

**Comment by beerygaz** [comment]
This used to work in the dev version as it used to create the switches automatically.  I thought the new filters would let us select whether we wanted they bypass switches or not.  But either I'm getting the filter wrong or this is not the case.  

If I run the release version do I now need to manually create all my bypass switches?

**Comment by yozik04** [comment]
All info is available in the wiki: https://github.com/ParadoxAlarmInterface/pai/wiki/Home-Assistant-integration#add-more-properties-to-zones-or-partitions

Dev version is equal to stable version nowadays.
