### ISSUE TITLE
Support for IP150+

### ISSUE THREAD

**Issue by Gollam** [ParadoxAlarmInterface/pai#230]
## Alarm system
SP5500

## Question
I haven't found anything in the wiki or documentation about the recently released IP150+ module. It is an upgraded version of IP150. Do you know if it also should work with pai? Both IP150 and IP150+ is available for buying, but I'd like to know beforehand.

**Comment by remy-burney** [comment]
IP150+ module will also work with PAI.
I just got one with the latest firmware and it's all good with my alarm SP5500

**Comment by Gollam** [comment]
Thanks!
