### ISSUE TITLE
Bell status

### ISSUE THREAD

**Issue by proasnet** [ParadoxAlarmInterface/pai#232]
## Feature description
Hi, I like a PAI, now I am testing it without EPS32 with IP100 and working too. I need find a way for triggering some lights by Activated Bell, red flashing lights. But, I have not an event as active Bell. My system is EVOHD with IP100 and HA as HASSIO. Is possible integrate it please?
Thank you very much. Great work !!

**Comment by yozik04** [comment]
If something is in alarm it will have this flag set: `paradox/states/zones/Entrance_door/presently_in_alarm`

**Comment by yozik04** [comment]
And probably this: paradox/states/partitions/First_floor/audible_alarm

**Comment by yozik04** [comment]
I recommend you to make a screenshot in MQTT explorer for your partition before alarm. Then trigger an alarm, take another screenshot during alarm and compare.

BTW. Most probably paradox/states/partitions/First_floor/current_state fill be "triggered" during alarm.

**Comment by proasnet** [comment]
Okay. Thank you. I try it as soon as possible. How mqtt explorer I can use? Can be used explorer simultaneously with integrated mqtt server?

**Comment by yozik04** [comment]
MQTT is client. Same as HASS and PAI is.

**Comment by proasnet** [comment]
Oh, tested 1,5 year later :D. But working. Thank you very much, and happy christmas !!!
