### ISSUE TITLE
Issue in getting pai to work 

### ISSUE THREAD

**Issue by pisabell2** [ParadoxAlarmInterface/pai#233]
## Alarm system
EVO192 with an IP150 interface.

## Environment
Ubuntu running under Windows 10.

### Git branch
I used the command: git clone https://github.com/ParadoxAlarmInterface/pai.git

## Question
I followed the instructions on the git site and made minimal edits to /etc/pai/pai.conf. 

Running "run.sh" then resulted in an error message aboutvtrying to import a module called 'Embedded' (see the log). I don't know if this is an issue with my python installation or an issue about accessing the panel.

## Logs (if required)
#
[pai-log-encrypted.txt](https://github.com/ParadoxAlarmInterface/pai/files/6268114/pai-log-encrypted.txt)

Huge thanks in advance for your help!

**Comment by yozik04** [comment]
Hey. I am unable to decrypt your message. I do not think that error has any sensitive data in it

**Comment by pisabell2** [comment]
You are right: therevis nothing sensitive in there. I just followed the instructions posted on the site.
Here is an unencrypted version.
Thanks!
[PAI-log.txt](https://github.com/ParadoxAlarmInterface/pai/files/6271822/PAI-log.txt)

**Comment by yozik04** [comment]
construct is too new. They dropped `Embedded` in 2.10

**Comment by pisabell2** [comment]
Thanks a lot for the diagnostic!
Do you know what version I should use and how exactly I can revert to that
version?
Thanks again.


Le mer. 7 avr. 2021 à 11:04, Jevgeni Kiski ***@***.***> a
écrit :
