### ISSUE TITLE
Insecure secrets in e92a3241_paradox_alarm_interface

### ISSUE THREAD

**Issue by proasnet** [ParadoxAlarmInterface/pai#234]
## Alarm system
EVOHD 7.31

## Environment
RPI

## Git branch
hassio

## Describe the bug
```
Insecure secrets in
e92a3241_paradox_alarm_interface
```
This I have daily in HA messages. Do you know, please, what can I do with it?
I thought it was using passwords in the PAI configuration, so I used the password procedure in secrets.yaml, but this procedure didn't work and the PAI configuration didn't take references to secrets.

**Comment by proasnet** [comment]
SOLVED !!!
In addon must be secrets in 'abc'
For example:
IP_CONNECTION_PASSWORD: '!secret paradox'
PASSWORD: '!secret pin'
etc...

**Comment by proasnet** [comment]
So, after some days I get this message " Insecure secrets in e92a3241_paradox_alarm_interface " from home assistant again, now I have all secrets in secrets.yaml.
I have no idea where is a problem

**Comment by yozik04** [comment]
If you want to invest your time in it you can ask supervisor maintainers in discord how this "Insecure secrets" check is  working and ask them to log path of the config setting so human beings would be able to debug it.

**Comment by yozik04** [comment]
Here is where data is collected for checking for pwned passwords:
https://github.com/home-assistant/supervisor/blob/fd98d38125e0702ccdb15dd9f1ce2940d2811eb6/supervisor/addons/options.py#L140

Our addon only sets type `password` to `MQTT_PASSWORD` and `IP_INTERFACE_PASSWORD` attributes.
So if you set these to secure passwords it should not complain.

**Comment by proasnet** [comment]
Hello Jevgeni, thank you for interesting, on weekend I see on it. But, I
thing, why my instalation has problems with secrets? I have standard
hassios instalation, without any experiments, and I'm the only one who has
a problem with secrets, I am understand why.


st 5. 5. 2021 v 10:17 odesílatel Jevgeni Kiski ***@***.***>
napsal:

**Comment by yozik04** [comment]
you are not the only one.

**Comment by golddragon007** [comment]
As far as I see in the current 'new' version it's not possible to change it, or maybe only in that case if you are using inside gold. Secure your instance with the additional password.

**Comment by ipetrovits** [comment]
Hey there,

Got the same messages, ended up using this workaround:
[HA forums: Opt-out of pwned secrets warnings](https://community.home-assistant.io/t/opt-out-of-pwned-secrets-warnings/286394/241)

<details>
  <summary>If you're bored you can read my journey to this workaround</summary>

  Done this a few weeks ago, my memories can be a bit faded, and of course I did not want to replay the whole story on my house system :)
I moved my HA setup from docker+core to hass.io and started getting these messages as well. I tried to mitigate it by securing my Paradox passwords.
- I strengthened my IP150 module password which had no effect
_(in fact as I checked it directly in [HIBP](https://haveibeenpwned.com/), that password was compromised, so i was better this way..)_
- Added separate user/password for MQTT - no effect
- Moved both passwords into !secrets, no effect.
- Then i checked the config, and there was a 4 digit numeric PIN which is my SP6000 panel password. Moved that into !secrets, and as I remember, I got no further message about insecure PAI passwords, but got a new one about insecure passwords in !secrets.
_I don't know what can be added as this panel password, but BabyWare did not allow me to set it other than a 4 (maybe 5?) digit numeric._

As numeric passwords of a few digits are all compromised according to [HIBP](https://haveibeenpwned.com/), it won't matter I set it to.
Then I ended up in this forum where i found the workaround, and was able to disable [HIBP](https://haveibeenpwned.com/) checks. I found no whitelist option for this so far, which could be great as it is a very useful feature - imho.
[HA forums: Opt-out of pwned secrets warnings](https://community.home-assistant.io/t/opt-out-of-pwned-secrets-warnings/286394/241)
</details>

**Comment by yozik04** [comment]
I think I fixed it long time ago. Reopen if needed.
