### ISSUE TITLE
Trying to get it to work with Homekit

### ISSUE THREAD

**Issue by remirr** [ParadoxAlarmInterface/pai#236]
Hi there,

I am relatively new to this and am having some trouble getting this to work in Homekit via a Windows Homebridge. I have installed the Mqttthing and found your JSON which I have pasted below but the values are confusing to me. 

i.e. I do not have a First Floor etc.. What I have set up in insite Gold at the moment is the following:

Home Alarm - 1 Zone Open
That zone has three settings:
Disarm - Off
Stay - Perimiter door sensors armed
Sleep - Everything Armed except Upper Level
Arm - Whole house armed

I then have 25 odd sensors comprising of Door sensors and motion sensors. Ideally I would like to be able to add a button to Homekit that shows the current status of the Alarm and when I press it I can select which mode I would like. Is this possible or do I need to have 3 buttons for the three modes?

In addition, I am not sure what the Username and Password is since I just have the IP address and a 4 digit pin to get into the system. 

Thank you!

--------

{
            "accessory": "mqttthing",
            "type": "securitySystem",
            "name": "First floor",
            "url": "mqtt://<ip_address>",
            "username": "<username>",
            "password": "<password>",
            "topics": {
                "setTargetState": "paradox/control/partitions/First_floor",
                "getTargetState": "paradox/states/partitions/First_floor/target_state",
                "getCurrentState": "paradox/states/partitions/First_floor/current_state"
            },
            "currentStateValues": [
                "armed_home",
                "armed_away",
                "armed_night",
                "disarmed",
                "triggered"
            ],
            "targetStateValues": [
                "armed_home",
                "armed_away",
                "armed_night",
                "disarmed"
            ],
            "restrictTargetState": [ 1, 3 ]
}

**Comment by remirr** [comment]
Maybe @iondarie or @marcantoineveilleux are able to help :)

**Comment by iondarie** [comment]
Have you read trough the documentation of MQTTTHING?: [Security System](https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Accessories.md#security-system) / [Contact Sensor](https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Accessories.md#contact-sensor) / [Motion Sensor](https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Accessories.md#motion-sensor)

"First_floor" should be replaced with the name of your partition.

**Comment by remirr** [comment]
Hi @iondarie, 

I have, thank you although I am still a bit confused - I guess I just don't want to do anything wrong to then set off the alarm. So the alarm system was set up by the installer, I am not actually sure what the partitions are, is there a way for me to see this in the App or on the Panel? 

What do people normally setup in Homekit? Not just the three buttons for the three states but also add all the sensors?

Thank you!

**Comment by iondarie** [comment]
On the panel you should see the name of the partition for example: basement or first floor or second floor etc...

I have set up both my partitions for control and all of my motion sensors, but if you have window or door sensors you can add them to
