### ISSUE TITLE
MQTT TLS error

### ISSUE THREAD

**Issue by rjcds** [ParadoxAlarmInterface/pai#238]
## Alarm system
 EVO192 via IP150

## Environment
Docker

## Git branch
Initially dev-latest, but same error with stable latest

## Describe the bug
Unable to connect pai to add-on_core_mosquitto using TLS

Home Assistant on Docker, with add-on_core_mosquitto
I can successfully connect to Docker container for Home Assistant via https://hass.mydomain.com using Lets Encrypt 
I can successfully connect to add-on_core_mosquitto from another client using MQTT Explorer, 8883, SSL and hass.mydomain.com as address

pai fails with 
`WARNING  - PAI.paradox.interfaces.mqtt.core - Connection failed, retrying: Operation not permitted(1)`

add-on_core_mosquitto logs show
`OpenSSL Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca`

 
pai.conf
```
MQTT_HOST = 'hass.mydomain.com'
MQTT_PORT = 8883                        
MQTT_TLS_CERT_PATH = '/etc/pai/certs/fullchain.pem'
```

pai docker container is run with permissions admin:users (1024:100)
```
sudo docker exec -it CONTAINERID ls -lsa /etc/pai/certs
total 3
     0 drwxr-xr-x    1 root     root            38 May  1 20:33 .
     0 drwxr-xr-x    1 1024     users          106 May  1 20:30 ..
     4 -rwxr-xr-x    1 1024     users         3781 Apr 19 14:55 fullchain.pem
```

Not sure what the issue is, as both a client outside Docker and another Docker container can connect to the broker using TLS...

**Comment by rjcds** [comment]
Ok so the solution is (when using Lets Encrypt certs) to make MQTT_TLS_CERT_PATH point to a copy of the operating system's own .crt file (usually /etc/ssl/certs/ca-certificates.crt)

As per the [Note](https://www.home-assistant.io/docs/mqtt/broker#configuration-variables) in the HA MQTT setup page.

All working now !

**Comment by rjcds** [comment]
@yozik04 Done !

**Comment by yozik04** [comment]
Thank you!
