### ISSUE TITLE
HA OS Mosquitto 6.x addon does not accept publish messages

### ISSUE THREAD

**Issue by chriscc12345** [ParadoxAlarmInterface/pai#242]
### Alarm system
EVOHD, Magellan MG5050 via IP150

### Environment
raspberrypi4-64
hassos 5.13
Home Assistant 2021.5.5

### Git branch
Prod and Dev

### Description:
Mosquitto 6.x addon does not accept publish messages from PAI.

**Comment by chriscc12345** [comment]
2021-05-20 19:21:15,163 - ERROR    - PAI.paradox.hardware.spectra_magellan.panel - ChecksumError Error in path (parsing) -> checksum
wrong checksum, read b'00', computed b'2e', message: b'0080000810000000141505141314cf99966e0000000000000000000000000000000001c000'

**Comment by Giulll** [comment]
My system also has the same problem, HA detects the system as armed in every condition is the paradox and no longer accepts commands. Magellan 5050 and IP150. I am no longer receiving status from PIR sensors and no true errors in the PAI log.
No change was made in the configuration.

Many thanks

**Comment by ivankarpov** [comment]
Same here, the problem starts with auto-update Mosquitto broker to version 6.0.1 for HA. As I can see only possible related change in the mosquitto is disabling the anonymous access. I have created a HA user for MQTT and I used that user/pass in PAI without success. ( login confirmed with MQTT explorer ). 

After the update there is no MQTT message from PAI ( homeassistant autodiscovery topic included )  

Also I've tried to remove/reinstall the PAI - it is not helping

**Comment by Gunth** [comment]
I can confirm that it is related to the Mosquitto update, revert back Mosquitto to 5.1.1 work again with the same configuration of PAI.

**Comment by CorneDuPlooy** [comment]
@Gunth , how do you revert back to 5.1.1? I cannot find any docs on rolling back an addon. Thanks.

**Comment by Gunth** [comment]
When i upgrade the Mosquitto addon i have made a backup of the addon before so i revert it to the previous version with the backup.
I don't know if there is other way to revert back ...

**Comment by CorneDuPlooy** [comment]
Ok thanks... Crap, mine was set to auto update...

**Comment by yozik04** [comment]
Issue in HA home-assistant/addons/issues/2020

**Comment by yozik04** [comment]
Fix is in 2.5.3
