### ISSUE TITLE
integration not work after Home Asistant update

### ISSUE THREAD

**Issue by danygi79** [ParadoxAlarmInterface/pai#244]
## Alarm system
EVOHD

## Environment
- HASSIO over Proxmox

## Git branch
master

## Describe the bug
not work after upgrade home assitant from 2021.5.2 to 2021.5.3

## To Reproduce
no step, only home assistan update

[log.txt](https://github.com/ParadoxAlarmInterface/pai/files/6519021/log.txt)

**Comment by yozik04** [comment]
dupe of #242
