### ISSUE TITLE
Interface not working 

### ISSUE THREAD

**Issue by JINXz** [ParadoxAlarmInterface/pai#245]
**Alarm system**
Magellan MG5050 via IP150

**Environment**
raspberrypi4-64
hassos 5.13
Home Assistant 2021.5.5

**Python version**

**Git branch**
Prod and Dev

**Describe the bug**
Interface just doesn't work

ERROR    - PAI.paradox.lib.handlers - No handler for message 5

**To Reproduce**

[keybase.txt](https://github.com/ParadoxAlarmInterface/pai/files/6520341/keybase.txt)

**Comment by yozik04** [comment]
dupe of #242
