### ISSUE TITLE
Swan Setup

### ISSUE THREAD

**Issue by chriscc12345** [ParadoxAlarmInterface/pai#246]
Good Day,

Would like to find out if you can assist me with configuring my PAI with swan configuration.

I also keep getting this message on HA

Insecure secrets in e92a3241_paradox_alarm_interface
The add-on e92a3241_paradox_alarm_interface uses secrets which are detected as not secure, see https://www.home-assistant.io/more-info/pwned-passwords for more information.

**Comment by yozik04** [comment]
Do not use SWAN. Use local connection.

**Comment by chriscc12345** [comment]
my ip150 can no longer connect with local
