### ISSUE TITLE
Change Status Labels

### ISSUE THREAD

**Issue by remirr** [ParadoxAlarmInterface/pai#248]
Is there a way to change the labels used by PAI? 

So our Paradox alarm has three states
- Armed - Everything Armed
- Stay - Perimiter Armed
- Sleep - 1st Floor Armed - 2nd not armed. 

These do not line up with the PAI states which are 
- Armed Home = Stay
- Armed Away = Armed
- Armed Night = Sleep

Either I want to be able to change the Paradox terms in Babyware or the terms in PAI, is this possible? 
i.e.
- Armed Whole House
- Armed Sleep (1st Floor)
- Armed At Home (Perimeter)

Thanks

<img width="360" alt="Screen Shot 2021-06-09 at 18 35 12" src="https://user-images.githubusercontent.com/2309583/121438509-1f073780-c952-11eb-8fab-8d861a63a1b2.png">

**Comment by yozik04** [comment]
Where you want to change these labels in HomeAssistant?

**Comment by remirr** [comment]
Ideally I want to change how they show up on both the Alarm Panel and in HA (I have access to Babyware but am not sure how to do it). If that is going to be to hard, then I just want to rename the labels in HA on the Alarm Card. 

Perhaps you have a suggestion on which is the best / easiest way?

**Comment by yozik04** [comment]
Then I do not understand. You can rename partitions in babyware. But above you were talking about renaming actions.
What do you actually want?

**Comment by remirr** [comment]
Sorry for the confusion. 

**If I want the Card in HA to say:**
- Armed Whole House
- Armed Sleep (1st Floor)
- Armed At Home (Perimeter)

- How and where do I do that?

**Comment by iondarie** [comment]
@remirr unfortunately I don't think that you will be able to do that...

**Comment by remirr** [comment]
There is no way to change the labels that show up on the card in HA? In this case, is there a way to change the labels in Babyware so they come through differently?

**Comment by yozik04** [comment]
Make a new template sensor and replace values as you want. How to do that? You need to ask that in homeassistant community.
In Babyware or using keypad you can change partition names.

**Comment by remirr** [comment]
Would you have a link to the template? I have spent a few hours looking but can't seem to find it...

Also, how do I add the keypad so that a code is required to arm and disarm?

**Comment by yozik04** [comment]
Code: https://github.com/ParadoxAlarmInterface/pai/wiki/Home-Assistant-integration#make-home-assistant-to-ask-for-a-code-to-armdisarm-dev-branch

Regarding template I know it is possible but how to implement I am unable to help.

**Comment by remirr** [comment]
@yozik04 Thanks for this but I don't seem to get the arm option under customizations
![Screen Shot 2021-06-19 at 16 12 34](https://user-images.githubusercontent.com/2309583/122654419-3942d180-d119-11eb-906a-5d9f27bb4b18.png)
