### ISSUE TITLE
IP150+ Web interface doesn't allow configuration

### ISSUE THREAD

**Issue by abeldacosta33450** [ParadoxAlarmInterface/pai#253]
EVO48
FW : 2.16

IP Module (150+)
FW : 5.02.19
HW : 020
ECO : T067

When i log into the web interface, i have the following in Main Menu
. Receiver Configuration (grey - not accessible)
. System Information
. IP150+ Configuration (grey - not accessible)
. Email Configuration (grey - not accessible)
. Event Log

Can someone explain me how i can activate or access the menus i can access or see ?
If i need to upgrade the system, what is the method of procedure ?
Many thanks
Regards

**Comment by abeldacosta33450** [comment]
![Capture d’écran, le 2021-06-28 à 12 26 53](https://user-images.githubusercontent.com/86601144/123635091-8ad71480-d81b-11eb-96a8-2e9a04ffe3b8.png)

**Comment by yozik04** [comment]
Is PAI connected?

**Comment by abeldacosta33450** [comment]
From what i can see, PAI is a middleware which helps connecting the IP150 module with applications like MQTT. 
I'm on Apple MACOS (may use IOS too). Can you please point to a page where i can download compatible SW ?

**Comment by yozik04** [comment]
You are right.
You will not be able to run InField on Mac. Setup a VirtualBox with Windows or something. Where to download firmware? Better ask in gitter.

**Comment by abeldacosta33450** [comment]
Yes, i did that actually to run Babyware and Winload. With Winload, i managed to connect to the IP150+ but i can't configure anything useful with regards to notications and being able to remotely power on/power off the alarm.
So, i understand you recommend me using InField. i'll give it a try
Thanks

**Comment by abeldacosta33450** [comment]
Looks like InField is an application for upgrading Paradox component. What shall i upgrade ?

**Comment by yozik04** [comment]
your EVO48 fw.

**Comment by abeldacosta33450** [comment]
ah ok... What version shall i target ? any risk to render the system unoperational ?

**Comment by yozik04** [comment]
latest you can find. Do not think so.

**Comment by abeldacosta33450** [comment]
I've installed InField 4.26.4 but it complains about EVO48 not being known (and yes, i can't find it in the product list so it makes sense). will try an older InField version

**Comment by abeldacosta33450** [comment]
OK i've managed to connect using the latest InField version BUT i can't find any upgrade PUF file for the EVO48

**Comment by abeldacosta33450** [comment]
![Capture d’écran, le 2021-06-29 à 17 14 50](https://user-images.githubusercontent.com/86601144/123823859-d7931c00-d8fd-11eb-941e-9e0fe09076c3.png)

**Comment by abeldacosta33450** [comment]
Can someone point me to a link where i can fetch the PUF file ?

**Comment by abeldacosta33450** [comment]
@iondarie yes, you were right. Managed to find the master code and the rest of the menus showed up.

**Comment by abeldacosta33450** [comment]
thanks all

**Comment by abeldacosta33450** [comment]
@yozik04 @iondarie Shall i try to downgrade the IP150+ module from 5.02 to <4.xx ? or this won't help ?
Thanks

**Comment by yozik04** [comment]
@abeldacosta33450 it will auto upgrade again. What was in System Status? If you are talking about zone/partition statuses I think Paradox has removed that menu in 4.x firmware when they switched to Insite Gold.

**Comment by abeldacosta33450** [comment]
@yozik04 I can block to the connections used for the auto-update...

**Comment by abeldacosta33450** [comment]
![Capture d’écran, le 2021-07-08 à 13 36 30](https://user-images.githubusercontent.com/86601144/124915194-8d8ef200-dff1-11eb-90ae-02216599c8c1.png)

**Comment by abeldacosta33450** [comment]
here is the SYS INFO menu

**Comment by abeldacosta33450** [comment]
So, if i read you correctly, Paradox intentionally disabled the menu... So, indeed, only way is downgrade and block connections

**Comment by iondarie** [comment]
You need to be logged in. as System Master for all the menu's to be available. (screenshot was taken at the time of this reply)

<img width="1172" alt="Screenshot 2021-07-09 at 19 59 56" src="https://user-images.githubusercontent.com/9055885/125112769-48051e80-e0f0-11eb-90e5-e594595b9cdd.png">

**Comment by abeldacosta33450** [comment]
Thanks @iondarie !
