### ISSUE TITLE
Reporting IP and IP module trouble?

### ISSUE THREAD

**Issue by golddragon007** [ParadoxAlarmInterface/pai#256]
## Alarm system
Magellan MG5050 with IP150+ module

## Environment
RPI4

### Git branch
2.7.1

## Question
When I log in to the IP150 module I see that I can set reporting IPs there. My question if this integration can work with it or it's planned to work with it.
I see also one trouble that I don't know how to solve it right now, "IP module no service". I've placed the IP module to a network that has no internet connection, I hope not that's its problem... If anybody knows what ports/ips this needs to be freed to make it quiet, it would be nice.

**Comment by yozik04** [comment]
I think this error just tells you that IP150 is not registered to security company or can not connect to security company server. If you disable internet for that then you won't be able to get rid of that "trouble".

**Comment by golddragon007** [comment]
Currently, I'm not sure about that, as if I set an IP for the reporting WAN1 or WAN2 I will get an unregistered error. I think this is not registered to a security company, while the other one is just an internet connection check like Windows or Linux does to check if there is an internet connection.
