### ISSUE TITLE
arming code and existing user

### ISSUE THREAD

**Issue by loop2** [ParadoxAlarmInterface/pai#260]
## Alarm system
EVO192+ IP150

## Environment
HASSIO OS
Paradox Alarm Interface: Current version: 2.7.1

## Question
When I arm/disarm my alarm system from Hassio the paradox Insite Gold app show me the notification of arm/disarm by Unknown user... is possible to connect the activation to an existing user?

Another question... when i add in lovelace the alarm panel there is not request of code... how i can add it?
Thanks a lot!

**Comment by loop2** [comment]
None can help me?

**Comment by yozik04** [comment]
It is not possible to help you as PAI arms your system using System User. It is not tied to any user in your alarm.

**Comment by yozik04** [comment]
Regarding adding code to lovelace. Try this setting in PAI `MQTT_HOMEASSISTANT_CODE: '123456'`. I do not remember if I merged that to stable branch already.

**Comment by loop2** [comment]
Thanks for the answer! The strange thing is that sometimes i receive the notification from paradox that the alarm was inserted from ALESSANDRO e sometimes from UNKNOWN... this is strange because as you says there is not tied to any user in my alarm.

For the arming code is tried to add MQTT_HOMEASSISTANT_CODE: '1234' in all three branches but in the lovelace card i haven't the code keyboard.
Thanks

**Comment by loop2** [comment]
I would the code because i can activate the alarm via alexa without code from my bed (distant from alarm keyboard) but i don't want that someone says "disarm" to disable my alarm! :-)

**Comment by yozik04** [comment]
When you receive unknown then PAI has armed/disarmed the system. When you arm from keypad you will receive real user name.

**Comment by loop2** [comment]
From about a week I'm using only the PAI via HASSIO but i receive the notification from paradox that the alarm was inserted from ALESSANDRO e sometimes from UNKNOWN. I don't using more keyboard or paradox insight app....
It's strange!

**Comment by loop2** [comment]
From about a week I'm using only the PAI via HASSIO but i receive the notification from paradox that the alarm was inserted from ALESSANDRO e sometimes from UNKNOWN. I don't using more keyboard or paradox insight app....
It's strange!

**Comment by loop2** [comment]
I can confirm that adding MQTT_HOMEASSISTANT_CODE: '1234' i haven't the pinpad on the HA frontend...
Another question on the arming... from my paradox keyboard, i there are some zones or sensors open i can "forse" the arming without this open sensors and when the sensors become closed, also they are armed...
Is possible to have this also? If i try to arm with an open zone start the siren...

**Comment by loop2** [comment]
I have tried with both stable and dev versions...
but after added MQTT_HOMEASSISTANT_CODE: '123456' i have to do anything else?

In the wiki i can read this:

Goto Configuration -> Customizations.
Find your alarm_control_panel partition.
Check code_arm_required and code_disarm_required.
Now you need to enter the code to disarm and arm.

I don't know where i must check code_arm_rquired...

thanks a lot!
