### ISSUE TITLE
Battery sensor missing for my wireless alarm sensors'

### ISSUE THREAD

**Issue by golddragon007** [ParadoxAlarmInterface/pai#262]
## Alarm system
MG5050 IP150+ (?) module

## Environment
HA integration

### Git branch
Current version: 2.7.1

## Question
I can't find my wireless sensors' battery state anywhere. How will I know when one of my batteries running low? (I would like to write a warning notification in my automation to see these batteries and get notified)

## Logs (if required)
-

**Comment by jpbarraca** [comment]
The panel will issue a trouble associated with that zone, which can be sent to the notification channel in use. A binary sensor is also created (...rf_low_battery_trouble)
However, I observed that sometimes the sensor will start behaving strangely (tamper alarms, no detection) before the trouble is issued.

**Comment by yozik04** [comment]
Required data is in MQTT. Open MQTT Explorer and lookup. You can create custom mqtt sensors/binary_sensors in home assistant.

**Comment by golddragon007** [comment]
OK, so there is a lot of information there, but the integration does not make by default for them an entity in HA. Which was unexpected for me, as something was picked up automatically.

One more question, which may not relate too much here, but can I trigger different alarm types also? I.e. like if a fire alarm sensor detected something and triggers the fire alarm type? is it done also with MQTT?

**Comment by yozik04** [comment]
@golddragon007 If you go `dev` version then HA automatically detects every available parameter that PAI can export. But it is creepy. For my 21 zone setup I have 612 topics. Which means ~612 sensors. Do you want that in HA? HA can still handle that load but really. When you try to setup automation this large amount of extra sensors makes it hard to find required entities. How valuable are these extra sensors for a common user?

There should be a topic in mqtt which can indicate what alarm was triggered. I think. At least there was something for EVO.

**Comment by golddragon007** [comment]
@yozik04 I don't see your problem. I have currently 600 sensors, some of them not available some of them ~400 disabled in HA. Disabled sensors are not available in the dropdown lists. Nor in development nor in automation. I did not say all should be enabled by default. But all can connect to a device i.e. all zone is a device and then all zone has multiple sensors, some of them enabled by default. Like motion sensors. Some of them are disabled by default like radio link quality. Then the user can turn in and off with one click whatever sensors he needs without starting configuring 21+ sensors one by one. On top of that, a sensor can have attributes too. So some values can go as attributes instead of a separate sensor.

I want to trigger the fire alarm if my Zigbee fire alarm detector detected smoke. But I don't know yet if it's possible to trigger such or just the alarm muting possible.

**Comment by yozik04** [comment]
Attributes and/or proper home assistant integration are for version 3.0.0+. If time will ever come.
I personally do not like 600 sensors in home assistant and do not want spend time disabling that. If a person needs a special thing then he can always configure it manually.

**Comment by golddragon007** [comment]
Amm where can I find the low battery trouble for the wireless siren?

**Comment by Dyltong** [comment]
I have built a bit of a workaround solution to this. Basically a persistent notification that comes each night, indicating zones that haven't triggered for 7 days. This indicates zones that may be out of battery:

Involves creating a new sensor, and an automation (just need to replace your sensor names).

[https://github.com/Dyltong/pai_battery_notification_ha](url)
