### ISSUE TITLE
Software currently connected

### ISSUE THREAD

**Issue by LudoARN** [ParadoxAlarmInterface/pai#263]
Hi,

I use Paradox Alarm Interface with Home Assistant and it works great.
But now, i can only have one active user on my alarm system : this add-on. I can't use neither the web interface, nor Insite Gold on my phone.

If i stop the PAI module, i can use web Interface and Insite Gold with my phone, and my wife's phone.
Can you help me ?

![image](https://user-images.githubusercontent.com/81586322/134779823-18d615cf-a6e3-4f2e-90f4-89c625961ffd.png)

![image](https://user-images.githubusercontent.com/81586322/134779890-c321b9ad-f2a3-4f60-bc6b-2b60202f492f.png)

**Comment by yozik04** [comment]
We won't be able to help you. This addon is meant to replace Insite Gold. Only one connection is possible at a time. PAI or Insite Gold. Pick your poison.

**Comment by chriscc12345** [comment]
So why can multiple devices access the alarm via Gold at same time, there should be a way around this, is it not because of the panel user pin thats used

**Comment by yozik04** [comment]
Insite Gold uses another different protocol which of course has zero documentation available. We use Babyware protocol and it was a large effort to make it work. If somebody wants to reverse engineer also the Insite Gold protocol please feel free. We will all benefit from it. I can not guarantee that it supports all features we have.

**Comment by chriscc12345** [comment]
I spoke with one of there tech's today, said that once port 10000 is used the system shutsdown all other users from accessing.

he said the default port for swan is 3478 and the internal port can be anything like 60229. maybe that can help.

**Comment by chriscc12345** [comment]
I have made contact with paradox lets see if something can happen.
![Uploading Screenshot_20211110-081750_Outlook.jpg…]()
