### ISSUE TITLE
Encrypted uart even using 307usb?

### ISSUE THREAD

**Issue by mgx0** [ParadoxAlarmInterface/pai#265]
Hi there

i have an evo192 board with firmware that encrypts serial. Does 307USB cable help? Or does the uart traffic come out from this cable as encrypted?

i can buy 307USB quite cheap if I can see the decrypted uart traffic but there is literally no information on this topic. 

Or is the IP150 module help to control the board?

Can anybody suggest something?

**Comment by yozik04** [comment]
We have zero information on that so can not comment

**Comment by mgx0** [comment]
Thought so. Thanks for the reply anyway

**Comment by aelias-eu** [comment]
The 307USB is just a USB / RS232 / TTY converter. It doesn't encrypt/decrypt anything.

**Comment by mgx0** [comment]
Yes thanks, i understood how it is working in the meantime. Using pl2302 usb to serial for weeks now, it just needs a compatible thing on the other end (ip150, babyware etc) that talks encrypted serial
