### ISSUE TITLE
IP connection blocks reporting?

### ISSUE THREAD

**Issue by golddragon007** [ParadoxAlarmInterface/pai#267]
## Alarm system
Paradox MG5050 + IP150+

## Environment
RPI

### Git branch
2.7.1

## Question
Can it happen that the PAI IP connection blocks the reporting of the alarm to the alarm centre? I know if the PAI connected, I can't go in with babyware, nor by installer or master code to any programming menu. Or did I do something wrong config?

**Comment by yozik04** [comment]
Reporting of the alarm to the alarm centre: This should not happen.
The rest: Only one connection at a time. This is IP150 module limitation.

**Comment by yozik04** [comment]
Dupe of #263
