### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by dreampost** [ParadoxAlarmInterface/pai#269]
I am using a Paradox IP150+ IP module. Firmware version is 5.02.19.
The panel password is something I could never change, so I assume it's the default: paradox.
I installed Paradox Alarm Interface (Second Instance) from the HASSIO repo. It cannot connect to the panel: authentication failed.
The configuration:

![image](https://user-images.githubusercontent.com/17015454/144466317-80ffcbc8-f157-4db4-9811-66d830a0a437.png)

![image](https://user-images.githubusercontent.com/17015454/144466472-14af7f6b-9b35-45cd-be23-0e6807d337e1.png)

And the logs:
![image](https://user-images.githubusercontent.com/17015454/144466718-3fe5e79d-6878-4845-be80-d7ca221d3e90.png)

**Comment by yozik04** [comment]
PASSWORD: ‘5004’ is wrong Jevgeni From: dreampostSent: Thursday, December 2, 2021 18:52To: ParadoxAlarmInterface/paiCc: SubscribedSubject: [ParadoxAlarmInterface/pai] Authentication failed (Issue #269) I am using a Paradox IP150+ IP module. Firmware version is 5.02.19.The panel password is something I could never change, so I assume it's the default: paradox.I installed Paradox Alarm Interface (Second Instance) from the HASSIO repo. It cannot connect to the panel: authentication failed.The configuration:And the logs:—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dreampost** [comment]
Which password is that supposed to be?
Thanks.

**Comment by dreampost** [comment]
Hmm, I tried out something and now I got this:
![image](https://user-images.githubusercontent.com/17015454/144508984-f644cc8b-0873-4538-886e-18864f3a2780.png)

**Comment by yozik04** [comment]
Wrong password :)
Read configutation part in wiki first please. It has a lot of valuable information.

**Comment by dreampost** [comment]
Well, I did read it several times. It is not clear which password is bad if the error message above also displays "Authentication success. IP (114) Module.
Is it like the panel password is bad?
If I get it bad, then it is displayed clearly: Bad panel password

![image](https://user-images.githubusercontent.com/17015454/144591542-0b60e1b5-f3a5-434c-a950-865a685c55a2.png)

If I out let's say '0000' - like mentioned in the guide - I get this:

![image](https://user-images.githubusercontent.com/17015454/144591850-de6e72aa-da16-47a2-b5c3-ea30f204ec6e.png)

Let me also mention that I cannot connect with any of Babyware or Winload: both apps say that I have got a wrong panel ID..

**Comment by yozik04** [comment]
![image](https://user-images.githubusercontent.com/2420038/144601289-99696d86-4389-4800-ac1a-31f59a8d93c4.png)
From your screenshot

**Comment by yozik04** [comment]
It clearly states it wants PC Password.
Authentication success is to your IP150 module. This is first auth.
Second Auth is PC Password.
Not a user/master or installer password.

If panel ID is changed then most probably PC Password as well.
PAI does not require you to specify Panel ID. It figures it out itself.

**Comment by dreampost** [comment]
ok, got.. I just called the guy who has set up my Paradox back in time. With his help we went into the console and specified Panel ID and Panel Password on the panel itself.
I used those values in Winload and it managed to connect and pull down the full config.
I've inserted that numer in the following format '0000' (instead of zeros using the real number) and I still get authentication issue.
So what should definitely be accurate now: the IP password and the panel code, as those values work in Winload.
![image](https://user-images.githubusercontent.com/17015454/144606774-fd4294dd-c88f-4e04-9c8c-43624ac09a3f.png)


The error:
![image](https://user-images.githubusercontent.com/17015454/144606940-7557b300-04e7-48bb-94f7-181edbc66835.png)

**Comment by dreampost** [comment]
Winload config:
![image](https://user-images.githubusercontent.com/17015454/144607200-d7db229d-ba8a-4324-9795-b872bb740c49.png)

![image](https://user-images.githubusercontent.com/17015454/144607281-b4fda2af-38c0-4300-b725-69300088fb4d.png)

![image](https://user-images.githubusercontent.com/17015454/144607631-d6e27bd4-4b6b-4ceb-b786-499cfb6e9341.png)

**Comment by yozik04** [comment]
Let's refer to the wiki: https://github.com/ParadoxAlarmInterface/pai/wiki/FAQ#authentication-failed-wrong-password

**Comment by yozik04** [comment]
I never used Winload so I can not guarantee that it connects the same way.

**Comment by dreampost** [comment]
> Let's refer to the wiki: https://github.com/ParadoxAlarmInterface/pai/wiki/FAQ#authentication-failed-wrong-password

oh man.. problem fixed.. I read the doc several times by now, but somehow I skipped this line:
"if your password has 0 try to replace it with a. Some panels want 0 encoded this way. 0306 -> a3a6"

This was it, now it works.

**Comment by yozik04** [comment]
=) I am glad you fixed it!
