### ISSUE TITLE
Wrong information on README? (It *is* working with EVO 7.50+)

### ISSUE THREAD

**Issue by fdcastel** [ParadoxAlarmInterface/pai#272]
## Alarm system
**EVO 192 256K (DIGIPLEX)**
Firmware 7.52.001
Bootloader 1.00.015

**IP150**
Firmware 1.34.000
Bootloader 2.12.001

**BabyWare 5.4.26**
_Information from In-Field Paradox Upgrade Software._

## Describe the bug
The README of project warns:

**Do not upgrade EVO firmware versions to 7.50.000+. Process is irreversible! Paradox introduces serial communication encryption which most probably will break our PAI ability to talk to the panel.**

However, I got myself a new EVO 192 panel which came with 7.52.001. **And PAI is working fine with it.** (I'm using via home assistant).

Has anybody more information about this? It seems clearly misleading or incomplete. 

What I discovered, so far:

The [firmware changelog](https://www.paradox.com/DotNetApp/FirmwareUpdate/FirmwareUpdate.aspx?SUBCATID=68&group_id=5) available on paradox site indeed says:

```
V7.50.011(released on April 21, 2021)
Firmware Download
V7.50.011

What's new
- Added serial port encryption - the serial output will be operational only with Paradox devices (IP150/+, PCS250/260/265/265LTE, USB307)
- Added serial port unlock license key for 3rd party communication devices ( license can be purchased from Insite Gold Installer Menu)
- The unlock license key needs to be entered in keypad programming only, section 3000 – (Only TM50/TM70 keypads can be used - A-Z characters needed)
- Panel programming is compatible with BabyWare 5.4.26 version and up
- This firmware version cannot be downgraded
```

But, as I said, it is working. 

Maybe it is working because my IP150 is running a VERY old firmware version? (pre-2016)

Sadly, the [IP150 firmware changelog](https://www.paradox.com/DotNetApp/FirmwareUpdate/FirmwareUpdate.aspx?SUBCATID=38&group_id=64) doesn't mention anything about cryptographic communications. So, I don't know what would be a "safe" version to upgrade it.

I'm using it on a test panel (not in production) with almost all default values (did a hard reset) except for users/zones/areas.

**Comment by yozik04** [comment]
Oh WOW! As none of us tried that new FW version with serial encryption yet we had to warn everybody as it sounded like a breaking change.
I will add your FW versions to our wiki's compatibility list.

Thank you for the great news.

**Comment by fdcastel** [comment]
Could anybody please report what version of IP150 firmware are you using? 

_(one which reportedly is working fine with PAI, of course)_ 😉

I'm asking this because I'm running a very old version (v1.34) and would like to upgrade to at least something newer.

**Comment by yozik04** [comment]
@fdcastel Please check compatibility wiki page.
You are lucky one to have 1.34 IP150 fw. People pull their hair our how to get that. 3.x+ adds only Insite Gold related functionality which is not possible to use if you want to use PAI. I, personally, will sit on 1.34 forever :) as it works great.

**Comment by fdcastel** [comment]
Understood. Thank you very much @yozik04 😄 

> @fdcastel Please check compatibility wiki page. 

https://github.com/ParadoxAlarmInterface/pai/wiki/Compatibility

My fault. I missed this one entirely 😢

**Comment by Beylie** [comment]
I'm running IP150 (FW V5.02.045) and EVO192 256K (FW V7.52.001) with PAI and have zero problems so far (about a 2 weeks now). Using direct connection to IP150.

**Comment by pedroandrade1977** [comment]
> I'm running IP150 (FW V5.02.045) and EVO192 256K (FW V7.52.001) with PAI and have zero problems so far (about a 2 weeks now). Using direct connection to IP150.

Hi are you using also Insite Gold ? Does PAI work for you when using this?

**Comment by Beylie** [comment]
I've discontinued use of Insite Gold and only use PAI. But from what I remember, Insite Gold alerted on arming /disarming/alarm, but I could not log into it unless PAI was stopped.


________________________________
