### ISSUE TITLE
Is there a way to get the indication of a general TBL status ?

### ISSUE THREAD

**Issue by yyy35yyy** [ParadoxAlarmInterface/pai#275]
## Alarm system

Magellan MG5050), access mode IP150

## Question
There is a a pushbutton on the keypad called TBL. It flashes red if there is any kind of failure in the system (the system also puts out an annoying beep sound). Is there a way to get this general failure indication through MQTT ?
In addition - to stop the beeping you need to press the TBL pushbuttons - is there a way to do that through MQTT command ?

Thanks

**Comment by jpbarraca** [comment]
No. I would recommend using Babyware to clear the error or remove the beep.
