### ISSUE TITLE
Trigger fire alarm from HA

### ISSUE THREAD

**Issue by golddragon007** [ParadoxAlarmInterface/pai#278]
## Alarm system
MG5050, IP150+

## Environment
RPI 4

### Git branch
2.7.1

## Question
Is there a way to trigger a normal fire alarm (not panic) from HA?
Does the "Alarm Control Panel: Trigger" service do this with some special parameters? Or it's fully unsupported currently?

**Comment by yozik04** [comment]
Fully unsupported. Use PGM wired to a zone to trigger alarms.
