### ISSUE TITLE
Conflict between master and second instance

### ISSUE THREAD

**Issue by DjBac** [ParadoxAlarmInterface/pai#281]
Alarm systems: SP7000 SP5500 on RPI.

The dev branch although connects to the panel, does not publish anything to mqtt.

I connect on the main dist the SP7000 and then I see on my MQTT devices the alarm panel.
I connect on the second instance the SP5000 and then on the MQTT devices the SP7000 gets replaced with the SP5000 and their zones and areas are combined.
I can see two different mqtt topics, for example:
homeassistant/sensor/28110bfc/pai_status/config
homeassistant/sensor/2a0384a6/pai_status/config

If I disable mqtt autodiscovery on one panel, then nothing is parsed to the mqtt explorer.

but they both refer to the same topic: "state_topic": "paradox/interface/pai_status"

What would be the best solution to get two different alarm panels to appear as two different devices?
There are two areas on both panels and they are named the same. If I change the areas' names, would it make a difference?

**Comment by yozik04** [comment]
Resolved in 3.0.0
