### ISSUE TITLE
Serial connector

### ISSUE THREAD

**Issue by lpaolini** [ParadoxAlarmInterface/pai#282]
In the [wiki](https://github.com/ParadoxAlarmInterface/pai/wiki/Connection-methods#paradox-serial-connector-on-the-board) it says "Paradox serial connector on the board" but I'm not sure if it refers to the socket or the connector view.

```
┌───────┐
│ Rx   ┌╵
│ Tx   │
│ GND  │
│ AUX+ └╷
└───────┘
```

Looking at the following photo of the Paradox serial interface it looks like it's the connector view, assuming red is AUX, black is GND, etc.

Can someone please clarify? Thanks!

![serial](https://user-images.githubusercontent.com/377807/154450925-6c05c70e-fede-455c-9d34-7ee8064d789e.png)

**Comment by yozik04** [comment]
If you look on the connector from bottom up. White is Rx, Green - Tx, Black - GND, Red - AUX+. So does wiki show you. =)
But I always recommend do check with voltmeter. GND+ and AUX will show 12V.

**Comment by yozik04** [comment]
Actually good picture. Probably need to put that to the wiki for better understanding.

**Comment by yozik04** [comment]
Taking my words back. I have the opposite to your picture.

**Comment by lpaolini** [comment]
Wow, so what's the actual pinout, looking at the panel's connector?

**Comment by yozik04** [comment]
![image](https://user-images.githubusercontent.com/2420038/154465479-4822e1e8-f90b-40bc-9e0f-1dac605167a5.png)

**Comment by yozik04** [comment]
This is my custom made connector and I am sure Black is GND and Red is 12V, because I power other module from it.
So I still recommend to verify with Voltmeter. Maybe that paradox one is smart and can detect AUX and rotate pins as required.

**Comment by lpaolini** [comment]
This is weird. I could not find any image of the Paradox serial cable with a different pinout than that in my image... 
I'm very confused. I doubt Paradox can have reversed the pinout from one model to the next one. That'd be crazy!

**Comment by yozik04** [comment]
=) I think Paradox was not the inventor of MG or EVO. Protocols are also very different. Can be that they bought a company with a different hardware design
