### ISSUE TITLE
Real time door status in place of a 10s cycle

### ISSUE THREAD

**Issue by Benoit3** [ParadoxAlarmInterface/pai#285]
Hello,

first I thank you for this very easy to use Paradox Alarm Interface. I use it with an evo192 and an IP100 IP interface.

Before using it I had a PRT3 interface and basic python scripts [Paradox2MQTT](https://github.com/Benoit3/Paradox2MQTT/blob/main/README.md).

The feature level was several steps below, except on one point:
- zones status were reported immediately (not after a time between 0->10s) through PRT3 event analysis which allowed to do  asynchronous zone/partitition status request

It is very usefull if you want for example switch on a light when a zone becomes open : you don't need to wait for a variable time between 0 and 10s ?

Is there a solution to achieve that ?

Regards and thank you for your work,
Benoit

**Comment by yozik04** [comment]
Hey. https://github.com/ParadoxAlarmInterface/pai/wiki/Configuration#pai-side Performance section

**Comment by Benoit3** [comment]
Thanks a lot, it's working perfectly.
Sorry to no have read it in the wiki.
Regards,
Benoit
