### ISSUE TITLE
Pgm 5 on board relay

### ISSUE THREAD

**Issue by tasosstr** [ParadoxAlarmInterface/pai#292]
## Alarm system
Check on SP6000 and SP7000

## Question
Hello I would like to ask if there is any option for make active the PGM 5 the on board relay, to send a MQTT command for activated.

What I see on paradox/states/outputs/Output_01 and Output_02 and Output_13 and Output_14  can send on or off and I can see they change the status, but if I was write for Output_05 nothing happens.

I went to babyware and I can control it for on and off. 

On Pgm settings the Output 5 are disable and make me to believe this is the reason, so is any way to make active like babyware ? or should be activate with some event ?

Why I need it ? I have connect the 24H zone there so I can trigger the alarm without arm the alarm, so if needs active even and someone else has done the settings please share it.

Thank you in advance.

Best Regards,
Tasos

**Comment by tasosstr** [comment]
When I had enable from PGM settings then I can control it.

**Comment by yozik04** [comment]
I like when issues auto resolve for me 😅
It is great you sorted it out!

**Comment by tasosstr** [comment]
@yozik04 Hello my friend, Thank you very much ! ! !
 I like it too :-) and share it for help other people too :-)

And thank you for remind me, I take a screen shoot from the setting I did and working ;-)
![PGM 5](https://user-images.githubusercontent.com/20454403/163049764-c53175ec-bd82-49dc-bab6-5abc51faf676.jpg)

For my case, because when the relay arms then this trigger the 16 Zone, this zone are 24H protector, so  it will trigger alarm on any case, for deactivate the alarm it must send a disam command.

**Comment by arnaudpn** [comment]
Hi @tasosstr ,

I'm trying to do the same for the pgm_5 relay sitting on the main board of my EVO192 (v3.20.016) but I'm having issues to get it working in HA\PAI

In Babyware:
<img width="1083" height="29" alt="Image" src="https://github.com/user-attachments/assets/77605679-d394-42ae-84d6-4f2668e0b541" />

In MQTT Explorer it shows as Disabled:

<img width="187" height="127" alt="Image" src="https://github.com/user-attachments/assets/df730300-d0b7-4557-848c-87b56decb952" />

Pressing the PGM 5 entity results in these errors:

```2026-01-21 00:55:33,244 - INFO     - PAI.paradox.interfaces.mqtt.basic - message topic=paradox/control/outputs/pgm_5, payload=ON
2026-01-21 00:55:33,272 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29
2026-01-21 00:55:34,276 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29
2026-01-21 00:55:36,785 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29
2026-01-21 00:55:37,351 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29
2026-01-21 00:55:38,360 - ERROR    - PAI.paradox.paradox - Got ERROR Message: 29
2026-01-21 00:55:39,342 - ERROR    - PAI.paradox.paradox - control_output timeout
2026-01-21 00:55:39,343 - WARNING  - PAI.paradox.interfaces.mqtt.basic - Output command refused: pgm_5=ON user: None
```

HA\PAI & Babyware connects to the EVO192 through an IP150+ module (I have a serial and I didn't try, I guess it won't change anything).

Is there something that I am missing ?
Maybe an additional / hidden "Enable" option that I didn't find in Babyware ?

PS: I can manually trigger this relay from Babyware succesfully as I can clearly hear it switching state.

Thanks !
a.

**Comment by tasosstr** [comment]
> Hi [@tasosstr](https://github.com/tasosstr) ,
> 
> I'm trying to do the same for the pgm_5 relay sitting on the main board of my EVO192 (v3.20.016) but I'm having issues to get it working in HA\PAI
> 
> In Babyware: <img alt="Image" width="1083" height="29" src="https://private-user-images.githubusercontent.com/15666506/538251004-77605679-d394-42ae-84d6-4f2668e0b541.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjkxOTM5NTAsIm5iZiI6MTc2OTE5MzY1MCwicGF0aCI6Ii8xNTY2NjUwNi81MzgyNTEwMDQtNzc2MDU2NzktZDM5NC00MmFlLTg0ZDYtNGYyNjY4ZTBiNTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTIzVDE4NDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZDcyYjQwNzI2OTIyMmU5N2IzNjI1YzdhM2NmZmFlYjBkZWViNzljYjI3NWJmMjk1ZThjOTI3MDM3YmExYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j46kKNxCS7GdE5XWw9Y3qHxruXEIqAzVudb4IiZhMKY">
> 
> In MQTT Explorer it shows as Disabled:
> <img alt="Image" width="187" height="127" src="https://private-user-images.githubusercontent.com/15666506/538251446-df730300-d0b7-4557-848c-87b56decb952.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjkxOTM5NTAsIm5iZiI6MTc2OTE5MzY1MCwicGF0aCI6Ii8xNTY2NjUwNi81MzgyNTE0NDYtZGY3MzAzMDAtZDBiNy00NTU3LTg0OGMtODdiNTZkZWNiOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTIzVDE4NDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjFjZmI0N2YyNGQ1MGE5MTc3YzI3YTQyMzU5ZDNjNTQ3MWNiYTU2NzYyYzM3YjdiMTRlOWNkMjg3YmMxMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PJXYiy6CbhFX1FYJDMQGO5TOMuHt4UthDk6OtClXVpU">
> 
> Pressing the PGM 5 entity results in these errors:
> 
> `2026-01-21 00:55:33,244 - INFO - PAI.paradox.interfaces.mqtt.basic - message topic=paradox/control/outputs/pgm_5, payload=ON 2026-01-21 00:55:33,272 - ERROR - PAI.paradox.paradox - Got ERROR Message: 29 2026-01-21 00:55:34,276 - ERROR - PAI.paradox.paradox - Got ERROR Message: 29 2026-01-21 00:55:36,785 - ERROR - PAI.paradox.paradox - Got ERROR Message: 29 2026-01-21 00:55:37,351 - ERROR - PAI.paradox.paradox - Got ERROR Message: 29 2026-01-21 00:55:38,360 - ERROR - PAI.paradox.paradox - Got ERROR Message: 29 2026-01-21 00:55:39,342 - ERROR - PAI.paradox.paradox - control_output timeout 2026-01-21 00:55:39,343 - WARNING - PAI.paradox.interfaces.mqtt.basic - Output command refused: pgm_5=ON user: None `
> 
> HA\PAI & Babyware connects to the EVO192 through an IP150+ module (I have a serial and I didn't try, I guess it won't change anything).
> 
> Is there something that I am missing ? Maybe an additional / hidden "Enable" option that I didn't find in Babyware ?
> 
> PS: I can manually trigger this relay from Babyware succesfully as I can clearly hear it switching state.
> 
> Thanks ! a.

Hi arnaudpn,

I am sorry but i don't have EVO and i have no idea with this, but have a look at https://github.com/ParadoxAlarmInterface/pai/wiki/MQTT-Interface maybe there you will find something.

Best Regards,
Tasos

**Comment by arnaudpn** [comment]
Hi @tasosstr 

Thanks for your quick feedback !
In the meantime I have taken a Wireshark trace, I'll share my findings in a separate issue.

Kind regards,
Arnaud.
