### ISSUE TITLE
Much time for load information

### ISSUE THREAD

**Issue by dxcoco2** [ParadoxAlarmInterface/pai#293]
## Alarm system
EVO192 + IP100

## Environment
RPI HASSIO

Hi, i've frequently (every 5-12min max) "disconnection" with the error:
**PAI.paradox.lib.handlers - No handler for message 5**

but I would like to understand why it takes so long to receive the information below (User Definition)

2022-04-19 19:19:03,987 - INFO     - PAI.paradox.hardware.panel - Partition definitions loaded (0.15s)
**2022-04-19 19:19:40,773 - INFO     - PAI.paradox.hardware.panel - User definitions loaded (36.78s)**
2022-04-19 19:19:41,644 - INFO     - PAI.paradox.hardware.panel - Loading labels

Can I skip or speed up this operation?

Thanks

**Comment by yozik04** [comment]
`No handler for message 5` is not a reason of disconnects. It happens when unexpected reply from the panel is received.
We have wiki that covers that. See LIMITS.
