### ISSUE TITLE
IP150+ with firmware > 5.3.0 

### ISSUE THREAD

**Issue by jafar-atili** [ParadoxAlarmInterface/pai#294]
## Alarm system
SP7000 with IP150+

## Question
My IP150+ does not allow http/s connections, after contacting Paradox they said this:

_Dear Jafar,

I would like to let you know that the web interface of the IP150+ was removed in version 5.3.0 for security reasons,
Module's configuration can be accessed from Insite Gold app (Installer section) based on a valid installer/dealer website login.

Thank you._

Then I asked how it can be integrated with 3rd party home automation apps, and they replied:

_Dear Jafar,

Please note that the only integration allowed using the IP150/+ is through our SDK.

I would like to let you know that we have SDK available which is SWAN based (it requires access to internet in order to validate license and to work properly even after software deployment). The SDK can can shared with 3rd party software integration companies once requested by our official distributors. It cannot be send to end customers.

Thank you._

(And they shared PDF of their SDK License agreement)

My Paradox system was installed by me, not installer and I have no dealer to talk with.

My question, having the IP150+ with firmware > 5.3.0, will PAI work in my case?

Thank you!

**Comment by yozik04** [comment]
Yes

**Comment by Emree26** [comment]
Did you install? If you did, can you help me? I am getting unable to connect to alarm error and i tried every avaliaable options.
