### ISSUE TITLE
Home Assistant Trigger Alarm

### ISSUE THREAD

**Issue by madmen2302** [ParadoxAlarmInterface/pai#295]
## Alarm system
Sp4000

## Environment
HOME ASSISTANT RPI 

### Git branch

Home Assistant Add On

## Question

I cant trigger the alarm neither by calling a service or by calling an action. Can anyone help me with this?

**Comment by yozik04** [comment]
Trigger siren or arm the alarm?

**Comment by madmen2302** [comment]
> Trigger siren or arm the alarm?

Trigger the siren

**Comment by yozik04** [comment]
Basically it is the same as described in #162. But I do not remember if you can trigger PGM in SP4000 from PAI.

**Comment by yozik04** [comment]
Actually there is a writeup for SP/MG branch. So it should be supported. Closing this as dupe to #162
