### ISSUE TITLE
Publish TM50 temperature

### ISSUE THREAD

**Issue by ducatidirk** [ParadoxAlarmInterface/pai#296]
I have PAI set up and working nicely for years already, giving me full visibility and control over my Paradox MG5050 system in Home Assistant. Thanks for great work!

Would be really neat if I could get the temperature readings from my TM50 keypads into Home Assistant too. Perhaps someone can add this feature?

**Comment by yozik04** [comment]
The hardest thing is to find that's address in ram memory.

**Comment by brunsy** [comment]
Sorry to revisit such an old issue.
I've found the temperature, although it's in the keypad's own module RAM.
I can see it at Module bus 2, block 0, byte 14 in °C 

So would likely need to implement RAM polling for this....
