### ISSUE TITLE
PAI adjusts time and date every morning at 3am?

### ISSUE THREAD

**Issue by ph33rlus** [ParadoxAlarmInterface/pai#298]
I have an EVO192 panel connected to Home Assistant using an IP150 with the non SWAN firmware. 
I've been running PAI with it perfectly for years. I've also had the IP150 setup to email me troubles which also works well.

Too well. For the last week or 2 I've been seeing emails about Time Date Restore at 3am.
Specifically I get 2. first one where the time is 12 hours out, and then a 2nd email straight after where the time is correct.

Is PAI meant to be screwing with the date and time at all? or is the issue somewhere else?

**Comment by yozik04** [comment]
You can disable time sync if you want.
PAI should fix the time only if it is off by some treshold, which is also configurable.
Check the button battery of the panel.

**Comment by ph33rlus** [comment]
nevermind - i found it *facepalm* thank you!
