### ISSUE TITLE
Question about setup

### ISSUE THREAD

**Issue by pedroandrade1977** [ParadoxAlarmInterface/pai#300]
Hello,

first of all, having gone through the PAI documentation and issues/questions, I can only thank the developers for the time to share this solution and support it for everyone. I have been trying for ages to figure how I can get my alarm to become part of my home automation setup, and I am hoping this will be it.

But I have a couple questions about the setup, prior to get going. Below is my understanding, if something should be different please correct me.

The plan is to:
- Get a USB to TTL cable (4 pin)
- Connect pins to panel as per the pin out diagram, but do not connect the AUX+
-  Connect the USB to a Raspberry PI running Raspbian
- Install PAI and configure with PC password and details of existing MQTT broker in my setup

I will not be using Home Assistant, but my home automation platform (Hubitat) supports MQTT integration, I’ll just need to write a couple of drivers.

Thanks in advance

**Comment by yozik04** [comment]
Looks like a valid plan

**Comment by pedroandrade1977** [comment]
Many thanks will let you know how I will get on ;)

**Comment by pedroandrade1977** [comment]
Hi, so I got the ttl to usb cable, installed pai on a raspberry pi 4 with pip3, had to install additionally Paho MQTT and pyserial, set the config file according to instructions and was getting ready to connect the cable to the panel until… I saw the serial port is already taken by the gsm unit! (I know should have checked first!)

Removed the gsm and managed to connect and am getting auth error (expected as I don’t have the pc pass).

before I go fight with the installer to get the password, and considering that I want to keep the gsm unit, is there any work around for this? The panel is a SP7000, and there is another port in the centre of the board also labelled serial, can this be used? It didn’t work when I connected there, and also the gsm didn’t even light up when I plugged it to this second port, but maybe someone has suggestions.

thanks in advance

**Comment by yozik04** [comment]
Probably the only solution is to buy IP150. IP150 will be connected to panel's serial and GSM will be connected to IP150.

**Comment by pedroandrade1977** [comment]
Thanks a lot. Good thing the cable only cost 3 euros ;) Will think about IP150.

Thinking about trying first cloud connection method, as I am using insite gold through the gsm connection. For this connection also the PC password is used? In insite gold app I connect with my user code.

thanks

**Comment by yozik04** [comment]
PC code as well

**Comment by pedroandrade1977** [comment]
Ok thanks, I have a “installer” or “technician” code which the installer gave me over the phone one day when we needed to change a configuration and he didn’t want to come over. Would I be able to find the PC password with this? In the manual it seems I can change it, but I don’t want to break smth (maybe gsm unit or monitoring station are using it…)

**Comment by yozik04** [comment]
With installer code you can do everything. I do not think PC password is used anywhere.

**Comment by pedroandrade1977** [comment]
So, from what I read, I can have a setup where I have the panel connected with serial cable to IP150+, and the PCS265LTE connected to a PCS Out connection in the IP150+. I suppose one of the two modules would be configured to report to the monitoring station, or maybe one would be a backup for the other - need to check that.

In any case, I understand that with this configuration, as long as the IP150+ has firmware 4.40+ it should allow local connections and be usable with PAI. If I manage to use PAI then I do not need Insite Gold actually and would gladly disable it if possible.

About PC pad, how can I use installer code to find PC password?

Thanks

**Comment by yozik04** [comment]
> About PC pwd, how can I use installer code to find PC password?

Check panel's installer manual.

**Comment by pedroandrade1977** [comment]
Ok, thanks a lot, managed to find it :)

Disconnected the gsm unit, plugged in the serial cable and the raspberry, and it connected. So ultimately managed to make it work.

Now back to the drawing board to try to get a IP150 and get a working setup. In the meantime will whip up the hubitat drivers.

Many thanks for your help, closing the issue now.
