### ISSUE TITLE
Open/close Tamper 

### ISSUE THREAD

**Issue by eternum79** [ParadoxAlarmInterface/pai#301]
What to configure to close or open zones and tamper?  i installed pai via ip.  Sorry but I'm a beginner. thanks

**Comment by yozik04** [comment]
Not enough info.

**Comment by eternum79** [comment]
Let me explain better. With the Swan application I can individually disable the sensors of the zones (bedroom or kitchen or living room ... etc), or the tampers for maintenance. I can't find a way to do it with PAI. I can only see the states of these.
Thank you

**Comment by yozik04** [comment]
Is is home assistant or what? What panel?

**Comment by yozik04** [comment]
Do you mean "bypass zone" instead of "disabling sensors"

**Comment by eternum79** [comment]
> Do you mean "bypass zone" instead of "disabling sensors"
Sorry. Home assistant, panel mg5075, and yes i mean Bypass.

**Comment by yozik04** [comment]
Take a look into our wiki. There is a page regarding event filtering. There should be example with bypass as well.

**Comment by eternum79** [comment]
> Take a look into our wiki. There is a page regarding event filtering. There should be example with bypass as well.

Unfortunately I can't find it. Could you send me the exact link? Thank you very much for your patience

**Comment by yozik04** [comment]
https://github.com/ParadoxAlarmInterface/pai/wiki/Home-Assistant-integration#add-more-properties-to-zones-or-partitions

**Comment by eternum79** [comment]
Thanks a lot, problem solved! Lastly, to receive notify of alarm, or arm/disarm, what guide should I follow? My device is an android.

**Comment by yozik04** [comment]
I use pushover. See wiki.

**Comment by yozik04** [comment]
That was an attempt. I think it is not finished. Something simple is missing there.
