### ISSUE TITLE
issue on passing variables when Linux execution of PAI

### ISSUE THREAD

**Issue by dmylnka** [ParadoxAlarmInterface/pai#302]
i run a linux Ubuntu 20.04 VM and have a fresh install of PAI as described in wiki.
I made the appropriate configuration to /etc/pai/pai.conf and manually execute ./run.sh

So far so good , PAI starts succesfully , connected to IP module and trying to retrieve data from Panel.
I need to experiment with PC Password variable. 

Trying to execute PASSWORD='1213' ./run.sh   i dont see any change as PAI load Password value from /etc/pai/pai,conf.
I experimented with other variables like connection type ot logging level and seems that variables are ignored and retrieved explicity from /etc/pai/pai.conf.

see below an obvious example of connection type= serial and PAI starting with connection to IP

root@ubuntu2004:/home/ubuntu/pai# CONNECTION_TYPE='Serial' ./run.sh     
Attempting to load configuration from /etc/pai/pai.conf
2022-07-14 10:25:40,249 - INFO     - PAI - Starting Paradox Alarm Interface 3.1.0-dev
2022-07-14 10:25:40,249 - INFO     - PAI - Config loaded from /etc/pai/pai.conf
2022-07-14 10:25:40,249 - INFO     - PAI - Console Log level set to 20
2022-07-14 10:25:40,250 - INFO     - PAI - Starting...
2022-07-14 10:25:40,250 - INFO     - PAI.paradox.paradox - Connecting to interface
2022-07-14 10:25:40,250 - INFO     - PAI.paradox.paradox - Using IP Connection

**Comment by yozik04** [comment]
You forgot about “PAI_” prefix

**Comment by dmylnka** [comment]
'thanks for your fast prompt.

To my understanding  you say that  i have to execute " PAI_CONNECTION_TYPE='Serial' " 
excuse me for asking clarifications but this is not something described to https://github.com/ParadoxAlarmInterface/pai/wiki/Manual

**Comment by yozik04** [comment]
I looked it up in the source code :)
If my assumption is right then doc needs fixing.
