### ISSUE TITLE
I have an issue with my ip150, when it's connected to my company network there is no internet light blinking, the IP was set as static to the alarm module and I am able to ping the IP and from my network switch I can see the ip150 Mac add  tagged to IP assigned its up and active. Where as when connected to a public sim card router there is internet light. Can someone pls help with this

### ISSUE THREAD

**Issue by Pream04** [ParadoxAlarmInterface/pai#309]
I have an issue with my ip150, when it's connected to my company network there is no internet light blinking, the IP was set as static to the alarm module and I am able to ping the IP and from my network switch I can see the ip150 Mac add  tagged to IP assigned its up and active. Where as when connected to a public sim card router there is internet light. Can someone pls help with this

_Originally posted by @Pream04 in https://github.com/ParadoxAlarmInterface/pai/issues/118#issuecomment-1219704042_

**Comment by yozik04** [comment]
Closing as it is not related to the project.

**Comment by yozik04** [comment]
Ask in gitter. We have some installers there. Maybe they will be able/willing to help.
