### ISSUE TITLE
Babywire 

### ISSUE THREAD

**Issue by mm84** [ParadoxAlarmInterface/pai#310]
Hi guys,
I have problem with huge delay on PIR. I try to do with performance instruction " In Babyware it is recommended to check System Options -> Communication -> “Transmit zone status on serial port”. This way events will be automatically sent by the panel and received without much delay." But i have problem with connect. Ive version 5.4.3 and I cant connect via LAN. I set IP adress, port 10000 and paradox password. But I still have problem with connect with my panel. 

![image](https://user-images.githubusercontent.com/42741279/185902748-3400930c-84fa-490b-8252-ef374c910415.png)

Anyone have same problem?

**Comment by yozik04** [comment]
Are you connecting via PAI or directly?

**Comment by mm84** [comment]
Tried using babywire. Pai working like a charm (only problem with delay from pir).

Best Regards,
Marcin
________________________________

**Comment by yozik04** [comment]
connect with Babyware directly without PAI. Set the flag "Transmit zone status on serial port". It should help. Or is it set already?

**Comment by mm84** [comment]
But I can't connect to babywire. Still problem from screenshot. I tried everything.

Best Regards,
Marcin
________________________________

**Comment by yozik04** [comment]
maybe panel id is wrong?

**Comment by mm84** [comment]
![image](https://user-images.githubusercontent.com/42741279/187871237-d56da718-f3a8-476a-8481-55c3baf4f01f.png)

Even if i go to settings and klick on magnet - ive get IP, SN, info about DHCP - but when i click Configure - ive error from image. My installer told me that PanelID is default 0000.

**Comment by yozik04** [comment]
Cat it be that there are settings in IP module web interface to enable or disable local access?

**Comment by mm84** [comment]
i cant acess via web - i try 192.168.1.250:80, 192.168.1.250:8080, 192.168.1.250:10000 - nothing.

**Comment by yozik04** [comment]
Then I am out of ideas.

**Comment by mm84** [comment]
Im thinking about send this module for warranty repair. Thanks Yozik!

**Comment by mm84** [comment]
I'll try to contact with my installer. I'll let you know tomorrow. Thanks for tips!

Best Regards,
Marcin
________________________________
