### ISSUE TITLE
How to disconnect from the Paradox panel?

### ISSUE THREAD

**Issue by gaspo100** [ParadoxAlarmInterface/pai#311]
I've got  PAI working with Home Assistant and connected to MG5050 via serial port.
However, when the PAI connects to the panel I cannot access installer menus via LCD32 screen.
Is there a way to tell PAI to disconnect from the panel so that I can make installer changes?

**Comment by yozik04** [comment]
Just stop PAI.

**Comment by gaspo100** [comment]
Thanks, that works, was not sure if it properly closes serial connection to the panel.

**Comment by yozik04** [comment]
Yes. It closes properly.
