### ISSUE TITLE
Toggle for zone bypass

### ISSUE THREAD

**Issue by kurtwarwick-new** [ParadoxAlarmInterface/pai#317]
Hi

Would it be possible to provide an entity that acts as a toggle (switch) for the bypass / clear_bypass of a zone?

I have been manually creating topics for this, which is not entirely ideal. It would be great to get this OOTB, much like the tamper sensor.

Thanks!

Kurt

**Comment by beerygaz** [comment]
Zone bypass switches are there for the dev version in HA, but I just migrated to the main release and they vanished.  I figured that was why the filters were there, but it seems the filters have no bearing on the HA integration creating the bypass switches. #249 refers

**Comment by beerygaz** [comment]
In HA this is possible with the correct filter. Add `bypassed` to `HOMEASSISTANT_PUBLISH_ZONE_PROPERTIES`

**Comment by kurtwarwick-new** [comment]
Thank you so much @beerygaz !

I honestly had no idea about that configuration option.

Thanks again!
