### ISSUE TITLE
MQTT Events delayed or not even fired.

### ISSUE THREAD

**Issue by ValeriJordanov** [ParadoxAlarmInterface/pai#326]
Hello there, first of all I would like to appreciate the hard work of creating this!

**Setup**
- EVO192 (v.7.70.1) connected with IP150+ (v.5.06.014).
___
**Environment**
- The HA instance is installed on VMWare Virtual Machine running Linux (v.5.x) and VMWare is running over Windows 10 PC configured as a local server. PC is connected via LAN directly to the router and the panel is connected via LAN to the router as well. Static IPs are granted on both.
___
**Branch**
- I have followed the initial setup guide and have not tried dev branch as I couldn't find any similar issue, apart from the one from 2019 with Serial connection problem -> https://github.com/ParadoxAlarmInterface/pai/issues/62
___
**Issue**
- So my issue is the following.
I have everything setup and working, however the MQTT events are either really slow to trigger or does not trigger at all.
Example : If a Motion Sensor detects movement longer than 5 to 10 seconds the MQTT event gets fired. However if the Motion is detected for less than this time the event does not get fired at all.
The easiest way to check this is by opening the door which has a sensor. If the door stays open for longer event will be fired, otherwise no.
At first I thought it is a problem from either the motion sensors or the EVO192.
However I have Paradox TM50 as a wall controller and can see once an event happens, and it does react immediately.
I have checked the debug logs, but it has nothing tagged as error or even a problem.
- What I tried.
I tried all kind of restarting, HA Instance, PC, EVO192.

**Pre-Setup Information**
- The company which handles the Alarm setup has configured a Insite Gold connection so I hard-reset the IP150+ module.

**Note**
- Weirdly I am not able to access the IP150 webpage so I am unable to do any configurations there. Also Babyware(v.5.1) crashes.
Any suggestion here would be appreciated as well. I am however able to access the IP150 via "BlueEye" which is the Android app for accessing it, however it is almost the same as InsiteGold and does not really give you any access over anything.

**Comment by yozik04** [comment]
Please find performance related section in the wiki.

**Comment by ValeriJordanov** [comment]
@yozik04 Thank you!
SERIAL_BAUD did nothing, but I expected that as I am connecting via IP Module.
So I have to get my Babywire working now so I can verify the other suggestion there.
Will post results when I do it.

**Comment by ValeriJordanov** [comment]
@yozik04 Babywire took more time configuring than HomeAssistant, MQTT and PAI combined.
However it sort of works faster now. Thanks!

**Comment by lpaolini** [comment]
@ValeriJordanov

I got the same configuration as yours, identical firmware versions for EVO192 and IP150+.

I'm running PAI as a Docker container on a Raspberry Pi4 4GB, which is also running several other containers, including MQTT, and it responds very quickly to events. Zone open events trigger in about one second, but that's due to the 600ms reaction time set in the EVO192 configuration. Zone closed events are fired immediately, in fact.
