### ISSUE TITLE
Optional prefix for Home Assistant autodiscovery entity ID

### ISSUE THREAD

**Issue by clau-bucur** [ParadoxAlarmInterface/pai#329]
Allow adding an optional prefix that will be added to the generated entities ID via autodiscovery in HomeAssistant.

## Feature description
PAI generates alot of entities so it's a good idea to have a way to quickly identify them in different scenarios.
eg.: exclude most of them from recorder (easily done if they are prefixed) and only include a few that are of interest.

Moreover, some of the current entities have IDs that do not hint at all to the PAI integration.
See: `binary_sensor.system_troubles_*` or `sensor.system_power_*`.

**Comment by RaeesD** [comment]
I would like to add that when running a second instance, the system states overlap so you can't see which panel's voltages you are looking at, they report to the same topic paradox/states/system/power/#. Is there any quick fix to this? Recently I had a problem with one panel dying (battery wasn't charging) and then both interfaces went offline/unavailable in HA.

**Comment by yozik04** [comment]
@RaeesD you must override prefix in settings.

**Comment by RaeesD** [comment]
> @RaeesD you must override mqtt prefix in settings.

Thanks for the quick reply.
Is that a line I need to add to the add-on configuration? I don't see an mqtt prefix field in the default options, this is on version 3.2.1.

**Comment by yozik04** [comment]
MQTT_BASE_TOPIC

**Comment by yozik04** [comment]
Done in #389
