### ISSUE TITLE
EVO192 v.7.50.000+ with 307USB

### ISSUE THREAD

**Issue by lpaolini** [ParadoxAlarmInterface/pai#335]
## Alarm system
EVO192 256k 7.70.01

## Question

Changelog for version 7.50.011, as shown in #272, says:

- Added serial port encryption - the serial output will be operational only with Paradox devices (IP150/+, PCS250/260/265/265LTE, USB307)

Would this mean that we can use 307USB for communicating with firmware versions >=7.50.000 ?
Also, If I understand correctly, communication over IP150 introduces a noticeable delay. Could this be a solution?

Thanks.

**Comment by yozik04** [comment]
PAI does not support serial encryption yet.

**Comment by lpaolini** [comment]
I see, but when it says "the serial output will be operational only with Paradox devices (IP150/+, PCS250/260/265/265LTE, USB307)" I think it means that 307USB will handle the encryption/decryption, as the IP150 does. Doesn't it?

**Comment by lpaolini** [comment]
By the way, I've just tried my panel running version 7.70.01 with PAI and here's the log.

```
pai  | 2022-12-21 20:02:07,013 - INFO     - PAI - Starting Paradox Alarm Interface 3.1.0
pai  | 2022-12-21 20:02:07,013 - INFO     - PAI - Config loaded from /etc/pai/pai.conf
pai  | 2022-12-21 20:02:07,014 - INFO     - PAI - Console Log level set to 20
pai  | 2022-12-21 20:02:07,016 - INFO     - PAI - Starting...
pai  | 2022-12-21 20:02:07,017 - INFO     - PAI.paradox.paradox - Connecting to interface
pai  | 2022-12-21 20:02:07,017 - INFO     - PAI.paradox.paradox - Using Serial Connection
pai  | 2022-12-21 20:02:07,026 - INFO     - PAI.paradox.connections.serial_connection - Connecting to serial port /dev/ttyUSB0
pai  | 2022-12-21 20:02:07,036 - INFO     - PAI.paradox.connections.serial_connection - Serial port open
pai  | 2022-12-21 20:02:07,037 - INFO     - PAI.paradox.paradox - Connecting to Panel
pai  | 2022-12-21 20:02:07,058 - INFO     - PAI.paradox.paradox - Panel Identified EVO192  version 7.70 build 1
pai  | 2022-12-21 20:02:07,058 - INFO     - PAI.paradox.paradox - Initiating panel connection
pai  | 2022-12-21 20:02:12,071 - ERROR    - PAI.paradox.paradox - Timeout while connecting to panel. Is an other connection active?
pai  | 2022-12-21 20:02:12,072 - ERROR    - PAI - Unable to connect to alarm
pai  | 2022-12-21 20:02:15,078 - INFO     - PAI - Starting...
...
```

So, it's detecting the panel and the firmware version, but then it doesn't seem to be able talk to it.

**Comment by lpaolini** [comment]
I'm thinking, how can a panel running firmware 7.50+ work with an old IP150 running outdated firmware? This makes me think the panel somehow recognizes it and switches to unencrypted communication over serial. Would that make sense?

**Comment by yozik04** [comment]
> I see, but when it says "the serial output will be operational only with Paradox devices (IP150/+, PCS250/260/265/265LTE, USB307)" I think it means that 307USB will handle the encryption/decryption, as the IP150 does. Doesn't it?

307USB can not handle encryption/decryption. It is just an USB to serial cable.

**Comment by yozik04** [comment]
> I'm thinking, how can a panel running firmware 7.50+ work with an old IP150 running outdated firmware? This makes me think the panel somehow recognizes it and switches to unencrypted communication over serial. Would that make sense?

Maybe they had that serial encryption in the firmware for a long time and made it default just now. You can be right as well, makes sense.
You can try to connect with Babyware using your PL2303 cable and capture the traffic. But I won't have time to dig it myself.

**Comment by yozik04** [comment]
This maybe related https://github.com/ParadoxAlarmInterface/pai/issues/334

**Comment by lpaolini** [comment]
> > I see, but when it says "the serial output will be operational only with Paradox devices (IP150/+, PCS250/260/265/265LTE, USB307)" I think it means that 307USB will handle the encryption/decryption, as the IP150 does. Doesn't it?
> 
> 307USB can not handle encryption/decryption. It is just an USB to serial cable.

Yeah, that's what I thought, but I'm not convinced anymore, as that changelog is quite unclear.
I think I'll get a 307USB and give it a shot. If anyone has already tried that please let me know.

**Comment by lpaolini** [comment]
> > I'm thinking, how can a panel running firmware 7.50+ work with an old IP150 running outdated firmware? This makes me think the panel somehow recognizes it and switches to unencrypted communication over serial. Would that make sense?
> 
> Maybe they had that serial encryption in the firmware for a long time and made it default just now. You can be right as well, makes sense. You can try to connect with Babyware using your PL2303 cable and capture the traffic. But I won't have time to dig it myself.

I really doubt they had encryption ready in old IP150 firmware versions... Instead, I think it's one of following options:

- the panel exchanges version information and then it drops encryption if the IP150 version doesn't support it
- the panel forces IP150 firmware upgrade over the bus

I would almost exclude the second one. It would be very risky as it could break TCP/IP connection with the panel should anything go wrong during the firmware update.
I'll try to get an old IP150 with outdated firmware and capture serial traffic.

**Comment by lpaolini** [comment]
@yozik04 

I've captured a [full conversation](https://docs.google.com/spreadsheets/d/1IbUbwOw7cVvDfT4NGGWAr-qGC-Hl0LwHJ5-5rW9fk_k/edit?usp=sharing), from connection to disconnection, with a test panel with factory configuration.
I would be grateful if you could have a quick look, at least at packet lengths, and see if you notice anything different from a cleartext conversation with an older firmware version.

Actually, It doesn't look properly encrypted to me, as there's a lot of repetitions. If packet lengths match, they might be just scrambled, like XOR'd with a key.

**Comment by yozik04** [comment]
Looks like same story as with #334.

**Comment by yozik04** [comment]
I agree that having regular serial connection and an IP150 connection captures it will be easier to decrypt.

Let's continue in #337 PR.
