### ISSUE TITLE
according to log addons starts and loads, but no entity.

### ISSUE THREAD

**Issue by ravebp** [ParadoxAlarmInterface/pai#339]
Hello
I am quite noob to Homeassistant, but manage to do some things already.
According to to log from this addons, it manages to set up connection, loads the data (Zones, users, etc) But i cannot see any entities.
can someone help me what can be possibly wrong?

**Comment by panbimis** [comment]
same issue here. any help?

**Comment by yozik04** [comment]
is MQTT configured and working? can you see any data with MQTT Explorer?

**Comment by panbimis** [comment]
In my case, there are findings in MQTT Explorer. Actually there is a full list from zones, states etc from the alarm system. But still missing the panel in integrations. There is only the "core-mosqitto" which is already configured. Any ideas?

**Comment by panbimis** [comment]
Yes and it is a full tree. Wierd!
![MQTT_explorer](https://user-images.githubusercontent.com/121890163/211054933-7fdeea04-d106-4d45-b8a6-9dfd3a490d36.png)

**Comment by panbimis** [comment]
Finally I found the issue. The right procedure is to setup the PAI addon, the MQTT addon and when there is succesfull connection to alarm panel only then you have to go to "integrations" and setup the Mosquitto broker. 
By mistake I had setup the Mosquitto broker in "Integrations" before a succsefull connection to alarm panel. I delete it and after restart I configured again and it recognized. 
Thank you for your time! :) Below a screenshot after connection:
![MQTT_explorer2](https://user-images.githubusercontent.com/121890163/211059139-cb7f133c-5f8a-4ffa-b359-5aefcfd62167.png)

**Comment by yozik04** [comment]
Please edit wiki page to help others.
