### ISSUE TITLE
MQTT dash not published

### ISSUE THREAD

**Issue by lpaolini** [ParadoxAlarmInterface/pai#341]
## Alarm system
EVO192 v.7.70.1, IP150+ v.5.6

## Environment
Linux, Docker

## Git branch
serial_encryption

## Describe the bug
```metrics/exchange/pai``` topic is not published.
I saw it for a while, but the file I had pasted in /etc/pai/mqtt_dash.txt was incomplete, so I did it again, removed the topic from MQTT and restarted PAI, but the topic never showed up again. I'm 100% sure I'm doing something silly, but I just can't see it... Probably I have overwritten the topic clicking "publish" on the MQTT Dash Android app, but shouldn't PAI recreate it?

## To Reproduce

mqtt_dash.txt
```
[the default one in config]
```

pai.conf
```
MQTT_DASH_PUBLISH = True
MQTT_DASH_TOPIC = 'metrics/exchange/pai'
MQTT_DASH_TEMPLATE = '/etc/pai/mqtt_dash.txt'
```

I've double checked that /etc/pai/mqtt_dash.txt inside the Docker container contains the right file.

**Comment by yozik04** [comment]
Just use HomeAssistant =)
