### ISSUE TITLE
communication with PRT3 module with EVO192

### ISSUE THREAD

**Issue by Thommy2112** [ParadoxAlarmInterface/pai#348]
## Alarm system
EVO192, ver.: 7.70.1, IP module: IP150, ver.: 5.02.058, PRT3 module.
## Environment
Intel NUC 8GB RAM, 4 cores

PRT3 module props:
ttyUSB0
/dev/serial/by-id/usb-PARADOX_PARADOX_APR-PRT3_a4008049-if00-port0
Alrendszer:
tty
Eszköz útvonala:
/dev/ttyUSB0
Azonosító:
/dev/serial/by-id/usb-PARADOX_PARADOX_APR-PRT3_a4008049-if00-port0
Attribútumok:
DEVLINKS: >-
  /dev/serial/by-id/usb-PARADOX_PARADOX_APR-PRT3_a4008049-if00-port0
  /dev/serial/by-path/pci-0000:00:15.0-usb-0:4:1.0-port0
DEVNAME: /dev/ttyUSB0
DEVPATH: /devices/pci0000:00/0000:00:15.0/usb1/1-4/1-4:1.0/ttyUSB0/tty/ttyUSB0
ID_BUS: usb
ID_MODEL: PARADOX_APR-PRT3
ID_MODEL_ENC: PARADOX\x20APR-PRT3
ID_MODEL_ID: '6001'
ID_PATH: pci-0000:00:15.0-usb-0:4:1.0
ID_PATH_TAG: pci-0000_00_15_0-usb-0_4_1_0
ID_REVISION: '0600'
ID_SERIAL: PARADOX_PARADOX_APR-PRT3_a4008049
ID_SERIAL_SHORT: a4008049
ID_TYPE: generic
ID_USB_DRIVER: ftdi_sio
ID_USB_INTERFACES: ':ffffff:'
ID_USB_INTERFACE_NUM: '00'
ID_VENDOR: PARADOX
ID_VENDOR_ENC: PARADOX
ID_VENDOR_ID: '0403'
MAJOR: '188'
MINOR: '0'
SUBSYSTEM: tty
TAGS: ':systemd:'
USEC_INITIALIZED: '2278593'

Dear Yozik04,
Thank you for the great amount of work you put into the development of pai, it has become a very useful and indispensable addition to HA for me. You are God to me! but I have two specific problems with my system: one is that I cannot establish communication between the EVO192 and a PRT3 module (it works perfectly on an IP module), I also ran the commands on the root interface, but the situation did not change. 
the second one is related to the first one, because there is unfortunately a 20-second delay between the trigger event and the execution with the IP module communication. if the first function doesn't even work, I could use the second one, but a lighting delay of 20 seconds is too much. Please help me to solve the problem. There are no problems with the resources of my system, 8GB RAM, 4 cores, it does all tasks immediately, if I connect the same device with another integration (eg.: zigbee), the status change occurs immediately, only this module has delays. I tried to set the speed of the communication port, I changed the same speed on the module at the same time. I have restarted the integration and the whole system several times, but nothing changes. the error message is always this:

## Logs 
2023-02-16 00:26:33,843 - INFO     - PAI.paradox.paradox - Connecting to interface
2023-02-16 00:26:33,843 - INFO     - PAI.paradox.connections.serial_connection - Connecting to serial port /dev/ttyUSB0
2023-02-16 00:26:33,846 - INFO     - PAI.paradox.connections.serial_connection - Serial port open
2023-02-16 00:26:33,847 - INFO     - PAI.paradox.paradox - Connecting to Panel
2023-02-16 00:26:38,858 - ERROR    - PAI.paradox.paradox - Timeout while connecting to panel. Is an other connection active?
2023-02-16 00:26:38,859 - ERROR    - PAI - Unable to connect to alarm
2023-02-16 00:26:43,865 - INFO     - PAI - Starting...
2023-02-16 00:26:43,865 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2023-02-16 00:26:43,865 - INFO     - PAI.paradox.paradox - Clean Session
2023-02-16 00:26:43,866 - INFO     - PAI.paradox.paradox - Cleaning previous session. Closing connection
2023-02-16 00:26:43,905 - ERROR    - PAI.paradox.connections.protocols - Connection was closed: None
2023-02-16 00:26:43,905 - ERROR    - PAI.paradox.connections.serial_connection - Connection to panel was lost
2023-02-16 00:26:43,907 - INFO     - PAI.paradox.paradox - Disconnected from the Alarm Panel

Thank you for your answer

**Comment by yozik04** [comment]
Regarding the delay try this: https://github.com/ParadoxAlarmInterface/pai/wiki/Configuration#panel-side
I personally do not know what is PRT3 used for =) So I am unable to help here. There might be a different protocol that we do not support.
PAI works directly via Serial or through IP150 module. IP150 method is more plug and play assuming that you have all required passwords. I personally use IP150 method so the code is more ironed out there. Serial communication is a bit less stable, but it is mostly influenced by used SerialToUSB hardware. I see you have EVO192, ver.: 7.70.1 which uses encrypted serial (Starting from 7.50+) and we have not cracked that yet. So go with IP150 method.

**Comment by lpaolini** [comment]
PRT3 is used for integration with other systems through a serial protocol via USB or RS232. It can be used for sending commands (some commands, like arming or disarming the panel) and for receiving events (any event is supported as far as I know). There are many limitations though, e.g. you cannot bypass zones.

**Comment by lpaolini** [comment]
To clarify: PRT3 is *not* a serial interface adapter like 307USB. it implements its own serial protocol.

**Comment by Thommy2112** [comment]
Thank you for your reply, the speed is much better!

**Comment by yozik04** [comment]
No!
