### ISSUE TITLE
Zone status change on MQTT

### ISSUE THREAD

**Issue by ferllings** [ParadoxAlarmInterface/pai#361]
## Alarm system
EVO192, access mode IP150

## Environment
Docker

### Git branch
main

## Question

How can I see the realtime zone status changes on the MQTT? (when the alarm is not armed)
I can see the events on Babyware, but not on MQTT.
Do I need to enable something?
How can I debug this?

Thanks for your help.

**Comment by yozik04** [comment]
See Performance section in The wiki.

**Comment by ferllings** [comment]
Yes, I already saw it. Everything is enabled.

**Comment by yozik04** [comment]
Then it should be almost instant.

**Comment by ferllings** [comment]
I did a fresh install of PAI, with the same config and it's working now.
So closing this ticket
