### ISSUE TITLE
non-truncated message 5 PDU samples

### ISSUE THREAD

**Issue by rtATvw** [ParadoxAlarmInterface/pai#444]
## Alarm system
Panel model: EVO192
Access mode: IP150

## Environment
Alma Linux 9, VM
- Python version: 3.9
- Venv

## Git branch
Release: 3.4.0
Did you tried "dev" branch? No.

## Describe the bug

Possibly interesting variations of mostly non-truncated message 5 PDUs from:
IP(114) Module version 20, firmware: 6.0
EVO192 version 7.70 build 1

## To Reproduce
Connect to IP150 module via ip address and port 10000

## Logs
[message 5.txt](https://github.com/ParadoxAlarmInterface/pai/files/14603191/message.5.txt)

**Comment by rtATvw** [comment]
Additional messages
[message 5.txt](https://github.com/ParadoxAlarmInterface/pai/files/14641381/message.5.txt)

**Comment by yozik04** [comment]
What is PDU?

**Comment by yozik04** [comment]
I am not sure if I will be able to do anything with this info.
