### ISSUE TITLE
Cannot get Pushover to work

### ISSUE THREAD

**Issue by lpaolini** [ParadoxAlarmInterface/pai#452]
## Alarm system
EVO192 7.70.1 + IP150

## Environment
Docker (latest) on Raspberry Pi 4 

## Describe the bug
Using configuration below I get two lines of logging related to Pushover but no notification is sent.
Please note test notifications from Pushover website are correctly delivered.

## To Reproduce
```
PUSHOVER_ENABLE = True
PUSHOVER_KEY = '<Application token>'
PUSHOVER_BROADCAST_KEYS = [{
   'user_key': '<User key>',
   'devices': '*'
}]
PUSHOVER_MIN_EVENT_LEVEL = 'DEBUG'
```
## Logs
```
pai  | 2024-04-09 18:41:20,603 - DEBUG    - MainThread - PAI.paradox.interfaces.interface_manager - Registering PushoverTextInterface
pai  | 2024-04-09 18:41:20,604 - INFO     - PushoverTextInterface - PAI.paradox.interfaces - Starting PushoverTextInterface Interface
```

**Comment by yozik04** [comment]
Checked my keys.
`'user_key': '<User key>',` I use Group Key there for my Delivery Group.

`PUSHOVER_KEY = '<Application token>'` is Application API Token/Key

**Comment by lpaolini** [comment]
I tried creating a delivery group but the result is the same. Just an info log line, no errors, no push notifications.

```pai  | 2024-04-09 20:47:24,893 - INFO     - PAI.paradox.interfaces - Starting PushoverTextInterface Interface```

I'm very confused.

**Comment by lpaolini** [comment]
With the following configuration I get no notifications at all.
```
PUSHOVER_ENABLE = True
PUSHOVER_KEY = '<App key>'
PUSHOVER_BROADCAST_KEYS = [{
   'user_key': '<User key>',
   'devices': '*'
}]
```

But then IT WORKS perfectly well when I also add the following filters, as you suggested.
```
PUSHOVER_EVENT_FILTERS = [
    'live,alarm,-restore',
    'trouble,-clock',
    'live,tamper',
    'live,arm',
    'live,disarm'
]
```

@yozik04 Thanks for your support! It would be worth checking the defaults and updating the wiki if filters are actually required for Pushover to work.
