### ISSUE TITLE
Latest update (after 3.4.0) breaks MQTT initialization

### ISSUE THREAD

**Issue by minagerges** [ParadoxAlarmInterface/pai#457]
Latest update (From Docker Hub) (updated from 3.4.0) fails to initialize MQTT
I'm using Eclipse Mosquitto (docker latest) as MQTT.

updating pai from 3.4.0 fails to initialize MQTT complaining about API version > 2

So related to https://github.com/ParadoxAlarmInterface/pai/commit/9dbe5bca25608bfe1b7265cdf0a4f0fbfdb4acde

WHY?? I rolled back to pai 3.4.0 and now working.

**Comment by yozik04** [comment]
3.4.0 is the latest at the moment

**Comment by minagerges** [comment]
What's that "latest" pushed then ?
![image](https://github.com/ParadoxAlarmInterface/pai/assets/8280908/0c251024-674e-4b9b-82e2-1ba2215afff2)

**Comment by yozik04** [comment]
I think dev branch went there. Need to check.

**Comment by yozik04** [comment]
`latest` was latest commit to `master`. Now it is equal to latest released version and will continue to be. I made more standard tagging now. Pick which you like https://hub.docker.com/repository/docker/paradoxalarminterface/pai/general
issue with Paho MQTT version should be resolved in 3.4.1.
