### ISSUE TITLE
Home Assistant Core 2024.6 update ruins PAI

### ISSUE THREAD

**Issue by halmaizsolt92** [ParadoxAlarmInterface/pai#466]
After update, I wanted to arm my system, and it only gave me back an error message:
Validation error: arming requires a code, but non was given for '_entity_'

After restoring the previous version it works again (2024.5.5)

![image](https://github.com/ParadoxAlarmInterface/pai/assets/160393889/73eef450-934a-4319-aef2-c9e50fc225f9)

**Comment by PilgrimToHyperion** [comment]
Fix is to go the each partition entity you have and enter your code there. It'll then work like before.

This is what seems to have broken it:
![image](https://github.com/ParadoxAlarmInterface/pai/assets/28935079/3c8d668c-aa38-4534-94dd-75d58a7e1ad0)

**Comment by halmaizsolt92** [comment]
Thank you, it works!

**Comment by rogercrespo** [comment]
Where do you put the code?

**Comment by halmaizsolt92** [comment]
After update, in the partition entity setting, there is a new line: default code

![Screenshot_20240606_211333_Home Assistant](https://github.com/ParadoxAlarmInterface/pai/assets/160393889/9fec9cd1-8161-4109-b3e3-8f4abc63c19d)

**Comment by rogercrespo** [comment]
> After update, in the partition entity setting, there is a new line: default code
> 
> ![Screenshot_20240606_211333_Home Assistant](https://github.com/ParadoxAlarmInterface/pai/assets/160393889/9fec9cd1-8161-4109-b3e3-8f4abc63c19d)
> 

Thank you, solved.

**Comment by yozik04** [comment]
And what code you enter there?

**Comment by PilgrimToHyperion** [comment]
> And what code you enter there?

The code to arm / disarm the alarm.

**Comment by GitittomeNow** [comment]
Not sure why this is closed as there is no option to say pin is not required.

**Comment by yozik04** [comment]
> Not sure why this is closed as there is no option to say pin is not required.

I assume you were not on dev branch where we had the fix. I have Released 3.5.0. Feel free to update and verify.
