### ISSUE TITLE
Core update 2024.6.1 breaks the arming function

### ISSUE THREAD

**Issue by TamasAntal** [ParadoxAlarmInterface/pai#468]
Hi yozik04!

I have an EVO192. after installing core update 2024.5.5 and 2024.6.1 together, arming stopped working. It returns a message saying that arming requires a code, but pay did not return any. Or something similar. I have restored to core 2024.5.4, and arming works again...
Oh, and I have not had arming enabled before.

It would be so nice to get an update for this, as the alarm system is quite essential :) 

thanks!

## Alarm system
Describe your panel model (ex: EVO192, Spectra SP4000, Magellan MG5050), access mode (Serial, IP150, etc..).

## Environment
- Windows, Linux, RPI...
- Python version

## Git branch
Which Git branch you use. Did you tried "dev" branch? Please try before posting.

## To Reproduce
1. Start script '...'
2. Do something '....'
3. See error

## Logs
PLEASE DO NOT SEND LOGS IN CLEAR TEXT AS THEY MAY CONTAIN SENSITIVE INFORMATION
If you wish to add a log (which will greatly help us), please follow the following instructions:

1. Go to https://keybase.io/encrypt
2. Write to us
   1. Write 'jpbarraca' as the recipient if you have SP/MG panel
   2. Write 'yozik04' as the recipient if you have EVO panel
3. Write your log or add a link to the log file (if using services such as dropbox).
4. Click Encrypt
5. Save the result to a text file and add it as an attachment.

**Comment by uwan-cm** [comment]
I have the exact same issue. Waiting for a work around on this or an update to the integration.

**Comment by yozik04** [comment]
I am not sure if I need to update anything on my end or it is a HA bug.

**Comment by nor500** [comment]
Same problem for me. Have you got any temporary workaround?

**Comment by EtienneMD** [comment]
Code validation is now a mandatory option and defaults to `True`.

`code_arm_required` needs to be set to `False` in the configuration.

 https://developers.home-assistant.io/blog/2024/05/22/alarm_control_panel_validation/

**Comment by karamfil** [comment]
Is this something we need to do in the config somewhere and how, or is this PAI code change?

**Comment by uwan-cm** [comment]
> Is this something we need to do in the config somewhere and how, or is this PAI code change?

It was something new that got introduced in HA.  To fix it, just go to Settings > Devices & Services > Entities tab and click on your Alarm Panel entity and then on the settings icon on the popup.  You will see there is a setting for "Default Code", so just enter your alarm panel arming code there and save.

**Comment by TamasAntal** [comment]
Thanks a lot for the advice, adding the default code at the entity solved the issue. And the speedy answer... awesome!
