### ISSUE TITLE
Need to help about decode/encode data

### ISSUE THREAD

**Issue by hpbchung** [ParadoxAlarmInterface/pai#488]
## Alarm system
EVO192

## Environment
Windows

## Question
Hi guys, I have a project using Arduino to read the alarm status for each zone of the EVO192 model via serial communication. Could you provide me with an example file that shows how to encode the byte data for sending and how to decode the byte data upon receipt?

**Comment by yozik04** [comment]
It is not that easy. You need to connect and authenticate first (~5 requests). Then read RAM in certain address range block by block. You will get a binary back that you will need to decode each bit/byte you receive.

**Comment by hpbchung** [comment]
Yes, I know, and I have dumped the data like in the attached file, but I don't understand how to send the data and parse the received data because the bytes sent each time are not consistent enough to identify a pattern. If possible, could you explain or help me by writing a C file for some examples of sending and receiving data like this?
[COM13.pdf](https://github.com/user-attachments/files/16679590/COM13.pdf)

**Comment by yozik04** [comment]
Sorry, I will not write any code for you :), but you can lookup what Python code does in my repo and replicate that to your C code. Sometimes unit tests show the process better. Certainly look there as well.

**Comment by hpbchung** [comment]
Thanks for your help and have a nice day!
