### ISSUE TITLE
 urllib3 v2 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by minhsu12113** [ParadoxAlarmInterface/pai#497]
## Alarm system
 IP150

## Environment
- Linux, 
- Python 3.8

## Describe the bug
something wrong with urllib3 v2 

## Config

> LOGGING_LEVEL_CONSOLE = logging.INFO
LOGGING_LEVEL_FILE = logging.ERROR
LOGGING_FILE = None
CONNECTION_TYPE = 'IP'              
IP_CONNECTION_HOST = '192.168.1.157'
IP_CONNECTION_PORT = 10000 
IP_CONNECTION_PASSWORD = 'paradox'
IP_CONNECTION_SITEID = None
IP_CONNECTION_EMAIL = None
IP_CONNECTION_PANEL_SERIAL = None 
# IP_CONNECTION_BARE = False

## To Reproduce
1. Start script **./run.sh -c pai.conf** 

## Logs

> Traceback (most recent call last):
  File "/home/lovad/pai/paradox/main.py", line 63, in exit_handler
    await alarm.disconnect()
  File "/home/lovad/pai/paradox/paradox.py", line 648, in disconnect
    self._clean_session()
  File "/home/lovad/pai/paradox/paradox.py", line 670, in _clean_session
    if self.connection.connected:
  File "/home/lovad/pai/paradox/paradox.py", line 96, in connection
    from paradox.connections.ip.connection import LocalIPConnection
  File "/home/lovad/pai/paradox/connections/ip/connection.py", line 11, in <module>
    from paradox.connections.ip.stun_session import StunSession
  File "/home/lovad/pai/paradox/connections/ip/stun_session.py", line 7, in <module>
    import requests
  File "/usr/local/lib/python3.8/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.8/site-packages/urllib3/__init__.py", line 42, in <module>
    raise ImportError(
ImportError: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2g  1 Mar 2016'. See: https://github.com/urllib3/urllib3/issues/2168
Task exception was never retrieved
future: <Task finished name='Task-13' coro=<exit_handler() done, defined at /home/lovad/pai/paradox/main.py:56> exception=ImportError("urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2g  1 Mar 2016'. See: https://github.com/urllib3/urllib3/issues/2168")>

**Comment by minhsu12113** [comment]
after install **pip install urllib3==1.26.6** it work

**Comment by yozik04** [comment]
What was before urllib3==1.26.6 ?

**Comment by minhsu12113** [comment]
> What was before urllib3==1.26.6 ?

Seem to 1.0.2g

> ImportError: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2g  1 Mar 2016'. See: https://github.com/urllib3/urllib3/issues/2168
