### ISSUE TITLE
Companion App Notifications

### ISSUE THREAD

**Issue by camsaway** [ParadoxAlarmInterface/pai#516]
## Alarm system
SP6000 with IP150 to HASS

## Environment
HASSOS on Bare Metal Mini PC
Companion App latest Android Release

### Git branch
Master/Main
No didnt' try Beta

## Question
Since this last PAI update (about 2 weeks) all my devices and panels sound an android alarm if the SP6000 alarm is triggered and I have to dismiss them all individually (4 phones and 3 panels). I assume this is related to "Making Home Assistant Notifcations Work" part of the release.

While I like the functionality, I don't want it to automatically do this for all HASS Companion Apps (Phones and Panels) - I would like it to only trigger on one of my phones.

What is the correct way to disable these notifications? Do I have to silence alarm_stream notifications on each device or can it be done centrally? Or can I disable the notifications in PAI configuration (I'm concerned that if I disable in PAI config then the events won't be sent to HASS at all - I do run automations already on the basis of alarm activation).

## Logs (if required)
N/A

**Comment by yozik04** [comment]
You should change next setting. Default is:
`HOMEASSISTANT_NOTIFICATIONS_NOTIFIER_NAME='notify'`

Direct your notifications to any other gorup/device.
`HOMEASSISTANT_NOTIFICATIONS_NOTIFIER_NAME='mobile_app_<blabla>'`

You can lookup valid names in Developer's panel. I think the tab is called Actions now. Filter services starting with 'notify.'.

If you want you can create a notification group and send notifications there.
