### ISSUE TITLE
Docker image for Raspberry Pi

### ISSUE THREAD

**Issue by radokristof** [ParadoxAlarmInterface/pai#72]
**System**
Raspberry Pi 3B+ (ARM which matters)

**Describe the bug**
Can't use the Docker image provided by the Docker Hub on Raspberry Pi because I get the following error:

standard_init_linux.go:207: exec user process caused "exec format error"

**Comment by radokristof** [comment]
Building it manually helps, but I get a PermissionError:

`Traceback (most recent call last):
  File "run.py", line 10, in <module>
    main.main(args)
  File "/usr/local/pai/paradox/main.py", line 79, in main
    config_logger(logger)
  File "/usr/local/pai/paradox/main.py", line 38, in config_logger
    encoding=None, delay=0)
  File "/usr/local/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/pai/paradox.log'
`

Looking into the Dockerfile it seems that there is not a command to own the /var/log folder?

**Comment by yozik04** [comment]
If you can fix and make a pull request it would be great. I do not use docker.

**Comment by radokristof** [comment]
Ok I will try. Until then, do you have a linux service conf which will run this script?

**Comment by yozik04** [comment]
Please try to build docker container from "dev" branch. I rewrote part of it some time ago and I remember it was working.

Or setup systemd
```
$ cat /etc/systemd/system/paradox.service
[Unit]
Description=Paradox service
After=NetworkManager-wait-online.service network.target

[Service]
ExecStart=/usr/bin/python3 /home/user/services/paradox/run.py
User=yozik
Group=nogroup
Restart=always
SyslogIdentifier=paradox

[Install]
WantedBy=multi-user.target
```

**Comment by radokristof** [comment]
Thanks I got it working with a service.
I have tried it with the dev branch... had the issue above.

**Comment by psyciknz** [comment]
How do you want to do arm builds for docker?  Would you prefer specific arm dockerfiles?  or use a common one with a docker build script to activate qemu (if built on something other than arm).

I can contribute this, I've done it for my paradox service...but I may migrate to using PAI.

**Comment by yozik04** [comment]
Raspberry PI is from what arch?
https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by psyciknz** [comment]
It’s arm32.   It depending on raspberry pi version depends if arm32v6 or arm32v7.

You can build on a pc (amd Linux) with qemu.  But you can’t (or I couldn’t work it out) how to get dockerhub to auto build for arm.

**Comment by jpbarraca** [comment]
Dockerhub uses Ubuntu x86 hosts to build the images. We can use qemu to build arm images automatically, or at least they state that we can by using some of the available hooks. Must try and see can really be done.

**Comment by psyciknz** [comment]
Yeah I spent a week trying to do it via automated.....ended up building on a local ubuntu machine and pushing to image to dockerhub.

I think there's more likely of success if using something like travis-ci to do the automation.

**Comment by yozik04** [comment]
We should build it with travis like here:
https://github.com/sealsystems/docker-swarm-visualizer

**Comment by yozik04** [comment]
Another good source to solve this: https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

Dockerfile:
https://github.com/petrosagg/armv7hf-python-dockerhub

Should not be hard...

**Comment by psyciknz** [comment]
> Another good source to solve this: https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/
> 
> Dockerfile:
> https://github.com/petrosagg/armv7hf-python-dockerhub
> 
> Should not be hard...

Yeah Its not hard with qemu.  But most of those posts rely on a machine to do it.  Whereas with a project like this we'd want some sort of CI to do it.  The travis method is probably best.  You should be able to script travis to do qemu as well.  Then its up to the profect if you run 3 (or more) docker files (armhf, aarch64 amd64), or a method I'd found a while back is you make one docker file, and on build copy it to the architectures  then build.  Means you only have one docker file to edit and maintain rather than 3.

**Comment by radokristof** [comment]
https://github.com/travis-ci/travis-ci/issues/3376 
Maybe this can help? I highly doubt that there are no projects out there which uses travis to automatically deploy images/docker images for multiple platforms...

**Comment by IoTPlay** [comment]
Yes please !!!!

**Comment by yozik04** [comment]
Looks like this way it can be build for RPi now.
`
docker build --build-arg ARCH="arm32v7/" .
`

**Comment by IoTPlay** [comment]
Hi @radokristof , have you been able to get a Dockerfile working with the problem you reported? : 
```
Permission denied: '/var/log/pai/paradox.log'
```

**Comment by ivmarkov** [comment]
> Hi @radokristof , have you been able to get a Dockerfile working with the problem you reported? :
> 
> ```
> Permission denied: '/var/log/pai/paradox.log'
> ```

Please check [here](https://github.com/ParadoxAlarmInterface/pai/issues/102#issuecomment-557902195) for an explanation why this happens, and the solution (use docker's "--user" flag with `docker run`).

**Comment by ivmarkov** [comment]
> Looks like this way it can be build for RPi now.
> `docker build --build-arg ARCH="arm32v7/" .`

Alternatively, from Docker 19.03 onward, one can also easily build a multi-arch image. Here's all I had to do - using Docker Desktop with experimental options enabled - to build and push a multi-arch image of the master branch:
- `git clone https://github.com/ParadoxAlarmInterface/pai.git`
- `docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t batvanyovanistia/pai --push .`

Now, if only we can run Docker 19.03 + buildx either on Travis, or in Docker Hub's own build environment, providing not just an image for Raspberry Pi, but a multi-platform one would be super easy.

**Comment by yozik04** [comment]
Please test images from here:
https://hub.docker.com/r/paradoxalarminterface/pai/tags

**Comment by radokristof** [comment]
It seems working, so I close this issue.
