### ISSUE TITLE
Development: adding homie

### ISSUE THREAD

**Issue by psyciknz** [ParadoxAlarmInterface/pai#75]
I want to add homie for mqtt (as well as mqtt).  This supports discoverability for home assistant and openhab (2.4 mqtt).

So I think https://github.com/mjcumming/HomieV3 might be a good one to integrate...mostly because it's v3 which is what is needed.

I think the best way to do it, it to create a copy of the MQTT_Interface.py and modify it.

But the main thing that is needed, is a list of all the 'things'  that can be utilised.  If I can read the code properly, the MQTT_Interface is only called when there's a value change.  Is there a global registry of zones/partitions etc, or will I need to update the main classes so that when reading the items labels from the panel that Homie_MQTT_Interface is called to create all the items so they can be advertised.

**Comment by psyciknz** [comment]
So in Paradox.py, is `self.data` the list of items (and states) and `await self.panel.update_labels()` is where it's updated (as part of connect_async).

So to me this would be the logical place that I should fire off an advertise items to the interface manager, where if the interface supports it, it will broadcast all the panel labels.

**Comment by jpbarraca** [comment]
I think this should be done in a dedicated interface.
Paradox.py can notify the interfaces that it finished loading all labels and properties. This will happen after the labels are loaded and the first round of status messages is received.

**Comment by psyciknz** [comment]
So when I'm looking at the things that an interface can do, I can see "change" and handle_change.  Change seems to add stuff to a queue that is then triggered off and processed by handle_change.

Do I have that correct?

I'm thinking of doing the same, making an advertise_items which adds to a queue, then a handle_advertise_items that will then take all those items, create nodes for them (which will have to be stored in the interface for later use) to advertise their existence.

Then when a change state is called, use the stored node to post out an updated state.

**Comment by jpbarraca** [comment]
The change method is called with the initial state, and with changes. You can use this to register new items for advertisement.
Probably this will be enough for your use case.

**Comment by yozik04** [comment]
Maybe we want to integrate this one?
https://github.com/jalmeroth/homie-python/pull/47
It is not merged yet. But will be some day.

**Comment by yozik04** [comment]
I want to propose architecture change for PAI.
We should use publish subscribe model for interfaces. Core will produce events and interfaces will subscribe to them. Every interface would listen to the events it wants.

**Comment by jpbarraca** [comment]
agree :) 0MQ?
There is the issue that interfaces may consult the Paradox class for some things, or send messages to Paradox. Your change would imply an extended decoupling, and the Paradox class would also receive events. With the asyncio implementation that is possible to be done.

**Comment by psyciknz** [comment]
Re using the jalmeroth one.   I did look at that, but that’s v2 home and there’s a pr open for 3 but it hasn’t been touched in months.   So while I have used that one in the past the mjcunming one is active.

I also think it fits in better with pai as each device is independent.   With the other one, it has to track its own loop. 

That said if enough people are keen I can switch.

**Comment by yozik04** [comment]
I have not inspected any of them. Just saw a link from main homie repo. I am ok with your proposal :)

**Comment by psyciknz** [comment]
> The change method is called with the initial state, and with changes. You can use this to register new items for advertisement.
> Probably this will be enough for your use case.

So after reading the labels, would I just iterate over all items and call interfacemanager.change?

**Comment by blademckain** [comment]
+1 need homie

**Comment by jpbarraca** [comment]
@psyciknz you will get full knowledge of the properties after the first round of status messages.
The interfaces will be notified for every property and its value. You can receive these events and keep the structure private in the interface.

**Comment by yozik04** [comment]
I have tried https://github.com/mjcumming/HomieV3 with openhab 2.4 MQTT binding on a temperature sensor. Seems OKish.

The bad thing that thing status changes to: OFFLINE - GONE periodically. But uptime is updated properly every 60 seconds.

**Comment by psyciknz** [comment]
> @psyciknz you will get full knowledge of the properties after the first round of status messages.
> The interfaces will be notified for every property and its value. You can receive these events and keep the structure private in the interface.

So I've been digging into the structure some more  it's taken me quite a bit to figure out where events are fired from and processed.

I've made a new interface, and it gets the change and notify events.

The first status messages, that would be the change event...and I assume I'll just have to track that it's the first one, or can I use that initial variable...as I'll have to do something on the first one to advertise all the values, and after that, it's just state changes.

**Comment by yozik04** [comment]
@psyciknz I have added publish subscribe stuff to the core. You can subscribe to "labels_loaded" in your binding to activate it.

```python
from paradox.lib import ps
ps.subscribe(listener, 'labels_loaded')
```

What other events you need?

**Comment by psyciknz** [comment]
No worries.  I was using the changes event to get some initial readings.  My main issue is the homie library I'm using it not publishing properties.   I may look at forking it and including in in the interface so I can alter it, othewise I'm stuck between two projects.

**Comment by jpbarraca** [comment]
We changed the way interfaces work and I started playing with the homie format. With the correct lib it can be integrated. 

 Did you made any progress here?

**Comment by psyciknz** [comment]
Only a little.  Had issues with the library I was trying to use, so was going to build it in, then got busy.  What library did you look at?

**Comment by jpbarraca** [comment]
homie and homie3. In order to support homie3.0.1 there seems to be some boilerplate needed.

**Comment by psyciknz** [comment]
I want to get back on to this.  Just this past couple of days I’ve been converting some raspberry pi scripts to the jalroth version of homie ( 3.0.1 branch).

I’ll see how much of a fit this is for a new mqttinterface

**Comment by yozik04** [comment]
We have too many mqtt topics for homie. Please just do a subset of most relevant.

**Comment by psyciknz** [comment]
Yeah I was thinking I’d have to have some sort of filter in the config to restrict it. 

Also just because it has all these channels, it doesn’t mean they all need to be assigned an item (to use openHAB terminology)

**Comment by jpbarraca** [comment]
Added a small interface that exports everything in the homie 2.0 format. Have to check what are the differences between versions and if we really need an external lib.

**Comment by psyciknz** [comment]
Yeah you could definitely just do it without an external library.   Just need to structure it all properly and hit the specification. 

Is that your preference?

**Comment by jpbarraca** [comment]
I don't see the python&homie landscape that stable. 
The spec is getting more complex and a lib could help us offload the evolution to new versions. But the libs are introducing changes in their API as they support newer specs. The differences between python-homie and python-homie3 seem to be very relevant. 

The current version uses homie v2 and was started a few months ago. I would prefer supporting homie3 and have to see what is required.

**Comment by yozik04** [comment]
Openhab's HomeAssistant MQTT component getting better and better every day. Already workable solution on latest 2.5 snapshot.

**Comment by yozik04** [comment]
https://github.com/mjcumming/HomieV3 was added to https://homieiot.github.io/implementations/ page. So it should be good to go.

**Comment by psyciknz** [comment]
The stuff Ive been doing at home this week has been moving mqtt python scripts  to homie v3.0.1 and esp8266 devices. 

So it would make sense (since that seems to be the best supported for discovery) to use at least the v3 homie specification.

I had been using mjcummings library as it seemed to fit better with pai, so my branch has that. 

I did have an issue with some part of it which stopped me for a bit, I think related to the setting of a device or property and it would fail a check.

**Comment by psyciknz** [comment]
@yozik04. I couldn’t see how ha integrated homie.   Is it just as part of the mqtt platform it does it natively? (I use both openHAB and home assistant)

**Comment by psyciknz** [comment]
@jpbarraca I had a quick look at your homie interface, you're importing homie, which as far as I know is https://github.com/jalmeroth/homie-python  - if you want v3, you need to get branch: https://github.com/bodiroga/homie-python/tree/homie-v3.0.0  - he's done a v3 implementation, which is what I've just been working on.  

The changes to what you have currently is minor.   Are you wanting to continue with it  - As my current homie branch is not compatible with yours , which was using the https://github.com/mjcumming/HomieV3 library.  But I could re-fork and carry on your work

**Comment by jpbarraca** [comment]
This was just a test with some code I had around.
I prefer using your branch :) Is it updated in your fork?

**Comment by psyciknz** [comment]
I've got one that will be based on the mjcumming if I can get that going, but I think it has merge issues with some of the base components..and I took another one using the https://github.com/bodiroga/homie-python/tree/homie-v3.0.0 for homie (taking your code).

I normally merge from your master to pull over any newer code, then just work on my specific homie class to get the extra bits going.

**Comment by jpbarraca** [comment]
if you upload it to Github we may test it in your fork and then merge.

**Comment by psyciknz** [comment]
I'm just working through it again.  Trying to find a point where the labels have been loaded from teh panel, when the interfaces are called.  Or an initial change point (so I can set up all the nodes).

**Comment by psyciknz** [comment]
OK so it took me a bit, but I figured out the changes with your master, and re-integrated.    I also managed to figure out my property problem and so i now have each zone as a node, with the 'open' and 'alarm' properties being loaded and updated.

I definitely need to add a restriction on the zones, it's very noisy in mqtt.  But at least it's fianlly working.

Code here: https://github.com/psyciknz/pai/tree/homie-mjcumming
Requirements.txt adds the link to the github library.

**Comment by yozik04** [comment]
Create a pull request it is easier to see changes and travis will test the code.

**Comment by psyciknz** [comment]
It will test the pull before I merge?

**Comment by yozik04** [comment]
Sure. It won't merge before our approval. Then you will continue to work in your branch and it will update pull request every time you push to your repo.

**Comment by psyciknz** [comment]
> Sure. It won't merge before our approval. Then you will continue to work in your branch and it will update pull request every time you push to your repo.

To master, or is there another branch (the homie one?) I should use?

**Comment by yozik04** [comment]
It is always changeable in the pull request. Do to "dev"

**Comment by jpbarraca** [comment]
Besides the new interface, the homie branch only adds one internal event to signal that all labels and properties are loaded.

**Comment by psyciknz** [comment]
What event is that?  I think I’m just attaching to the first update properties.  I’ll check in so you can see.

**Comment by psyciknz** [comment]
Also be aware at about line 176-186 in Paradox.py I've added some print lines (that proably aren;';t needed now)
https://github.com/jpbarraca/pai/blob/master/paradox/paradox.py
```
await self.panel.update_labels()

            # Update the interface with all of the items (implemented for homie, which will advertise all 
            # of the available items as nodes)
            #self.interface.change(element_type, elements[type_key]['key'],
            #                              property_name, property_value, initial=False)
            try:
                
                for element_type in self.data:
                    print(element_type)
                    if element_type == 'zone':
                        elements = self.data[element_type]
                        for type_key in elements:
                            print (type_key)
                            for property_name in elements[type_key]: # 1 2 3
                                print (property_name)
                                print ("%s-%s=%s" % (type_key,property_name,elements[type_key][property_name]))
                                #self.interface.change(element_type, self.data[element_type]['key'],
                                #                property_name, False, initial=True)
            except:
                pass


            logger.info("Connection OK")
```

**Comment by yozik04** [comment]
use `logger.debug()`
instead of `print()`

**Comment by psyciknz** [comment]
I dont need it at all.   It any more.

But if I wanted to log the homie library, which has logging as well what do I need to do to the logging setup?  Or set up a new one?

**Comment by jpbarraca** [comment]
@psyciknz in the homie branch, paradox.py sends changes, events, and internal messages. The Internal type has one message (properties_enumerated), which is sent after the first run of the status update loop. 
https://github.com/jpbarraca/pai/blob/7f8ab1c1c9ebc6bbd85ad3d425f1b7c3ec2d30cc/paradox/paradox.py#L249

**Comment by yozik04** [comment]
@psyciknz Sorry. I just pushed a large rewrite to Interfaces including MQTT. Cleared up all the mess. I think I broke a lot for you.
You need to create a subclass of `paradox.interfaces.mqtt.core.AbstractMQTTInterface`. Create `homie` file in `paradox/interfaces/mqtt` and it will be separate interface. I will soon do that for homeassistant.

**Comment by psyciknz** [comment]
> @psyciknz in the homie branch, paradox.py sends changes, events, and internal messages. The Internal type has one message (properties_enumerated), which is sent after the first run of the status update loop.
> https://github.com/jpbarraca/pai/blob/7f8ab1c1c9ebc6bbd85ad3d425f1b7c3ec2d30cc/paradox/paradox.py#L249

So I've incorportated parts of the homie branch in mine and picked up the changes to paradox.py and ps.py.

And I've got the sendInternal firing.

In your version of the homie interface, you iterate over a self.cache....but I never actual see anything go into that cache for it to be output.

At the moment I'm creating all my nodes in handle_change (when the element = 'zone' and for certain properties (open and alarm), which seems to trigger early enough.

https://github.com/jpbarraca/pai/pull/93/commits/2ca5625929c2f0f66f94438f0d5c5f2458bba9e1#diff-d8acc877d7f1caf8669a041efa2c3cc3R333

**Comment by psyciknz** [comment]
Ahh I finally saw where cache is being updated:
if self.setup_called: 
            node.setProperty(change['property']).send(change['value'])
        else:
            self.cache['{}-{}-{}'.format(change['type'], change['label'], change['property'])] = change

**Comment by psyciknz** [comment]
OK, think I figured out how to do it now.  Check the pull request.
My pai.conf has 
```
#Homie Interface
HOMIE_INTERFACE_ENABLE = True
HOMIE_BASE_TOPIC = "paradox/homie"
HOMIE_NODE_FILTER = {
                        'zone'      :['open', 'alarm'],
                        'system'    :['vdc', 'dc','battery']
                    }
```
which will create nodes out of all the zones with an open and alarm property (will need a way of reducing this, as mine is creating 32 nodes), then it creates a power node with vdc, dc and battery parameters.  These are created at the setup, then updated.  I think it works well, and now add anything into the pai.conf will add it to the nodes very simply.

**Comment by yozik04** [comment]
Looks like current dev is broken on MG5050

**Comment by jpbarraca** [comment]
I just fixed errors related to the number of elements in the panel. E.g.: the MG5050 has 15 modules, while the status messages report the state of 16 messages.
Is that it?

**Comment by yozik04** [comment]
Most probably. There was number 16 in the exception :)
