### ISSUE TITLE
Alarm Triggered - what goes where

### ISSUE THREAD

**Issue by psyciknz** [ParadoxAlarmInterface/pai#78]
I think I get TRIGGERED in the current_hass topic for mqtt.

But I couldn't figure out if there was a topic somewhere that replicated the email in part telling me what zone is in alarm:
```
Message: Alarm
Partition: 1 - Area 1
Zone: 2 - Family room PIR
In alarm
```

Is there a location in mqtt where this information might be posted?  or would i have to create an entity for each zone on:
```
paradox/states/zones/Zone_08/alarm False
paradox/states/zones/Zone_08/trouble False
```

**Comment by jpbarraca** [comment]
The mqqt interface propagates the property changes it observes. There is some processing related to HA and HomeKit but that's it.

The only thing indicating that a zone is in alarm is the alarm property.

What can be added to help your scenario?

**Comment by psyciknz** [comment]
For openHAB I just run an alarm string to MQTT with the last zone in error.  So you can look back on it.

**Comment by yellowonblack** [comment]
There are few things you can look for:

 - Topic **paradox/states/partitions/PARTITION_LABEL/audible_alarm** - where you have by default **False** and  **True** if one partition is currently generating an alarm. The value resets to **False** when the audible alarm is off. 
 - Topic **paradox/states/partitions/PARTITION_LABEL/alarm_in_memory** - where you have by default **False** and  **True** if one partition was in alarm. The value reset to **False** after you rearm that particular partition. The same behaviour you see in _Insite Gold_ app.

- Topic  **zones  paradox/states/zones/ZONE_LABEL/alarm** - where you  have by default **False** and **True** when the zone is breached
- Topic  **zones  paradox/states/zones/ZONE_LABEL/supervision_trouble** - where you have by default **False** and  **True** if one zone was in alarm. The value reset to **False** after you rearm the partition where the zone is attached. The same behaviour you see in _Insite Gold_ app.

@jpbarraca please correct me if I'm wrong.

**Comment by psyciknz** [comment]
Yes, but to display those to the user, I have to iterate all 32 zones to figure out the one in alarm, where the triggering  item could be posted to a topic.

**Comment by jpbarraca** [comment]
The event reported from the panel doesn't carry the triggering item and we would need to iterate over all of them.

**Comment by psyciknz** [comment]
So you set the triggered/alarm state based on a live event, an din that you don't get the item that set that state?

Ahh ok.  So in HA I guess you could add all alarm topics for an zone to items and use the history to find the triggered one.  Openhab the same.

**Comment by yellowonblack** [comment]
In HA, you have to create binary_sensors for all the zones (at least alarm and supervision_trouble subtopics) in order to see live alarms and/or the zones which generated an alarm since last arming. 
After that you can use <Entity Filter Card> to show only those binary_sensors which are/were in alarm (state_filter: "on")

**Comment by jpbarraca** [comment]
The triggering zone will have the no_delay property set to False. This is what the panel reports but I actually do not know what is the meaning of this property.

**Comment by yozik04** [comment]
In case of alarm `paradox/states/partitions/PARTITION_NAME/current_hass` will have status `triggered`. In `dev` branch.

**Comment by Orgjvr** [comment]
I created this automation to send me a telegram message on which zone triggered. Make sure you receive alarm events on zones in your PAI configuration. Also modify the topic and the split if you are not using the default topic structure.

`alias: Alarm Triggered Message
description: Send a message on Alarm events
trigger:
  - platform: mqtt
    topic: paradox/states/zones/+/alarm
    payload: "True"

condition: []
action:
  - service: notify.telegram_alarms
    data:
      message: "Zone triggered: {{ trigger.topic.split('/')[3] }}"
mode: single`
