### ISSUE TITLE
EVO192 support

### ISSUE THREAD

**Issue by yozik04** [ParadoxAlarmInterface/pai#8]
I am working on EVO192 support.
It has different LiveEvent message:

```
  struct ParadoxPacket { //37 byte
       byte armstatus;       //00
       byte requested_event_nr; //01 0xFF: Event just occurred (serial port only)
       uint16_t event_nr;    //02-03
       byte century;         //04
       byte year;            //05
       byte month;           //06
       byte day;             //07
       byte hour;            //08
       byte minute;          //09
       byte event_group;     //10
       byte partition;       //11
       byte event_1;         //12
       byte event_2;         //13
       char serial_nr[4];    //14-17
       LabelType label_type; //18
       char label[16];       //19-34
       byte not_used;        //35
       byte checksum;        //36
  };

Example Zone Open event:
b'\xe0\xffeb\x14\x12\n\x12\x132\x01\x01\x05\x00\x00\x00\x00\x00\x02Living room     \x00\x1c'
```

@jpbarraca I need some help make code flow to branch into SP/Magellan and EVO.
I will populate EVO part and test with my system.

**Comment by yozik04** [comment]
BTW. Where you got struct documentation? Can you please share.

**Comment by jpbarraca** [comment]
In the initial versions of the paradox_messages file the structs were the ones from EVO . Later I switched to the MGSP format. If you go back in the commit history you will find parsers for EVO. Support for both series will be a nice feature

**Comment by jpbarraca** [comment]
Look in the openhab forum for a Dropbox link related to IP150

**Comment by yozik04** [comment]
Initial EVO192 added in my repo. But I did a large refactoring. Will be hard to merge. Doh...

**Comment by jpbarraca** [comment]
I also did a large refactoring :( as well as added several bugfixes. I propose we load your changes into a different branch, freeze the main branch and work on the new branch carefully. This would keep the commit history from both repositories.

**Comment by yozik04** [comment]
I can try to integrate all your changes. There is only 3-4 conflicting files.

Jevgeni

**Comment by jpbarraca** [comment]
Great. Then issue a pull request.
Because I do not have an EVO, can you maintain the code for these devices?

**Comment by yozik04** [comment]
Yes I can. I will be using it with my home automation system. So it will be tested throughly.

Jevgeni

**Comment by yozik04** [comment]
Linking pull request #10
