### ISSUE TITLE
problem connecting to EVO192 using IP100

### ISSUE THREAD

**Issue by ivanfmartinez** [ParadoxAlarmInterface/pai#80]
**System**
IP100 connected to EVO192

**Describe the bug**
Using latest pai version, trying to use with IP100+EVO192.
It can connect and detect the panel. but results in :
"Authentication Failed. Wrong Password or User Type is not FullMaster?"

Using BabyWare / winload I have 3 configuration items related to the authentication/password 

IP100 password -> pai.conf -> IP_CONNECTION_PASSWORD -> apparently is ok 
PANEL_ID -> pai.conf -> ???????
PC_PASSWORD -> pai.conf -> PASSWORD

**To Reproduce**
python3 run.py

 diff -u config/pai.conf.example pai.conf  | grep "^+" | grep -v LOGGING
+++ pai.conf    2019-05-18 06:00:46.620985934 -0300
+CONNECTION_TYPE = 'IP'                 # Serial or IP
+IP_CONNECTION_HOST = '10.1.0.30'       # IP Module address when using direct IP Connection
+IP_CONNECTION_PASSWORD = b'XXXXXXX'    # IP Module password
+MQTT_HOST = 'mqtt'             # Hostname or address
+IP_INTERFACE_PASSWORD = b'XXXXXX'
+
+STATUS_REQUESTS = list(range(1, 6))
+
+PARTITIONS_CHANGE_NOTIFICATION_IGNORE = [
+  'arm_full',
+  'exit_delay',
+  'all_zone_closed', 
+  'ready',
+  'stay_instant_ready',
+  'force_ready',
+  'entry_delay',
+  'auto_arming_engaged'
+]

**Comment by ivanfmartinez** [comment]
[encrypted-pai.log](https://github.com/jpbarraca/pai/files/3193885/encrypted-pai.log)

**Comment by ivanfmartinez** [comment]
@jpbarraca  Also in the encrypted log you can see pai detect my panel as :+1: 
 Found Panel EVO192 version 3.32 build 16

But using windload/babyware they show the version as 3.20

**Comment by yozik04** [comment]
You have so old firmware version... Did you considered updating?

**Comment by ivanfmartinez** [comment]
Yes, but I don't have access to any new version. If I got the firmware files I can try to update.

**Comment by yozik04** [comment]
Contact me. I'll give you 6.90.005
<nickname>@gmail.com

**Comment by yozik04** [comment]
I personally have EVO192 6.x which as I understand is 128K version. The upgrade pdf document tells "Firmware version 7.01.004 unlocks the processor of the EVO192 panel and enables 256K flash memory instead of 128K.". 😮 So I have 256K on board but only 128K is used now? Interesting...

Do we have people who use PAI with EVO192 256K 7.x? Anyone with IP150 < 1.4 version with it?

**Comment by ivanfmartinez** [comment]
I have updated to 6.86, now pai shows :
 Found Panel EVO192 version 6.134 build 0

Apparently the number should be presented as hex and the pai is showing in decimal.

and the error still the same : 

"PAI.paradox.hardware.evo.panel - Authentication Failed. Wrong Password or User Type is not FullMaster?"

maybe is related to the IP100 module. 

Anyone else has used an IP100 module ?

**Comment by yozik04** [comment]
Mine also shows wrong version as well. I use IP150.
Maybe in your IP100 password is encoded differently.

**Comment by ivanfmartinez** [comment]
As I have seen in the code and debug log the IP100 connection is stablished correctly, the problem is during the EVO authentication. 

But Comparing the winload and pai connection packets :
pai is sending unknown1 as 00 and ecryption as 01.
windload is sending unknown1 as 0a and encryption as ee

If anyone know better this protocol and can help I can send the packet dumps.

**Comment by jpbarraca** [comment]
We should warn users when using firmware versions below v4 as they seem to have slightly different behaviour.

Regarding the messages,  can you change the unknown1 and encrypt in the code and see if it connects?

Also, babyware uses the same values?

**Comment by yellowonblack** [comment]
> I personally have EVO192 6.x which as I understand is 128K version. The upgrade pdf document tells "Firmware version 7.01.004 unlocks the processor of the EVO192 panel and enables 256K flash memory instead of 128K.". 😮 So I have 256K on board but only 128K is used now? Interesting...
> 
> Do we have people who use PAI with EVO192 256K 7.x? Anyone with IP150 < 1.4 version with it?

I use PAI with EVO192 256K 7.x, but over serial. The IP150 is "retired" and the last time I use it was version 4.30 with siteID.

**Comment by ivanfmartinez** [comment]
> We should warn users when using firmware versions below v4 as they seem to have slightly different behaviour.
> 
> Regarding the messages, can you change the unknown1 and encrypt in the code and see if it connects?
> 
> Also, babyware uses the same values?

After changing the values it does not even connect to the ip100 module, and become strange and I have to wait some minutes before trying to connect again.

I will save the Babyware packets to compare also.

**Comment by yozik04** [comment]
Our connection flow is based on Babyware.

**Comment by yozik04** [comment]
Stale...
