### ISSUE TITLE
[homeassistant] arm_stay -> arm_away does not send new status to /current_hass

### ISSUE THREAD

**Issue by yozik04** [ParadoxAlarmInterface/pai#90]
## Describe the bug
If alarm is in any arm state(arm_away->arm_stay, so on) and this state changes to any other arm state. /current_hass topic is not updated.

## To Reproduce
Broken test

<hr/>
Other issues that suffer from the bug: #83, #61

**Comment by jpbarraca** [comment]
We need to record and analyse the multiple sequences from disarm to arm and between arm states. A change results in multiple property updates

**Comment by yozik04** [comment]
Yes. Should be simple to create multiple tests for all the situations.

**Comment by yozik04** [comment]
In my opinion how it usually works.

We get arm=True change via Live message, then status response lets us know if it is stay arm or any other.

Can it be in an opposite order?

**Comment by yozik04** [comment]
@emildevil, @radokristof, @jpbarraca
I think we need to ignore Live event for HASS integration and update armed status only on status response, then we have all the required data to calculate /current_hass properly. That will of course introduce a delay. but we can schedule status request for earlier as soon as we receive Live event about arming.

**Comment by emildevil** [comment]
I couldnt agree more as a single event with the correct state will make it a lot easier - there must be a way as the panel calculates it properly - this is how I had to do it now to get the correct status;

I have a function in nodered that catches the status topics and set 3 global variables. This function feed a Report by Exception node which only passes on data if the payload has changed, remember we get multiple message and I only want one message with the state - to solve the last part of the puzzle i use a trigger node that keep the output from the RBE for 10 seconds, if no other message comes in it sends it, if another comes in it sends the last message. This is to avoid the sequence issue on the message - example if you sleep arm the first message is a arm true followed be a sleep true - this avoids this situation - if arm true received it waits for 10 seconds, if nothing else received it sends the state, if a sleep true is received it sends the sleep true.

So I have 10 seconds delay regardless, would be much better single state from the code.

if ((msg.topic === "paradox/states/partitions/Inside/arm") || (msg.topic === "paradox/states/partitions/Inside/arm_sleep") || (msg.topic === "paradox/states/partitions/Inside/arm_stay")){

if (msg.topic === "paradox/states/partitions/Inside/arm"){
    context.global.inside_arm = msg.payload;}

else if (msg.topic === "paradox/states/partitions/Inside/arm_sleep"){
    context.global.inside_arm_sleep = msg.payload;}

else if (msg.topic === "paradox/states/partitions/Inside/arm_stay"){
    context.global.inside_arm_stay = msg.payload;}

if ((context.global.inside_arm === "True") && (context.global.inside_arm_sleep === "True")){
    context.global.inside = "NIGHT_ARM";}

else if ((context.global.inside_arm === "True") && (context.global.inside_arm_stay === "True")){
    context.global.inside = "STAY_ARM";}

else if ((context.global.inside_arm === "True") && (context.global.inside_arm_stay === "False") && (context.global.inside_arm_sleep === "False")){
    context.global.inside = "AWAY_ARM";}

else if (context.global.inside_arm === "False"){
    context.global.inside = "DISARMED";}

msg.topic   = "homekit/alarm/inside"
msg.payload = context.global.inside;

if (msg.payload === undefined){
return null}
else {return msg}

}

**Comment by yozik04** [comment]
![stay_arming](https://user-images.githubusercontent.com/2420038/63588393-08da8c80-c5af-11e9-8633-b056de47c468.png)

**Comment by emildevil** [comment]
ideally state should be set to arm true/false and the then substate full/sleep/stay - this is easier said than done as the events works quite strange in paradox panels when it comes to partial states like sleep/stay

**Comment by yozik04** [comment]
exit_delay flag may not change at all... So it can not be used as a trigger.
![arming](http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/jpbarraca/pai/master/docs/arming.puml)

**Comment by emildevil** [comment]
what is the best way for me to get the raw panel events in sequence - babyware?

**Comment by yozik04** [comment]
You mean event history?

If realtime then with PAI is easier:
LOGGING_DUMP_PACKETS = True    	# Dump RAW Packets to log
LOGGING_DUMP_MESSAGES = True   	# Dump Messages to log

**Comment by emildevil** [comment]
perfect - let me run through;

**Comment by yozik04** [comment]
Should work in `dev`. Closing. Reopen if needed.
