### ISSUE TITLE
DEV: implement interface test

### ISSUE THREAD

**Issue by psyciknz** [ParadoxAlarmInterface/pai#94]
Obviously with developing the homie interface, I'd love to be able to test it rather than having to start up the entire program.  But not quite experienced enough in pytest to do it.

If you've got some pointers we should work to get some testing of the various interfaces under way.

**Comment by yozik04** [comment]
Some tests are here:
https://github.com/jpbarraca/pai/blob/dev/tests/interfaces/mqtt/test_homeassistant.py
